- CasaCore/url
- CasaCore/versions/0.0.1/requires
- CasaCore/versions/0.0.1/sha1
This is a wrapper for CasaCore, an important library for radio astronomers.
CasaCore currently wraps the necessary functionality for interacting with CasaCore tables and measurement sets (the data format produced by many modern radio telescopes -- eg. the [VLA](http://www.vla.nrao.edu/), [ALMA](http://www.almaobservatory.org/)). In addition, it deals with conversions between various astronomical coordinate systems.
https://github.com/mweastwood/CasaCore.jl
For more information on Casacore: https://code.google.com/p/casacore/
The more feature complete python wrapper (developed at Astron): https://code.google.com/p/pyrap/
> Register CasaCore: v0.0.1

- .test/METADATA.jl
We have enforced this policy manually up to now. Perhaps adding a test for this naming policy to the METADATA tests will help cut down on the need to check URLs of newly registered packages.
I have tested the logic locally and it seems to work. In fact, it picked up several packages whose repository names do not have a `.jl` extension, thus causing Travis to fail:
Perhaps we can ping the authors to get the repos renamed.
> Force package repo names to end in .jl

- .test/METADATA.jl
Currently if there are no tagged versions one would just get a `BoundsError`.
> Better error if package has no tagged versions

- GeometricalPredicates/versions/0.0.4/sha1
- better performance by ~15%
- better compatibility with Julia 0.4 (no warnings)
> Tag GeometricalPredicates v0.0.4

- LatexPrint/url
`LatexPrint` is a module that provides functions to convert standard Julia objects (such as numbers and matrices) into text that is suitable for pasting into LaTeX's math mode. For example, the rational number `3//5` is rendered as `\frac{3}{5}`.
> Register LatexPrint

- IJulia/versions/0.2.1/requires
- IJulia/versions/0.2.1/sha1
Provides support for multiple Julia kernels on Jupyter/IPython 3.0
Ref: JuliaLang/IJulia.jl#280
> Tag IJulia v0.2.1

- .test/METADATA.jl
This PR addresses an edge case observed in #2095 in which a package was
registered and the user attempted to register versions manually but
placed sha1 under `"METADATA/$pkg/versions"` instead of
`"METADATA/$pkg/versions/v0.01"`.
The version check test introduced by #2040 is now placed in a new loop
that runs for each subdirectory of METADATA, regardless of whether each
subdirectory corresponds to a package entry recognized by `Pkg.Read`.
Doing so allows the tests to detect package entries that are
misconfigured and hence not recognized as such by the package manager.
Additionally, `joinpath` is used consistently instead of manually splicing
strings together.
Furthermore, as PEGParser is the only package left without a .jl
extension in #2057, the .jl extension check is now upgraded to an …
> Run version check on all subdirectories of METADATA

- TimeSeries/versions/0.5.7/requires
- TimeSeries/versions/0.5.7/sha1
revert to using the `iround` method that has been deprecated in `v0.4` in favor of `round`
> Tag TimeSeries v0.5.7

- MultivariateStats/versions/0.2.0/requires
- MultivariateStats/versions/0.2.0/sha1
Relaxes some assumptions in classical MDS and allow analyses on non-Float64 data. Also updated to run on Julia 0.4-dev.
> Tag MultivariateStats v0.2.0

- .test/METADATA.jl
Hopefully will avoid Travis 10 min timeout and fix #2355
Also removes special-casing of legacy packages in #2057
> Test: diagnostics output during each stage of testing

- .travis.yml
The Travis status is now completely unusable on Julia release, since the internal consistency check reliably times out Travis, exceeding 10 min with no output.
This PR runs the tests on Julia nightly, which has a speedier Pkg.Entry.check_metadata.
> Run METADATA test on Julia nightly

- MatrixDepot/versions/0.2.5/requires
- MatrixDepot/versions/0.2.5/sha1
Main changes:
* support accessing matrices by number and UnitRange
* matrices in the collection are ordered alphabetically
* temporarily suspend the NIST Matrix Market interface
* use base Matrix Market reader for Julia 0.4
> Tag MatrixDepot v0.2.5

- SkyCoords/url
- SkyCoords/versions/0.1.0/requires
- SkyCoords/versions/0.1.0/sha1
Package for basic conversions between astronomical coordinate systems.
https://github.com/kbarbary/SkyCoords.jl
The name is borrowed from the `astropy.coordinates.SkyCoord` class in Python. "SkyCoordinates" would also be fine with me. Alternatives that I considered were "AstroCoord[inate]s" and "AstroSkyCoord[inate]s". The former is not specific enough and the later is a bit awkward.
> Register SkyCoords.jl

- GLFW/versions/1.0.0-alpha.5/requires
- GLFW/versions/1.0.0-alpha.5/sha1
Fixes some 0.4 warnings and retains 0.3 support via the Compat package.
> Tag GLFW v1.0.0-alpha.5

- Winston/versions/0.11.10/requires
- Winston/versions/0.11.10/sha1
@nolta, I'll give you a chance to decide if this is OK. Winston needs a version bump if Tk is going to start passing its tests, see https://github.com/JuliaLang/Tk.jl/pull/100.
> Tag Winston v0.11.10

- BinDeps/versions/0.3.7/requires
- BinDeps/versions/0.3.8/requires
- BinDeps/versions/0.3.9/requires
I just found out that those versions don't work on julia 0.2.
> Fix BinDeps julia requirements v0.3.7/v0.3.8

- AWS/versions/0.1.8/requires
Last version of AWS.jl that works with Julia 0.3 is only compatible HTTPClient 0.1.4 
See issue - https://github.com/amitmurthy/AWS.jl/issues/29
> Update HTTPClient version dependency of AWS.jl

- .test/METADATA.jl
- .travis.yml
more stable and hopefully fast enough now that pkg speedups were backported
> back to julia release for running travis tests?

- Lumberjack/versions/0.0.5/requires
- Lumberjack/versions/0.0.5/sha1
Now we can support both 0.3 and 0.4, thanks @samtkaplan !
> Tag Lumberjack v0.0.5

- FITSIO/versions/0.8.0/requires
- FITSIO/versions/0.8.0/sha1
Release notes:
- Windows support (32-bit & 64-bit), thanks to help from Tony Kelman
(requires master of BinDeps)
- New method `read_header(hdu, ASCIIString)` returns entire header as
a single string.
- bump cfitsio version from 3.360 to 3.370
- fix `show()` for an empty FITS file.
- fix several issues with `Clong` on 64-bit Windows.
> Tag FITSIO v0.8.0

- Homebrew/versions/0.1.16/requires
- Homebrew/versions/0.1.16/sha1
I've jumped to v0.1.16, since v0.1.15 exists in the Homebrew repository, but wasn't ever actually pushed to METADATA.  This release fixes some issues with the latest 0.4 `using` search methods, as well as brings minimum compatibility up to julia v0.2.
> Release Homebrew v0.1.16

- ConjugatePriors/url
- ConjugatePriors/versions/0.1.0/requires
- ConjugatePriors/versions/0.1.0/sha1
This package was part of Distributions.jl and was separated out in last refactoring (about couple months' ago during the tupocalypse). However, it had not been cleaned up until recently, by @hassaku. (see https://github.com/JuliaStats/ConjugatePriors.jl/pull/3)
Now it passes tests and it is ready to register.
> Register ConjugatePriors and Tag v0.1.0

- Mimi/url
The name here is an instance of the fourth rule of the guidelines for package names: this package implements one of several possible approaches to its domain, and so is using a less systematic name.
> Register Mimi

- SynthesisFilters/url
- SynthesisFilters/versions/0.0.1/requires
- SynthesisFilters/versions/0.0.1/sha1
Speech waveform synthesis filters, especially from mel-generalized cepstrum variants. See https://github.com/r9y9/SynthesisFilters.jl for details. 
Synthesized audio examples (Japanese) are available on [the introduction notebook](http://nbviewer.ipython.org/github/r9y9/SynthesisFilters.jl/blob/master/examples/Introduction%20to%20SynthesisFilters.jl.ipynb).
> Register SynthesisFilters: v0.0.1

- ProjectTemplate/versions/0.0.0/requires
- ProjectTemplate/versions/0.0.1/requires
PkgEval has recorded tests passing on this (although now it doesn't even try to find them), but last commit was Feb 2014, and it is unsupported.
RIP ProjectTemplates.jl
@johnmyleswhite
> Deprecate ProjectTemplate.jl

- Resampling/versions/0.0.0/requires
- SliceSampler/versions/0.0.0/requires
Also managed to include #3303, woops.
Last commit Nov 14, 2013. Package does load on 0.3, but it doesn't work.
RIP Resampling.jl
@johnmyleswhite
> Deprecate Resampling.jl

- SliceSampler/versions/0.0.0/requires
Package redirects to (another) MCMC.jl. Last commit Apr 16, 2013.
RIP SliceSampler.jl
@doobwa
> Deprecate SliceSampler/ doobwa/MCMC

- SystemImageBuilder/versions/0.0.1/requires
- SystemImageBuilder/versions/0.0.2/requires
- SystemImageBuilder/versions/0.0.3/requires
- SystemImageBuilder/versions/0.0.4/requires
- SystemImageBuilder/versions/0.0.5/requires
- SystemImageBuilder/versions/0.0.6/requires
- SystemImageBuilder/versions/0.0.7/requires
Set a max ceiling of 0.3 for SystemImageBuilder - we don't need it on 0.4 any more.
> Deprecate systemimagebuilder

- Etcd/versions/0.0.1/requires
`Current version: 0.0.1 (1 year, 3 months ago)`
Last commit over 1 year ago.
Doesn't seem to work on 0.3 (according to PkgEval).
RIP Etcd.nl
@forio @bass3m
> Deprecate Etcd.jl

- RunTests/versions/0.0.1/requires
- RunTests/versions/0.0.2/requires
- RunTests/versions/0.0.3/requires
Last commit > 1 year ago, last tagged version ~1.5 years ago, doesn't pass its tests on 0.3 or 0.4.
RIP RunTests.jl
@burrowsa
> Deprecate RunTests

- Vega/versions/0.4.0/requires
- Vega/versions/0.4.0/sha1
Bump Vega up to reflect move to vega2 as the base engine for graphics and make Julia code match the documentation examples!
> Tag Vega v0.4.0

- TimeSeries/versions/0.6.0/requires
- TimeSeries/versions/0.6.0/sha1
First version to support only Julia 0.4
> Tag TimeSeries v0.6.0

- IJuliaPortrayals/versions/0.0.3/requires
- IJuliaPortrayals/versions/0.0.3/sha1
Fixes partially-broken constructors for `YouTube` and `Vimeo`.
> Tag IJuliaPortrayals v0.0.3

- MFCC/versions/0.0.2/requires
- MFCC/versions/0.0.2/sha1
Long since this package was updated. 
- added Julia version in REQUIRE
- added minimal consistency test
- Julia 0.4 syntax
- inclusion of higher-level feature calculation routines.
> Tag MFCC v0.0.2, replaces #3431

- BinDeps/versions/0.3.16/requires
- BinDeps/versions/0.3.17/requires
- BinDeps/versions/0.3.17/sha1
Also bump version requirement for BinDeps 0.3.16 to avoid installed by 0.3 users
> Tag BinDeps v0.3.17

- JuliaParser/versions/0.6.3/requires
This has been reported as broken on Julia 0.3, causing Juno to stop working
ref https://groups.google.com/forum/#!topic/julia-users/ntOb9HNm0ac
> Adjust requirements on JuliaParser 0.6.3

- Compat/versions/0.7.1/requires
- Compat/versions/0.7.2/requires
Since they might break 0.3 code
Ref https://github.com/JuliaLang/Compat.jl/pull/143 and https://github.com/JuliaLang/Compat.jl/pull/144 for the fixes.
Cc. @simonster
> Disable Compat 0.7.1 and 0.7.2 for Julia 0.3

- ForwardDiff/versions/0.1.1/requires
- ForwardDiff/versions/0.1.1/sha1
- The target function passed to `jacobian` can now take the form `f!(output, x)` (JuliaDiff/ForwardDiff.jl#45)
- Added a couple more function definitions (JuliaDiff/ForwardDiff.jl#47, JuliaDiff/ForwardDiff.jl#53)
- Better inferencing for `derivative` when the target function is a type (JuliaDiff/ForwardDiff.jl#54)
- Turned on precompilation (JuliaDiff/ForwardDiff.jl#56)
- More robust conversion/promotion rules for nested differentiation (JuliaDiff/ForwardDiff.jl#59)
> Tag ForwardDiff v0.1.1

- .test/METADATA.jl
- .travis.yml
- Packages must now have a julia entry in requires
- Minimum allowed Julia version is v0.3.0
- Minimum allowed package version is v0.0.1
- Also minor cleanup of SHA1 check
Grandfathered exemptions have been granted for the 334 packages whose most recent registered versions do not conform to this policy. (Future PRs for these packages that tag a new version must conform to this new policy.)
> Enforce minimum versions for new package registrations

- ROOT/url
- ROOT/versions/0.0.1/requires
- ROOT/versions/0.0.1/sha1
This library wraps parts of the [ROOT package](https://root.cern.ch/) used in high-energy physics.
> Register ROOT: v0.0.1

- .test/METADATA.jl
A package with no tagged versions cannot be installed by `Pkg.add()`, so including them on the official package list seems to have limited value. I believe the question of registering a package with no tagged version has come up several times.
This PR ~~adds warnings to Travis for packages with no tagged versions.~~ enforces a new policy that new PRs to METADATA that register a new package must also tag at least one version of the package.
21 currently registered packages have no tagged versions and are made exempt from this new policy. They are:
[@jiahao: updated 2015/09/30]
> New packages must have at least one tagged version

- IJulia/versions/1.1.5/requires
- IJulia/versions/1.1.5/sha1
Enables precompilation, fixes a problem with the `notebook()` function with Conda, and makes `notebook()` properly killable.
> Tag IJulia v1.1.5

- ValidatedNumerics/versions/0.1.3/requires
- ValidatedNumerics/versions/0.1.3/sha1
This is the last version that will support Julia v0.3.
> Tag ValidatedNumerics v0.1.3

- Jumos/versions/0.1.0/requires
- Jumos/versions/0.2.0/requires
- Jumos/versions/0.2.1/requires
As I understand it, this package is now deprecated by its author, @Luthaf.
> Deprecate Jumos formally

- KernelDensity/versions/0.1.2/requires
- KernelDensity/versions/0.1.2/sha1
Fixes 0.4 dep warnings, bumps to 0.3 from 0.3-
(one less dep warning for Gadfly!)
> Tag KernelDensity v0.1.2

- README.md
This has come up in discussion before, ref https://github.com/JuliaLang/julia/pull/11910#issuecomment-116295281. We could probably auto-enforce this with a bit of scripting, for now I'm proposing writing this down as a policy.
> RFC: Add explicit requirement for registered packages to have an open source license

- Taro/versions/0.2.1/requires
ref https://github.com/aviks/Taro.jl/commit/ea056e03eec4880231a0cad1819ca78cf92064c4
defensive against the possibility that Taro's direct deps might not depend on Compat forever
cc @aviks
> add Compat to Taro/versions/0.2.1/requires

- LowRankModels/versions/0.1.2/requires
cc @madeleineudell the most recent tag of LowRankModels is failing tests on 0.3
```
julia> @time Pkg.test("LowRankModels")
INFO: Testing LowRankModels
ERROR: type: instantiate_type: expected TypeConstructor, got Function
in include at ./boot.jl:245
in include_from_node1 at ./loading.jl:128
in include at ./boot.jl:245
in include_from_node1 at ./loading.jl:128
in reload_path at loading.jl:152
in _require at loading.jl:67
in require at loading.jl:51
in include at ./boot.jl:245
in include_from_node1 at loading.jl:128
in process_options at ./client.jl:285
in _start at ./client.jl:354
while loading /home/tkelman/.julia/v0.3/LowRankModels/src/glrm.jl, in expression starting on line 10
while loading /home/tkelman/.julia/v0.3/LowRankModels/src/LowRankModels.jl, in expression starting on line 16 …
```
> make most recent LowRankModels tag require 0.4

- CodeTools/versions/0.2.0/requires
- CodeTools/versions/0.2.0/sha1
Just noticed that we have `julia 0.4-` in REQUIRE, should I change this to `julia 0.4`?
> Tag CodeTools v0.2.0

- Mandrill/url
- Mandrill/versions/0.1.0/requires
- Mandrill/versions/0.1.0/sha1
A Julia package for Mandrill's REST API. Mandril is an email delivery provider for transactional emails. 
https://mandrill.com/
https://github.com/aviks/Mandrill.jl
> Register Mandrill: v0.1.0

- Combinatorics/versions/0.3.1/requires
- Combinatorics/versions/0.3.1/sha1
Resolves name clash between code moved out of Base and the methods remaining that throw deprecation errors.
Ref: JuliaLang/Combinatorics.jl#13 JuliaLang/julia#13897 @sbromberger
> Tag Combinatorics v0.3.1 [git://github.com/JuliaLang/Combinatorics.jl.git]

- EvolvingGraphs/versions/0.0.8/requires
- EvolvingGraphs/versions/0.0.8/sha1
v0.0.8 
---------
* define function `matrix` for static graphs
* fix `add_edge!` error for `IntEvolvingGraph`.
* add functions for plotting: `plot` and `save_svg`
* fix Julia v0.4 deprecation
> Tag EvolvingGraphs v0.0.8

- XGBoost/url
The package was moved to dmlc/XGBoost.jl. Pkg.add still works, but Pkg.submit fails due to the move
> Update URL for XGBoost

- KLDivergence/versions/0.0.0/requires
Just saw this when skimming through PkgEval stuff
CC: @johnmyleswhite, who has already put an appropriate warning in the README
> Deprecate KLDivergence

- JuMPeR/versions/0.1.0/requires
- JuMPeR/versions/0.1.1/requires
- JuMPeR/versions/0.1.2/requires
Just to be very defensive, as they are so tightly coupled. I saw a strange downgrade case today because these old versions didn't have upper limits.
> Retroactively tighten JuMPeR requirements

- GitHub/versions/2.0.0/requires
- GitHub/versions/2.0.0/sha1
[obligatory link to package](https://github.com/JuliaWeb/GitHub.jl)
A fair amount of breaking changes have been made since the previous tagged version of GitHub.jl (hence the bump in the major version number). A brief overview:
- v0.3 has been dropped in favor of v0.4.
- [Webhook event handling infrastructure has been added](https://github.com/JuliaWeb/GitHub.jl#handling-webhook-events) (cc @tkelman since you previously expressed some interest in this)
- The package now has tests and tracks code coverage
- A large number of REST wrapper functions have been altered to make the API more consistent/flexible/predictable.
- A fair number of REST wrapper functions have been added to bring GitHub.jl a little bit closer to feature parity with the functionality that GitHub's API exposes (a lot of …
> Tag GitHub v2.0.0

- LightGraphs/versions/0.5.0/requires
- LightGraphs/versions/0.5.0/sha1
This has a few breaking changes but a lot of new functionality:
`stochastic_block_model` has been removed in favor of new Graph constructors that take a type of `StochasticBlockModel` which can handle various random generators
Persistence has been modularized and made consistent: graphs are now loaded using `load()` and `save()` methods with symbols indicating graph type
Static small graphs and MatrixDepot graphs have been moved into a new submodule, LightGraphs.Datasets.
> Tag LightGraphs v0.5.0

- MXNet/versions/0.0.7/requires
- MXNet/versions/0.0.7/sha1
Mainly a minor version tagged to maintain compatibility with Julia 0.4.2.
* Fix compatability with Julia v0.4.2 (@BigEpsilon)
* Metrics in epoch callbacks (@kasiabozek)
> Tag MXNet v0.0.7

- JuMP/versions/0.10.0/requires
- JuMP/versions/0.10.1/requires
- JuMP/versions/0.10.2/requires
- JuMP/versions/0.10.3/requires
- JuMP/versions/0.11.0/requires
- JuMP/versions/0.11.1/requires
- JuMP/versions/0.5.0/requires
- JuMP/versions/0.5.1/requires
- JuMP/versions/0.5.2/requires
- JuMP/versions/0.5.3/requires
- JuMP/versions/0.5.4/requires
- JuMP/versions/0.5.5/requires
- JuMP/versions/0.5.6/requires
- JuMP/versions/0.5.7/requires
- JuMP/versions/0.5.8/requires
- JuMP/versions/0.6.0/requires
- JuMP/versions/0.6.1/requires
- JuMP/versions/0.6.2/requires
- JuMP/versions/0.6.3/requires
- JuMP/versions/0.7.0/requires
- JuMP/versions/0.7.1/requires
- JuMP/versions/0.7.2/requires
- JuMP/versions/0.7.3/requires
- JuMP/versions/0.9.0/requires
- JuMP/versions/0.9.1/requires
- JuMP/versions/0.9.2/requires
- JuMP/versions/0.9.3/requires
ReverseDiffSparse 0.4 (currently being developed at https://github.com/mlubin/ReverseDiffSparse2.jl) will be a completely breaking release. This is still likely a month away, but getting prepared anyway.
> put an upper bound on ReverseDiffSparse dependencies

- Cubature/versions/1.0.10/requires
- Cubature/versions/1.0.10/sha1
Fixes stevengj/Cubature.jl#12 and some deprecation warnings.
> Tag Cubature v1.0.10 [git://github.com/stevengj/Cubature.jl.git]

- Distances/versions/0.2.2/requires
- Distances/versions/0.2.2/sha1
Tagging this as the last julia v0.3 version.
I plan to make a PR for a new v0.3.0  version that is for julia 0.4 only and thereby can remove some dependencies.
> Tag Distances v0.2.2

- AppConf/versions/0.1.0/requires
- Diversity/versions/0.2.4/requires
cc @tmlbl and @richardreeve - both of these tags fail on Julia 0.3. Diversity.jl is fixed on master and just needs a new tag, AppConf.jl can be fixed by https://github.com/tmlbl/AppConf.jl/pull/4. Adjusting the requires of these existing tags so these versions don't get installed by users on Julia 0.3 when they do `Pkg.update()` is good to do in the meantime, will get/keep them passing on PackageEvaluator for one thing.
> Fall back to last passing versions of AppConf and Diversity on Julia 0.3

- Compose/versions/0.4.1/requires
- Compose/versions/0.4.1/sha1
- Gadfly/versions/0.4.1/requires
- Gadfly/versions/0.4.1/sha1
Once again daring in the absence of @dcjones, but this contains several fixes:
Compose:
- `get` nullable fontfamily before writing to file (@darwindarak)
- Apply matrix transforms when resolving points (@rohitvarkey)
- CI fixes (@shashi, @timholy)
- Cairo build fixes (@mortenpi)
- Check whether backend is finished prior to attempting to draw to it. (@Sacha0)
- Escape ampersands (@glesica)
- Escape latex in pgf backend (@bastinat0r)
Gadfly:
- Fixed y-axis bug for histogram2d (@kshyatt)
- Lots of work on color scales (@simleb)
- Improve `spy` plots (@mortenpi)
- Move patchwork conditional loading to `__init__` (@shashi)
- Doc improvements (@simleb, @kshyatt, @amellnik)
> Bump Compose and Gadfly

- Media/versions/0.1.2/requires
Any users still on 0.3 would have their code broken from a Pkg.update
due to the latest tag. Using require bounds correctly makes this easy to avoid.
So does having tests.
> latest tag of Media is broken on Julia 0.3

- PairwiseListMatrices/versions/0.3.0/requires
- PairwiseListMatrices/versions/0.3.0/sha1
This version [adds a **join** method](https://github.com/diegozea/PairwiseListMatrices.jl/blob/master/src/pairwiselistmatrix.jl#L899) needed for [MIToS' Pfam module](https://github.com/diegozea/MIToS.jl/blob/master/src/Pfam/pdb.jl#L148).
> Tag PairwiseListMatrices v0.3.0

- GSL/versions/0.3.0/requires
- GSL/versions/0.3.0/sha1
A bunch of fixes to GSL wrapper functions, especially to the root finding functions (thanks @AndyGreenwell)
Also drops Julia 0.3 support
> Tag GSL v0.3.0 [git://github.com/jiahao/GSL.jl.git]

- PyCall/versions/1.3.0/requires
- PyCall/versions/1.3.0/sha1
Several bugfixes since 1.2, and also drops support for Julia 0.3, which is more trouble than it is worth at this point.
> Tag PyCall v1.3.0

- PDMats/versions/0.4.0/requires
- PDMats/versions/0.4.0/sha1
~~This will break the Distributions tests (though most of the package will work): I'll tag a new version as soon as this is merged.~~
Actually, it won't, someone had the foresight to pre-set the REQUIRE file.
> Tag PDMats v0.4.0

- StochasticSearch/versions/0.2.2/requires
- StochasticSearch/versions/0.2.2/sha1
Major changes:
- The package no longer supports Julia nightly due to breaking changes from Julia **v0.4** to **v0.5**.
- The interface to Optim.jl was removed, since the two packages have very different objectives and the interface was not being used by any code, and could not be used with the latest search techniques.
List of all fixes and changes:
- Update README.md
- Update 'rosenbrock' example.
- Update parameter type in README.
- Remove functions left over from Optim interface
- Remove dependance on Optim.
- Remove unused variable in search techniques.
- Remove unused variable in search blocks.
- Fix #13.
- Add VERSION file.
- Remove support for Julia nightly.
- Add the 'Run' configuration type.
- Distribute RemoteRefs between workers.
- Add a new channel type.
- Change 'Result' …
> Tag StochasticSearch v0.2.2

- Catalan/versions/0.0.0/requires
- Catalan/versions/0.0.1/requires
- Catalan/versions/0.0.2/requires
- Catalan/versions/0.0.3/requires
- MetaTools/versions/0.0.1/requires
- RobustStats/versions/0.0.0/requires
- RobustStats/versions/0.0.1/requires
These all have dependencies on other packages that have already been deprecated. So does PEGParser.jl, but at least that has been fixed on its master and just needs a new tag.
> Deprecate Catalan, MetaTools, RobustStats

- Mayday/url
- Mayday/versions/0.0.1/requires
- Mayday/versions/0.0.1/sha1
Mayday.jl is a package for performing optimization over sums-of-squares polynomials, built on top of JuMP. These polynomials are useful in control theory where we use them to prove that a particular dynamical system will be stable or will remain within some set of states. More concretely, we might use them to prove that an aircraft will remain within some known deviation from its desired trajectory.
I've designed Mayday as an alternative to a couple of other approaches: [SumOfSquaresOptimization](https://github.com/willperry/SumOfSquaresOptimization.jl) and [Polyopt](https://github.com/MOSEK/Polyopt.jl). The primary difference is that Mayday tries to be as small as possible: I'm relying on JuMP for the modeling and optimization, and on MultiPoly.jl for the polynomial representations. …
> Tag and register Mayday.jl

- WriteVTK/versions/0.3.2/requires
- WriteVTK/versions/0.3.2/sha1
Fixes issue with recent version of the BufferedStreams package.
> Tag WriteVTK v0.3.2

- PATHSolver/versions/0.0.5/requires
- PATHSolver/versions/0.0.5/sha1
Now supports Windows both 32bit and 64bit.
> Tag PATHSolver v0.0.5

- Convex/versions/0.0.1/requires
- Convex/versions/0.0.2/requires
- Convex/versions/0.0.3/requires
- Convex/versions/0.0.4/requires
- Convex/versions/0.0.5/requires
- Convex/versions/0.0.6/requires
- Convex/versions/0.1.0/requires
This will keep things working until Convex.jl is updated for MathProgBase 0.5. Only the most recent tag (0.2.0) had a safe upper bound on the dependency.
CC @madeleineudell @tkelman
> upper bound on MathProgBase dependencies for Convex.jl

- VideoIO/versions/0.0.15/requires
ref #5177 and #5182 - this tag was broken on Julia 0.3
cc @kmsquire
> bump minimum julia version on previous tag of VideoIO

- .test/update-redirects.jl
- AWS/url
- Bootstrap/url
- DReal/url
- Discretizers/url
- Formatting/url
- FreeType/url
- JDBC/url
- JLDArchives/url
- Jewel/url
- KDTrees/url
- LNR/url
- Lazy/url
- MacroTools/url
- Markdown/url
- MathLink/url
- Mathematica/url
- Miniball/url
- MultidimensionalTables/url
- MultipleTesting/url
- ObjectiveC/url
- Pardiso/url
- Requires/url
- SQLite/url
- SignedDistanceFields/url
- Soundex/url
- SpikingNetworks/url
- VLFeat/url
- VML/url
- VStatistic/url
And add the script I used to do so. Takes about 4 minutes to run with the current size of METADATA (with some async or only requesting headers you could probably make it much faster, I didn't bother for now) which is a bit too large to run on Travis every time, and these redirects are subject to happen arbitrarily when people rename their accounts or move things rather than just as a consequence of proposed changes here in METADATA.
> Fix redirects

- PyLCM/versions/0.0.3/requires
- PyLCM/versions/0.0.3/sha1
This version brings in fixes related to precompilation with Python modules and fixes the build process for PackageEvaluator and OSX on Travis.
> Tag PyLCM v0.0.3

- LCMGL/url
- LCMGL/versions/0.0.1/requires
- LCMGL/versions/0.0.1/sha1
[LCMGL.jl](https://github.com/rdeits/LCMGL.jl) wraps the [libbot lcmgl package](https://github.com/RobotLocomotion/libbot/tree/master/bot2-lcmgl), which allows OpenGL commands to be executed from a remote process using the [LCM](https://lcm-proj.github.io/) message passing system.
It's a pretty niche application, but I've found it to be quite useful.
Please let me know if there are any issues here, or if this is too niche to be included in METADATA.
> Register and tag LCMGL v0.0.1

- KernelEstimator/versions/0.1.7/requires
- NLsolve/versions/0.7.1/requires
ref https://github.com/JuliaOpt/Optim.jl/issues/217
It only uses linesearch, so it's not affected. I've run the tests in the package as an extra check.
The KernelEstimators will run fine as well.
> Fix Optim version for NLsolve

- FixedSizeArrays/versions/0.2.1/requires
- FixedSizeArrays/versions/0.2.1/sha1
A quick fix for a depwarn oversight in 0.2.0 see #5357 
cc @SimonDanisch Changes here are very minimal vs 0.2.0, I wanted to get this in quickly to fix problems with GeometryTypes tests (which in any case should be upgraded for the new API, but shouldn't just have broken without a depwarn.)
> Tag FixedSizeArrays v0.2.1

- TimeZones/url
Moved TimeZones.jl package to the new JuliaTime org.
> Updated TimeZones.jl URL

- LeastSquaresOptim/versions/0.0.1/requires
- LeastSquaresOptim/versions/0.0.2/requires
- LeastSquaresOptim/versions/0.0.3/requires
ref #5389, jacobian is now gone in 0.2.0
cc @jrevels @matthieugomez 
there's also a new failure in CoordinateTransformations.jl, cc @andyferris, but since that only depends on ForwardDiff in `test/REQUIRE` it needs a new tag to fix.
> Add upper bound on LeastSquaresOptim's ForwardDiff requirement

- MP3/url
- MP3/versions/0.0.1/requires
- MP3/versions/0.0.1/sha1
Hi, [this package](https://github.com/jongwook/MP3.jl) adds support for reading and writing MP3 files, using mpg123 and LAME native library.
This is my first Julia package and I might not be following some rules correctly; please let me know if so.
> Register MP3

- Requests/versions/0.0.1/requires
#5398 had some unintended consequences where if you have the newest
JSON installed and want to install Requests, it prefers installing Requests
0.0.1 instead of downgrading JSON to 0.5.3. JSON may not have been required
here but adding it with an upper bound should make the package resolution better.
> add an unnecessary JSON dependency with bound to Requests 0.0.1

- WAV/versions/0.8.0/requires
- WAV/versions/0.8.0/sha1
Fixes dancasimiro/WAV.jl#35
Various syntax updates for Julia v0.5.0
Drop support for Julia v0.3.x
> Tag WAV v0.8.0 [git://github.com/dancasimiro/WAV.jl.git]

- Plotly/versions/0.0.1/requires
- Plotly/versions/0.0.2/requires
- Plotly/versions/0.0.3/requires
- Plotly/versions/0.1.0/requires
- PlotlyJS/versions/0.1.0/requires
- PlotlyJS/versions/0.1.1/requires
- PlotlyJS/versions/0.1.2/requires
- PlotlyJS/versions/0.1.3/requires
- PlotlyJS/versions/0.1.4/requires
- PlotlyJS/versions/0.2.0/requires
- PlotlyJS/versions/0.3.0/requires
- Plotly does not require any particular version of JSON
- PlotlyJS versions before 0.3.0 require at most 0.5.1. Changes introduced in 0.5.2 and kept in 0.5.3 broke PlotlyJS.
- PlotlyJS versions 0.3.0 or later require at least 0.5.2. I set it to 0.5.3 to avoid downgrade/upgrade surprises, since 0.5.2 is the same as 0.6.
> Fix Plotly/PlotlyJS bounds

- CUDAdrv/url
- CUDAdrv/versions/0.1.0/requires
- CUDAdrv/versions/0.1.0/sha1
CUDA driver wrapper (split off of EOL'd CUDA.jl + CUDAnative.jl) for reuse in CUDArt.jl and CUDAnative.jl
> Register CUDAdrv

- Chemfiles/versions/0.6.0/requires
- Chemfiles/versions/0.6.0/sha1
I still have a build failure on win32-0.5.0 (https://ci.appveyor.com/project/Luthaf/chemfiles-jl/build/53), which is due to https://github.com/JuliaLang/WinRPM.jl/issues/76. I am nevertheless in favour of merging this, 0.5.0 is a nightly version.
> Tag Chemfiles v0.6.0

- Git/url
- Git/versions/0.1.0/requires
- Git/versions/0.1.0/sha1
https://github.com/JuliaPackaging/Git.jl (still needs moar docs)
ref https://github.com/JuliaLang/julia/pull/17294, this is the `Git` module that was formerly part of Base but is no longer used by the package manager on 0.5 so is being removed
> Register Git.jl

- StatsFuns/versions/0.3.0/requires
Everything in JuliaStats is on fire and broken because of StatsFuns 0.3.0, so might be best to do this until we can get things sorted out. As suggested by @tkelman.
> Make StatsFuns 0.3.0 require Julia 0.5- temporarily

- StatsFuns/versions/0.3.0/requires
Reverts JuliaLang/METADATA.jl#5624
once we do https://github.com/JuliaLang/METADATA.jl/pull/5613 then this should be safe again. @ararslan or @andreasnoack correct me if I'm wrong.
> Revert "Make StatsFuns 0.3.0 require Julia 0.5- temporarily"

- Spectra/versions/0.0.2/requires
- Spectra/versions/0.1.0/requires
- Spectra/versions/0.1.1/requires
ref https://github.com/charlesll/Spectra.jl/pull/2, cc @charlesll
This recently caused a failure on PackageEvaluator. Now I'm not sure why PackageEvaluator was using an older version of JuMP here, still digging into that.
> Add minimum JuMP 0.13 bounds to recent Spectra.jl tags

- PATHSolver/versions/0.0.1/requires
- PATHSolver/versions/0.0.2/requires
- PATHSolver/versions/0.0.3/requires
- PATHSolver/versions/0.0.4/requires
- PATHSolver/versions/0.0.5/requires
- VariationalInequality/versions/0.0.1/requires
- VariationalInequality/versions/0.0.2/requires
- VariationalInequality/versions/0.0.3/requires
on existing tags since it tries to use single-argument `jacobian(f)`, ref https://github.com/chkwon/PATHSolver.jl/blob/f0958e51cf75eefa385b549f9a1f16080bf5b3f1/src/PATHSolver.jl#L18 and https://travis-ci.org/tkelman/PATHSolver.jl/jobs/146865420
cc @chkwon @jrevels
> Bound PATHSolver's ForwardDiff dependency to max 0.2

- TikzPictures/versions/0.3.3/requires
- TikzPictures/versions/0.3.3/sha1
Makes TikzPictures compatible with TexLive 2016 while maintaining compatibility with earlier versions.
> Tag TikzPictures v0.3.3

- .test/METADATA.jl
- .test/travis.sh
- .travis.yml
- BayesNets/versions/0.0.1/requires
- BayesNets/versions/0.0.10/requires
- BayesNets/versions/0.0.2/requires
- BayesNets/versions/0.0.3/requires
- BayesNets/versions/0.0.4/requires
- BayesNets/versions/0.0.5/requires
- BayesNets/versions/0.0.6/requires
- BayesNets/versions/0.0.7/requires
- BayesNets/versions/0.0.8/requires
- BayesNets/versions/0.0.9/requires
- BayesNets/versions/0.1.0/requires
otherwise packages that are 0.5-only do not get verified
I suspect this will fail because #5453 put METADATA in an invalid state on nightly. @Keno please use PkgDev.publish so your metadata changes get verified locally.
> Run Travis test on 0.4 and 0.5, add Julia upper bounds on some old BayesNets tags

- ArgParse/versions/0.3.1/requires
Thanks to @abhijithch for pointing this out (see https://github.com/carlobaldassi/ArgParse.jl/pull/32).
> Update ArgParse's 0.3.1 Compat requirement

- EndpointRanges/versions/0.0.1/requires
it uses `indices1`, cc @timholy
> EndpointRanges does not actually work on 0.4

- Celeste/versions/0.1.0/requires
fixes GradientNumber not defined
> add ForwardDiff 0.2 upper bound to Celeste.jl 0.1.0 tag

- DocStringExtensions/url
- DocStringExtensions/versions/0.1.0/requires
- DocStringExtensions/versions/0.1.0/sha1
The package provides a number of extensions to the base docsystem. The [docs](https://juliadocs.github.io/DocStringExtensions.jl/latest/) provide an overview of what the package currently includes, with more features to come in future releases.
> Register DocStringExtensions

- GitHub/versions/2.1.0/requires
- GitHub/versions/2.1.0/sha1
This could break packages that rely on GitHub.jl's old pagination behavior. A description of the new behavior can be found [here](https://github.com/JuliaWeb/GitHub.jl/tree/master#pagination).
> Tag GitHub v2.1.0 [https://github.com/JuliaWeb/GitHub.jl]

- DataFrames/versions/0.7.8/requires
- DataFrames/versions/0.7.8/sha1
Tagging a commit from before contrast coding was introduced, which seems to have caused failures in other packages.
> Tag DataFrames 0.7.8

- Cuba/versions/0.1.2/requires
- Cuba/versions/0.1.2/sha1
From `NEWS.md` file:
> ### New Features ###
> 
> * Windows (`i686` and `x86_64` architectures) supported
>   ([#2](https://github.com/giordano/Cuba.jl/issues/2))
> Tag Cuba v0.1.2

- NormalizeQuantiles/versions/0.2.0/requires
- NormalizeQuantiles/versions/0.2.0/sha1
For function sampleRanks removed methods with optional parameters in favor of methods with keyword parameters
This change has been motivated because of warnings in julia 0.5 and 0.6 with
`using NormalizeQuantiles`
`WARNING: Method definition sampleRanks(Array{Int64, N<:Any}) in module NormalizeQuantiles at c:\Program Files\Julia-0.4.1\packages\v0.5\NormalizeQuantiles\src\NormalizeQuantiles.jl:382 overwritten at c:\Progr.....`
This is a sample code which shows the problem:
```
function test(a,b=1,c=1)
a+b+c
end
function test(a;b=1,c=1)
a+b+c
end
```
The reasoning of the warnings is clear, but:
1. it would be better to suppress the warnings when the functions are imported from a package because the package user should not be irritated,
or
2. if the keyword parameter version implicitly …
> Tag NormalizeQuantiles v0.2.0

- RobotOS/url
I just renamed my github account and if I'm not mistaken, this is the only change needed to keep the package info up to date.
> Move RobotOS package url to renamed github id

- KernelDensity/versions/0.2.0/requires
- KernelDensity/versions/0.2.0/sha1
Fixes https://github.com/JuliaStats/KernelDensity.jl/issues/30.
I'm tagging this as a minor release since all plotting code has been removed. However, this should be fairly low-impact for other packages. Currently the only registered packages that depend on KernelDensity are plotting packages (StatPlots, Vega, and Gadfly).
> Tag KernelDensity v0.2.0

- Interpolations/versions/0.3.6/requires
- Interpolations/versions/0.3.6/sha1
This is a patch release to make Interpolations.jl compatible with Julia 0.5.
No breaking changes for 0.4.x have been noted (all tests pass).
> Tag Interpolations v0.3.6

- .test/METADATA.jl
- Polynomials/versions/0.0.6/requires
since it uses `__precompile__` without checking for it first
ref https://github.com/JuliaLang/METADATA.jl/pull/5969#discussion_r74868810, cc @jverzani
> Make Polynomials 0.0.6 tag 0.4-only

- CoordinateTransformations/versions/0.2.0/requires
Rotations 0.3 has a different API to Rotations 0.1/0.2, and this version of CoordinateTransformations requires one of the latter.
> Update requirements to reflect changes to dependency

- ValueHistories/versions/0.1.0/requires
- ValueHistories/versions/0.1.0/sha1
Thanks to @tbreloff 
- drops 0.4 support
- new convenience macro
- shorter type names
> Tag ValueHistories v0.1.0

- CoverageBase/url
Package moved to JuliaCI, see https://github.com/JuliaCI/CoverageBase.jl/issues/17.
> Change url for CoverageBase

- HTTPClient/versions/0.2.1/requires
- HTTPClient/versions/0.2.1/sha1
WinRPM depends on this, so I thought I'd fix it.
> Tag HTTPClient v0.2.1

- FixedEffectModels/versions/0.0.1/requires
- FixedEffectModels/versions/0.0.2/requires
- FixedEffectModels/versions/0.0.3/requires
- FixedEffectModels/versions/0.1.0/requires
- FixedEffectModels/versions/0.1.1/requires
- FixedEffectModels/versions/0.2.0/requires
- FixedEffectModels/versions/0.2.1/requires
- FixedEffectModels/versions/0.2.2/requires
- FixedEffectModels/versions/0.3.0/requires
DataFrames 0.8.0 will introduce breaking changes to FixedEffectModels, so this PR specifies 0.8.0 as an upper bound on the DataFrames dependency for all tagged versions of FixedEffectModels.
As requested by @tkelman in #6238.
> Add DataFrames 0.8.0 as a FixedEffectModels upper bound

- DataFrames/versions/0.8.1/requires
- DataFrames/versions/0.8.1/sha1
Accompanies #5909. It fixes some of the stuff that 0.8.0 will break.
cc @tkelman, who IIRC said we should merge these around the same time.
> Tag DataFrames v0.8.1

- DataFrames/versions/0.8.0/requires
DataFrames 0.8.0 uses `Compat.view` but the lower bound on its Compat dependency is 0.8. It needs to be at least 0.8.4, when `view` was added to Compat.
> Bump Compat dependency for DataFrames 0.8.0 to 0.8.4

- IJulia/versions/1.3.0/requires
- IJulia/versions/1.3.0/sha1
I just realized that I hadn't tagged a new version in a while.
This version fixes a serious problem (JuliaLang/IJulia.jl#421), implements help if the user tries an IPython "magic", defaults to the user's home directory in `notebook()` and adds a keyword to change it.
Closes JuliaLang/IJulia.jl#460
> Tag IJulia v1.3.0

- Measurements/versions/0.2.1/requires
- Measurements/versions/0.2.1/sha1
From `NEWS.md` files:
> ### New Features ###
> 
> * New mathematical operations supported: `log2`, `abs2`, `fma`, `muladd`,
>   `besseli`, `besselix`, `besselk`, `besselkx`, `widen`, `big`.
Note that nightly build are currently failing on all systems (see for example https://travis-ci.org/giordano/Measurements.jl/jobs/159059165)
> Tag Measurements v0.2.1

- LibSndFile/versions/0.4.0/requires
- LibSndFile/versions/0.4.0/sha1
- PortAudio/versions/0.4.0/requires
- PortAudio/versions/0.4.0/sha1
This brings both packages in line with the new API in SampledSignals 0.2.0
https://github.com/JuliaAudio/PortAudio.jl
https://github.com/JuliaAudio/LibSndFile.jl
> Tags PortAudio v0.4.0 and LibSndFile v0.4.0

- DynamoDB/versions/0.0.1/requires
started failing when AWS 0.2 was tagged http://pkg.julialang.org/detail/DynamoDB.html
> DynamoDB 0.0.1 has upper bound on AWS 0.2

- CSV/versions/0.0.5/requires
- Metamath/versions/0.0.1/requires
and tighten CSV.jl 0.0.5's upper bound on DataStreams, ref https://github.com/getzdan/Metamath.jl/pull/1 and http://pkg.julialang.org/detail/Metamath.html
cc @getzdan and @quinnj
> Add upper bound on CSV.jl to Metamath.jl 0.0.1

- FixedEffectModels/versions/0.0.1/requires
- FixedEffectModels/versions/0.0.2/requires
- FixedEffectModels/versions/0.0.3/requires
- FixedEffectModels/versions/0.1.0/requires
- FixedEffectModels/versions/0.1.1/requires
- FixedEffectModels/versions/0.2.0/requires
- FixedEffectModels/versions/0.2.1/requires
- FixedEffectModels/versions/0.2.2/requires
0.7.8 didn't fix the issue with reducing over an empty collection
and FixedEffectModels 0.3.0 is Julia-0.5-only
ref http://pkg.julialang.org/detail/FixedEffectModels.html
#6244 wasn't tight enough, cc @matthieugomez @ararslan and ref https://github.com/JuliaStats/DataFrames.jl/pull/1017#issuecomment-243803777
If one of the more recent DataFrames tags has fixed the issue, then we can instead loosen or remove the upper bounds, let me know.
> Tighten FixedEffectModels bound on DataFrames further

- Formatting/versions/0.2.0/requires
- Formatting/versions/0.2.0/sha1
Minor tag because v0.3 support was dropped 
cc: @ViralBShah
> Tag Formatting v0.2.0

- GeneralizedSampling/versions/0.0.4/requires
ref https://github.com/JuliaLang/METADATA.jl/pull/6355
cc @robertdj - if you later tag a version of GeneralizedSampling that works with the latest NFFT, then this won't be noticeable.
> add an upper bound on GeneralizedSampling's dependency on NFFT

- LibExpat/versions/0.2.1/requires
- LibExpat/versions/0.2.1/sha1
Fixes a depwarn when doing `Pkg.build` of WinRPM.
> Tag LibExpat v0.2.1 [https://github.com/amitmurthy/LibExpat.jl]

- .test/METADATA.jl
- .test/check-pr.jl
- .test/travis.sh
When someone submits a pull request on METADATA, this addition to the CI tests will ensure that, for each modified package,
1. All local tags are present on the remote,
2. If so, that the commit SHAs match between the local and remote tags, and
3. ~~If more than one tag is available for a package, that multiple tags don't share a commit SHA.~~
Items 1 and 2 produce errors, ~~3 produces warnings.~~
I've also made the (unrelated) change of adding 0.6 to the testing list. This is a separate commit so it can be removed if necessary.
cc @tkelman
> Test the sanity of package tags when running Travis on a PR

- .test/check-pr.jl
Should fix https://github.com/JuliaLang/METADATA.jl/pull/6504#issuecomment-249460877
The problem was that `notpushed` is a `Vector{Pair}`, and we're trying to compare it to a `Vector{VersionNumber}`.
> Fix issue with identification of unpushed tags

- .test/travis.sh
this isn't using `language: julia` so https://github.com/travis-ci/travis-build/pull/841 won't do it
> add specific user agent for identifying downloads that come from here

- .test/METADATA.jl
- .test/check-pr.jl
There are a number of simplifications and corrections to the tag checking code:
* No more dependency on JSON.jl
* No more use of the GitHub API (which means no more quotas and rate limits)
* Get both annotated and lightweight tags when fetching remote tags
* Correctly identify when a tag hasn't been pushed to the remote
In simulations it's shown to exhibit the desired behavior in all of the circumstances I could think of. I think it runs a little faster too now. Maybe.
~~I also made the unrelated change of having the Bash script print the Julia version it's running. It's helpful for debugging when looking at the Travis log to have that be obvious.~~
cc @tkelman
> Simplify and (hopefully!) fix tag checking for PRs

- .test/check-pr.jl
Addresses the issue noted in https://github.com/JuliaLang/METADATA.jl/pull/6534#issuecomment-249944670.
The `first` was erroneously left over from a previous approach, wherein the variable `sha` was an array, and we wanted the first element. Now it's a string, so using `first` gets the first character of the string, which definitely isn't right.
Sorry @tkelman and @timholy!
> Fix issue with the SHA being interpreted as a Char

- .test/check-pr.jl
Makes the error message a little more helpful.
> Advise users to restart their builds after pushing tags

- .test/check-pr.jl
Currently when all tags have been pushed to the upstream package repository, we check that the SHA for _every_ tag matches between what's in METADATA and what's in the upstream repo. With this change, we'll only be checking whether the SHA matches for versions that were modified in the PR.
This also includes a fix that will ignore tags in the upstream repo with names that aren't valid version numbers. It's fine to have those upstream, just not in METADATA. Attempting to create a version in METADATA with an invalid version number will still fail.
> Only check SHA matches for modified package versions

- ProtoBuf/versions/0.3.0/requires
- ProtoBuf/versions/0.3.0/sha1
- make google wellknown types a submodule
- remove Julia 0.3 support, update CI and coverage
> Tag ProtoBuf v0.3.0 [https://github.com/tanmaykm/ProtoBuf.jl]

- StatsBase/versions/0.11.0/requires
- StatsBase/versions/0.11.0/sha1
Minor version since it deprecates a few things.
> Tag StatsBase v0.11.0

- .test/check-pr.jl
This should address the issue noted in #6636.
> Ignore upstream tags that don't start with v

- FixedPointNumbers/versions/0.2.0/requires
- FixedPointNumbers/versions/0.2.0/sha1
Main changes:
- implement `isapprox`
- be more consistent about choice of `Float32` or `Float64` when converting to `AbstractFloat`
The latter has a chance of being breaking for operations that really care about the specific element type. Not sure whether this should be a minor version bump as a consequence (it's a pretty tiny change, really).
> Tag FixedPointNumbers v0.2.0

- SampledSignals/versions/0.3.0/requires
- SampledSignals/versions/0.3.0/sha1
Makes SIUnits stuff less general but easier to reason about and extend. Now we have separate `SampleBuf` and `SpectrumBuf` types for time-domain and frequency-domain signals.
> Tag SampledSignals v0.3.0 [https://github.com/JuliaAudio/SampledSignals.jl]

- CUSPARSE/versions/0.5.0/requires
- CUSPARSE/versions/0.5.0/sha1
- Now supports Windows
- Uses `Base.Test` `@testset`s
- Tests pass on Windows and Linux
> Tag CUSPARSE v0.5.0 [https://github.com/JuliaGPU/CUSPARSE.jl]

- .test/travis.sh
- ArrayViews/url
- Compose/url
- Gadfly/url
- Gettext/url
- JavaCall/url
- MathLink/url
- Mathematica/url
- ObjectiveC/url
- RCall/url
- TestImages/url
I think the `git fetch origin +refs/pull/####/merge:` is sometimes getting stale data,
causing some builds to pass when they shouldn't
continuing from #6711 but this time opened from a fork to see if that behaves any differently
> add some more debugging output to the travis script

- MLBase/versions/0.6.0/requires
- MLBase/versions/0.6.0/sha1
Fixes 0.5 compatibility issues.
> Tag MLBase v0.6.0 [https://github.com/JuliaStats/MLBase.jl]

- Cuba/versions/0.2.0/requires
- Cuba/versions/0.2.0/sha1
From the `NEWS.md` file:
> This release faces some changes to the user interface.  Be aware of them when
> upgrading.
> 
> ### New Features ###
> 
> * `ndim` and `ncomp` arguments can be omitted.  In that case they default to 1.
>   This change is not breaking, old syntax will continue to work.
> 
> ### Breaking Changes ###
> 
> All integrator functions and some optional keywords have been renamed for more
> consistency with the Julia environment.  Here is the detailed list:
> 
> * Integrators functions have been renamed to lowercase name: `Vegas` to `vegas`,
>   `Suave` to `suave`, `Divonne` to `divonne`, `Cuhre` to `cuhre`.  The uppercase
>   variants are still available but deprecated, they will be removed at some
>   point in the future.
> * Optional keywords changes: `epsabs` to …
> Tag Cuba v0.2.0

- WriteVTK/versions/0.4.2/requires
- WriteVTK/versions/0.4.2/sha1
Do-block syntax is now supported for generation of VTK files.
> Tag WriteVTK v0.4.2 [https://github.com/jipolanco/WriteVTK.jl]

- XMLconvert/versions/0.1.0/requires
- XMLconvert/versions/0.1.0/sha1
Drop support for Julia 0.4
@paulstey -- this is the new issue to track
> Tag XMLconvert v0.1.0 [https://github.com/bcbi/XMLconvert.jl]

- RigidBodyDynamics/url
- RigidBodyDynamics/versions/0.0.1/requires
- RigidBodyDynamics/versions/0.0.1/sha1
`RigidBodyDynamics` is a basic rigid body dynamics package implemented completely in Julia. See https://github.com/tkoolen/RigidBodyDynamics.jl/blob/master/examples/Mechanism.ipynb for some usage examples.
> Register RigidBodyDynamics 0.0.1

- CRlibm/versions/0.3.0/requires
- CRlibm/versions/0.3.0/sha1
0.5 deprecations, and include the source code of the `CRlibm` library in the repository rather than downloading it.
> Tag CRlibm v0.3.0 [https://github.com/dpsanders/CRlibm.jl]

- NamedArrays/versions/0.5.3/requires
- NamedArrays/versions/0.5.3/sha1
A number of bugfixes and PRs: more efficient use of julia-0.5 possibilities (`Vararg`)
It turned out that all the `@compat`s were for julia-0.3, so the whole Compat requirement could be relaxed.
> Tag NamedArrays v0.5.3 [https://github.com/davidavdav/NamedArrays.jl]

- DiffEqSensitivity/url
- DiffEqSensitivity/versions/0.0.1/requires
- DiffEqSensitivity/versions/0.0.1/sha1
DiffEqSensitivity.jl is a component of the DiffEq ecosystem which performs sensitivity analysis on differential equations. Currently this only has the functionality for local sensitivity analysis on ODEs (which is probably the most well-known case), but the planned functionality includes expanding to SDEs and global sensitivities which is why it's separated from the OrdinaryDiffEq.
[Note: Just a heads up, there are 3 other component packages to be registered. DiffEqBifurcate is watiing on PyDSTool.jl + PyCall patches to fix segfaults. DiffEqUncertainty for uncertainty quantification and DiffEqOptimalControl for optimal control are in their earlier stages and will not be registered for quite awhile. So things should start to stabilize. Thanks for your patience during this large change!]
> Register DiffEqSensitivity.jl

- Mimi/versions/0.2.1/requires
- Mimi/versions/0.2.1/sha1
This should fix the current package test failures.
> Tag Mimi v0.2.1 [https://github.com/anthofflab/Mimi.jl]

- ParameterizedFunctions/versions/0.3.2/requires
- ParameterizedFunctions/versions/0.3.2/sha1
This patch updates the use of the environment variables for safer SymEngine build failures so that way the user's environment is not changed by `using ParameterizedFunctions`. @tkelman
> Tag ParameterizedFunctions v0.3.2 [https://github.com/JuliaDiffEq/ParameterizedFunctions.jl]

- DifferentialEquations/versions/1.1.0/requires
- DifferentialEquations/versions/1.1.0/sha1
This updates DifferentialEquations.jl to include ParameterizedFunctions.jl due to the change https://github.com/JuliaLang/METADATA.jl/pull/7037. It also adds minimum version requirements to the constituant packages.
> Tag DifferentialEquations v1.1.0 [https://github.com/JuliaDiffEq/DifferentialEquations.jl]

- ApproxFun/versions/0.4.0/requires
- ApproxFun/versions/0.4.0/sha1
- SingularIntegralEquations/versions/0.1.4/requires
- SingularIntegralEquations/versions/0.1.5/requires
This is a major update to ApproxFun, in particular, revamps how PDE solving is done so that it is more efficient for variable coefficients.
It also adds upper bounds to the requires for SingularIntegralEquations (with a new tag forthcoming there as well).
> Tag ApproxFun 0.4

- Sundials/versions/0.4.0/requires
- Sundials/versions/0.4.0/sha1
This tag updates the Sundials extra APIs to include the DiffEq common interface. The `cvode_fulloutput` function, created for the "1st-edition" of  the common interface, has been deprecated for the function `solve(prob,alg;kwargs)` to match the rest of the packages in the ecosystem. A requirement on DiffEqBase has been added accordingly (for now, no minimum version, but will add the minimum version in a patch which may be coming)
> Tag Sundials v0.4.0 [https://github.com/JuliaDiffEq/Sundials.jl]

- SwitchTimeOpt/url
Repository transferred to OxfordControl organization.
> Changed URL for SwitchTimeOpt.jl repository

- ODEInterfaceDiffEq/url
- ODEInterfaceDiffEq/versions/0.0.1/requires
- ODEInterfaceDiffEq/versions/0.0.1/sha1
ODEInterfaceDiffEq.jl is a glue package for ODEInterface with gives it JuliaDiffEq common interface bindings and all of the advantages that come with it. This code was previously included in OrdinaryDiffEq.jl and was the code which required conditional dependencies, but using this common API, conditional dependencies are no longer required. This does need to be registered as it is at least a crucial part of the OrdinaryDiffEq.jl tests (for testing native Julia versions vs the FORTRAN wrapper package), and the `radau` methods have no parallel in Julia as of right now, making them a strong contribution to the common interface.
It wasn't included in ODEInterface.jl directly because of the dependencies it adds, and so it keeps ODEInterface.jl a dependency-free library. For more discussion on …
> Register ODEInterfaceDiffEq.jl

- WAV/versions/0.8.3/requires
- WAV/versions/0.8.3/sha1
v0.8.3 is the same as v0.8.2, but it requires the correct version of Compat (0.9.5). These two minor versions add support for Julia v0.6.
> Tag WAV v0.8.3 [https://github.com/dancasimiro/WAV.jl]

- Playground/versions/0.2.0/requires
- Playground/versions/0.2.0/sha1
I realize it has taken me a while to update Playground to 0.5, but I was hoping a couple of my dependencies would get updated. I've updated the minor version number as I've dropped support for DeclarativePackages.
> Tag Playground v0.2.0 [https://github.com/Rory-Finnegan/Playground.jl]

- ParameterizedFunctions/versions/0.0.1/requires
- ParameterizedFunctions/versions/0.1.0/requires
- ParameterizedFunctions/versions/0.1.1/requires
- ParameterizedFunctions/versions/0.2.0/requires
- ParameterizedFunctions/versions/0.2.1/requires
- ParameterizedFunctions/versions/0.2.2/requires
- ParameterizedFunctions/versions/0.3.0/requires
- ParameterizedFunctions/versions/0.3.1/requires
- ParameterizedFunctions/versions/0.3.2/requires
- ParameterizedFunctions/versions/0.3.3/requires
- ParameterizedFunctions/versions/0.4.0/requires
- ParameterizedFunctions/versions/0.4.1/requires
- ParameterizedFunctions/versions/0.4.2/requires
- ParameterizedFunctions/versions/0.5.0/requires
This is to make sure DiffEqBase v0.5 won't be enabled until the ParameterizedFunction update.
Is this right? @tkelman
> Add a bunch of maximum versions to ParameterizedFunctions

- DiffEqDevTools/versions/0.0.1/requires
- DiffEqDevTools/versions/0.0.2/requires
- DiffEqDevTools/versions/0.1.0/requires
- DiffEqDevTools/versions/0.1.1/requires
- DiffEqDevTools/versions/0.2.0/requires
- DiffEqDevTools/versions/0.2.1/requires
- DiffEqDevTools/versions/0.3.0/requires
- DiffEqDevTools/versions/0.4.0/requires
- DiffEqDevTools/versions/0.5.0/requires
This is preparing for the DiffEqBase  tag.  A change in the tableau representation will cause breakage.
> max versions on DiffEqDevTools

- Cliffords/versions/0.2.0/requires
- Cliffords/versions/0.2.1/requires
- Cliffords/versions/0.2.2/requires
- Cliffords/versions/0.2.3/requires
- Cliffords/versions/0.3.0/requires
- CoordinateTransformations/versions/0.2.0/requires
- Geodesy/versions/0.1.0/requires
- Geodesy/versions/0.2.0/requires
Compat 0.11 introduces the ∘ operator from Base. Out of caution, we should ensure that packages that depend on Compat are not broken by this change.
cc @marcusps @blakejohnson 
Since your package no longer depends on Compat, you don't need to take any action. It also looks like you have already fixed the ∘ operator.
cc @c42f @andyferris 
Your package also no longer depends on Compat so there is no rush to tag a new version. But if the package will depend on Compat in the future again, it should probably avoid defining the ∘ operator locally if possible. I don't think it will break this package, but...
Geodesy imports ∘ from CoordinateTransforms, so if it also uses Compat, then there will likely be an error due to importing the same name from multiple packages. Geodesy also does not …
> Upper bound Compat on packages at risk of breaking with 0.11

- MathProgBase/versions/0.5.9/requires
- MathProgBase/versions/0.5.9/sha1
Tagging a release before dropping support for 0.4.
> Tag MathProgBase v0.5.9 [https://github.com/JuliaOpt/MathProgBase.jl]

- MathProgBase/versions/0.5.10/requires
- MathProgBase/versions/0.5.10/sha1
Backports a fix (https://github.com/JuliaOpt/MathProgBase.jl/commit/ed759de5e946e6221522131cbc6ae1b06ffa24a3) which affects rotated second order cone solvers.
> Tag MathProgBase v0.5.10 [https://github.com/JuliaOpt/MathProgBase.jl]

- Tau/url
release hashes remain the the same.
> Tau.jl: update repo URL after move to JuliaMath

- COBRA/versions/0.0.5/requires
- COBRA/versions/0.0.5/sha1
[![Build Status](https://travis-ci.org/opencobra/COBRA.jl.svg?branch=master)](https://travis-ci.org/opencobra/COBRA.jl)
**Detailed List of Changes**
*Source*
- Addition of `convertUnitRange()` to write a `UnitRange` type to a `.mat` (requirement from `MAT.jl`)
- Writing `rxnsList` and `rxnsOptMode` from each worker to the respective `.mat` file
- Minor changes to documentation
*Tested on `Linux`, `Windows`, and `macOS` on Julia `0.5`. CI integrated version.*
> Tag COBRA v0.0.5 [https://github.com/opencobra/COBRA.jl]

- DiffEqPDEBase/url
- IterationManagers/url
- PlotlyJS/url
@sglyon changed his username, and one of @ChrisRackauckas' packages was moved to an org. Be sure to re-enable your CI after doing this kind of thing.
> Update urls for 3 moved packages

- FixedPointNumbers/versions/0.3.0/requires
to avoid introducing deprecations on Julia 0.4 where many packages
are no longer introducing new updates
cc @timholy 
corresponding package PR at https://github.com/JuliaMath/FixedPointNumbers.jl/pull/65
> Make FixedPointNumbers 0.3.0 require Julia 0.5

- StochasticDiffEq/versions/0.0.1/requires
- StochasticDiffEq/versions/0.0.2/requires
- StochasticDiffEq/versions/0.0.3/requires
- StochasticDiffEq/versions/0.0.4/requires
- StochasticDiffEq/versions/0.0.5/requires
- StochasticDiffEq/versions/0.1.0/requires
- StochasticDiffEq/versions/0.1.1/requires
- StochasticDiffEq/versions/0.2.0/requires
- StochasticDiffEq/versions/0.3.0/requires
- StochasticDiffEq/versions/0.4.0/requires
- StochasticDiffEq/versions/0.5.0/requires
There will be a tag in DiffEqBase and a corresponding update in StochasticDiffEq which changes the noise interface to allow for in-place RNGs. No previous version will be compatible with the defaults in the new version, so this will block the release until a compatible version of StochasticDiffEq.jl is available.
> Maximum versions on DiffEqBase for StochasticDiffEq

- Indicators/versions/0.1.4/requires
- Indicators/versions/0.1.4/sha1
Simple bugfix for associated with field names for the output of the `mama` function on `Temporal.TS` object.
Been a while since I've made any changes, so if I've missed anything feel free to let me know and I can jump on it :)
> Tag Indicators v0.1.4 [https://github.com/dysonance/Indicators.jl]

- Reel/versions/0.1.0/requires
Through a discussion on Gitter with fuzzybear3965, it came up that there is currently a dependency conflict between Reel 0.2.0+ and Images 0.6.0+. Pkg prefers to install Images 0.6.0 over Reel 0.2.1, and so keeps Reel back to 0.1.0. Unfortunately, the [Reel 0.1.0 source code](https://github.com/shashi/Reel.jl/blob/v0.1.0/src/Reel.jl#L16) will not even load on 0.5. Using the philosophy that if Reel is required, it is better to have a functional Reel 0.2.1 and Images 0.5.14 than a dysfunctional Reel 0.1.0 and Images 0.6.0, I think it is desirable to block installing Reel 0.1.0 on 0.5 entirely.
> Upper bound Julia version for Reel

- AmplNLWriter/versions/0.3.0/requires
- CPLEX/versions/0.2.0/requires
- Cbc/versions/0.3.0/requires
- Clp/versions/0.3.0/requires
- CoinOptServices/versions/0.1.2/requires
- ECOS/versions/0.7.0/requires
- GLPKMathProgInterface/versions/0.2.3/requires
- Gurobi/versions/0.3.0/requires
- Ipopt/versions/0.2.6/requires
- KNITRO/versions/0.2.0/requires
- Mosek/versions/0.6.1/requires
- NLopt/versions/0.3.3/requires
- SCS/versions/0.2.7/requires
- Xpress/versions/0.1.0/requires
MPB 0.6 is [coming soon](https://github.com/JuliaLang/METADATA.jl/pull/7838). We dropped support for Julia 0.4 and removed functionality for default solvers, so it warranted a new minor release. Nevertheless most solver interfaces will not be affected.
> prepare for MathProgBase 0.6 release

- Juno/versions/0.2.6/requires
LambdaInfo not defined
cc @andreasnoack ref https://github.com/JuliaLang/METADATA.jl/pull/7945#issuecomment-279883202
> upper bound Juno 0.2.6 to prevent its installation on Julia 0.6-dev

- JLD/versions/0.5.0/requires
- JLD/versions/0.5.1/requires
- JLD/versions/0.5.2/requires
- JLD/versions/0.5.3/requires
- JLD/versions/0.5.4/requires
- JLD/versions/0.5.5/requires
- JLD/versions/0.5.6/requires
- JLD/versions/0.5.7/requires
- JLD/versions/0.5.8/requires
- JLD/versions/0.5.9/requires
- JLD/versions/0.6.0/requires
- JLD/versions/0.6.1/requires
- JLD/versions/0.6.2/requires
these used Union(...) or UTF16String so do not load on 0.5
this should help with some of the current resolution failures people are seeing
> Add julia 0.5 upper bound on early JLD versions

- README.md
The link to the Julia's manual section about packages doesn't work with the trailing slash. I tried in both Firefox and MS Edge and had the same issue. Removing the trailing slash fixed the problem in both.
> Fix link to manual in README

- Bio/versions/0.1.0/requires
- Bio/versions/0.2.0/requires
- Bio/versions/0.2.1/requires
- Bio/versions/0.2.2/requires
- Bio/versions/0.2.3/requires
- Bio/versions/0.3.0/requires
- Bio/versions/0.4.0/requires
- Bio/versions/0.4.1/requires
- Bio/versions/0.4.2/requires
- Bio/versions/0.4.3/requires
- Bio/versions/0.4.4/requires
- Bio/versions/0.4.5/requires
Retroactively fixes Bio require files to avoid issues Bio.Intervals has when using IntervalTrees v0.1.1. @tkelman
> Fixed Bio require files

- Convex/versions/0.4.0/requires
Until https://github.com/JuliaLang/METADATA.jl/pull/8080 goes through, this will let the latest releases of JuMP and Convex.jl coexist.
CC @madeleineudell
> Widen MathProgBase requirement on Convex.jl

- ConicNonlinearBridge/versions/0.0.1/requires
Prevents accidental downgrading due to MathProgBase 0.7
> Bounds on old version of ConicNonlinearBridge

- RationalFunctions/versions/0.0.4/requires
- RationalFunctions/versions/0.0.4/sha1
Tagging [v0.0.4](https://github.com/aytekinar/RationalFunctions.jl) with the following cosmetic changes:
> Tag RationalFunctions

- SingularIntegralEquations/versions/0.1.1/requires
- SingularIntegralEquations/versions/0.1.2/requires
- SingularIntegralEquations/versions/0.1.3/requires
- SingularIntegralEquations/versions/0.1.4/requires
- SingularIntegralEquations/versions/0.1.5/requires
- SingularIntegralEquations/versions/0.2.0/requires
- SingularIntegralEquations/versions/0.2.1/requires
cc @dlfivefifty @MikaelSlevinsky since ApproxFun 0.5 came out this has been failing due to an undeclared dependency http://pkg.julialang.org/detail/SingularIntegralEquations.html
> Fix missing dependency of SingularIntegralEquations on Plots

- KernelDensity/versions/0.0.1/requires
- KernelDensity/versions/0.0.2/requires
- KernelDensity/versions/0.1.1/requires
- KernelDensity/versions/0.1.2/requires
- KernelDensity/versions/0.2.0/requires
- KernelDensity/versions/0.3.0/requires
- KernelDensity/versions/0.3.1/requires
earliest versions don't even load on julia 0.4
> Add Optim 0.7 upper bound to KernelDensity

- RoME/versions/0.0.4/requires
- RoME/versions/0.0.4/sha1
Redo of #8153 , was missing Optim.jl requirement for testing.
[RoME.jl](https://github.com/dehann/RoME.jl)
v0.0.3 -> [v0.0.4](https://github.com/dehann/RoME.jl/releases/tag/v0.0.4)
[![Build Status](https://travis-ci.org/dehann/RoME.jl.svg?branch=master)](https://travis-ci.org/dehann/RoME.jl)
diff: [vs v0.0.3](https://github.com/dehann/RoME.jl/compare/0f105f4...6bb6b52d)
REQUIRE
```
julia 0.5
IncrementalInference 0.2.5
Graphs 0.7.1
TransformUtils 0.0.5
KernelDensityEstimate 0.2.3
Distributions
Colors
Gadfly
JLD
HDF5
Optim
```
> Tag RoME v0.0.4 [https://github.com/dehann/RoME.jl]

- RigidBodyTreeInspector/versions/0.0.1/requires
- RigidBodyTreeInspector/versions/0.1.0/requires
ref #8431, breaks due to 'TreeDataStructure not defined'
cc @rdeits @tkoolen
> add upper bounds on RigidBodyTreeInspector's dependency on RigidBodyDynamics

- DriftDiffusionPoissonSystems/versions/0.0.1/requires
EllipticFem 0.0.2 deleted the Mesh type, DriftDiffusionPoissonSystems v0.0.1 was using it
ref https://github.com/JuliaLang/METADATA.jl/pull/7985#issuecomment-280923138
cc @Stivanification @gerhardtulzer what this will mean is if you have DDPS installed on Julia 0.4, EllipticFEM will get downgraded to version 0.0.1 so DDPS can work correctly. You can avoid that by tagging a Julia-0.4-compatible version of DDPS that works with the latest versions of EllipticFEM (or avoids depending on it).
> Upper bound DriftDiffusionPoissonSystems v0.0.1 dependency on EllipticFEM

- Lint/versions/0.5.0/requires
- Lint/versions/0.5.0/sha1
- Ignore unused variables starting with `_`
- Remove two API deprecations dating from 2016 Summer
> Tag Lint v0.5.0 [https://github.com/tonyhffong/Lint.jl]

- ReverseDiffSparse/versions/0.7.2/requires
We should keep this dependency around until the next time JuMP gets a version bump that triggers precompilation, following discussion with @tkelman.
> preempt possible precompile bug

- NamedArrays/versions/0.6.0/requires
- NamedArrays/versions/0.6.0/sha1
New minor version because we're dropping support for Julia v0.4
> Tag NamedArrays v0.6.0 [https://github.com/davidavdav/NamedArrays.jl]

- .test/check-pr.jl
With this change:
```julia
julia> get_remote_tags("https://github.com/ararslan/Jackknife.jl.git")
Dict{VersionNumber,AbstractString} with 2 entries:
v"0.1.0" => "ef13817c52284adb704d122536769242a6eebfd1"
v"0.2.0" => "864fdce2c82c4f113bdf760da9e4dd19a6484589"
julia> get_remote_tags("https://github.com/ararslan/HopesAndDreams.jl.git")
remote: Repository not found.
fatal: repository 'https://github.com/ararslan/HopesAndDreams.jl.git/' not found
ERROR: The specified URL does not correspond to a valid Git repository
Stacktrace:
[1] get_remote_tags(::String) at ./REPL[6]:5
```
Ref https://github.com/JuliaLang/METADATA.jl/pull/8767#issuecomment-293369113 (cc @tkelman)
> Emit a better error message for misspecified repo URLs

- RecursiveArrayTools/url
- ResettableStacks/url
These two libraries were essentially helper libraries for JuliaDiffEq, and all of the work on them was spawned by JuliaDiffEq work. So for organizational and maitanance purposes, I migrated them to JuliaDiffEq.
> Fix URLs for migrations

- LanguageServer/versions/0.0.1/requires
cc @tkelman 
The only other package that used `_writejson`, from a GitHub search, is JSONStreams, which is unregistered.
> Bound JSON to 0.9.0 on LanguageServer

- OffsetArrays/url
https://github.com/JuliaArrays/OffsetArrays.jl
This needs confirmation from @timholy @alsam, because I noted that this wasn't a transfer per se, more of a "manual" fork, so the original repository is still at alsam/OffsetArrays.jl. (was this on purpose?) Anyway, this means that there is no automatic forwarding to the the new home at JuliaArrays, and the link in METADATA has to be replaced for the move to take effect
ref: https://github.com/alsam/OffsetArrays.jl/pull/26#issuecomment-294231805
> move OffsetArrays to JuliaArrays

- IntervalArithmetic/versions/0.9.0/requires
- ValidatedNumerics/versions/0.8.0/requires
ref https://github.com/JuliaLang/METADATA.jl/pull/8999#issuecomment-297960883
since prior versions of ValidatedNumerics did not depend on StaticArrays,
this could result in downgrading ValidatedNumerics to 0.7.0 in order to
upgrade StaticArrays to 0.5
that would be fixed by releasing a new StaticArrays-0.5-compatible version
cc @dpsanders
> Upper bound IntervalArithmetic and ValidatedNumerics' dependencies on StaticArrays to < 0.5

- .test/ci.sh
we can drop this when rc1 is uploaded
I suspect beta wouldn't work since it would fail the consistency check due to now-fixed resolver issues
> fix the ci script to temporarily use the last 0.6 commit before branching

- ConfParser/url
- FilePaths/url
- HexEdit/url
- Interfaces/url
- NMEA/url
- Pcap/url
- Playground/url
Update urls for @rofinn (formerly @Rory-Finnegan) and @furface (formerly @brandonkmiller)'s packages. Github redirects should handle these, but if you plan on keeping these new names permanently, best to have the urls be accurate.
> Update urls for moved packages

- .test/ci.sh
reverts a temporary workaround that was needed to deal with Pkg resolver problems
> use 0.6.0-rc1 on metadata travis

- SingularIntegralEquations/versions/0.2.0/requires
- SingularIntegralEquations/versions/0.2.1/requires
since ApproxFun 0.4.x has that julia upper bound
cc @dlfivefifty these go with https://github.com/JuliaLang/METADATA.jl/pull/7584
> Upper bound SingularIntegralEquations 0.2.0 and 0.2.1 to Julia < 0.6

- GeostatInversion/versions/0.1.0/requires
- GeostatInversion/versions/0.1.1/requires
- GeostatInversion/versions/0.1.2/requires
- GeostatInversion/versions/0.1.3/requires
- GeostatInversion/versions/0.1.4/requires
- GeostatInversion/versions/0.1.5/requires
- GeostatInversion/versions/0.2.0/requires
- RobustLeastSquares/versions/0.0.1/requires
ref https://github.com/JuliaLang/METADATA.jl/pull/9190#issuecomment-301363799
cc @lopezm94 @montyvesselinov @andyferris 
if this turns out to be fixable in an IterativeSolvers 0.3.1, we can revert this then. for now this will downgrade IterativeSolvers to 0.2.x if either of these other packages are installed.
> Upper bound IterativeSolvers to < 0.3 for GeostatInversion and RobustLeastSquares

- DoubleDouble/url
DoubleDouble moved to JuliaMath.
cc @simonbyrne
> Update DoubleDouble URL to JuliaMath org

- TikzPictures/versions/0.4.0/requires
- TikzPictures/versions/0.4.0/sha1
Diff vs v0.3.5: https://github.com/sisl/TikzPictures.jl/compare/baba140254ca5e1c8f3de50d938041a29f2ea6da...12648cbccf58ae7c33e9fcaf7089deeb1190614e
Adds a save as .tikz command.
> Tag TikzPictures v0.4.0 [https://github.com/sisl/TikzPictures.jl]

- Reduce/versions/0.0.2/requires
- Reduce/versions/0.0.2/sha1
Diff vs v0.0.1: https://github.com/chakravala/Reduce.jl/compare/a1f1d3a3ad81422582fff42a285c07aeb9f76988...fed2933c4800ac9f1c0be1af19f7f6655cbbbf9c
Added `build` support for Linux and Unix. The linux build works very well and quickly with precompiled binaries. The general unix build from source depends on what kind of build tools are present.
The OSX automated build may or may not be working yet, I don't have my own system to test it on:
https://travis-ci.org/chakravala/Reduce.jl/builds/234067763
https://travis-ci.org/chakravala/Reduce.jl/builds/234080918
Windows build is not yet supported
Also, fixed an `IJulia` display bug with LaTeX
Finally, the build directory has been changed to a relative directory.
> Tag Reduce v0.0.2

- FiniteElementDiffEq/versions/0.0.1/requires
- FiniteElementDiffEq/versions/0.0.2/requires
- FiniteElementDiffEq/versions/0.0.3/requires
- FiniteElementDiffEq/versions/0.0.4/requires
- FiniteElementDiffEq/versions/0.0.5/requires
- FiniteElementDiffEq/versions/0.1.0/requires
- FiniteElementDiffEq/versions/0.2.0/requires
- FiniteElementDiffEq/versions/0.2.1/requires
- FiniteElementDiffEq/versions/0.3.0/requires
- ReverseDiff/versions/0.0.1/requires
- ReverseDiff/versions/0.0.2/requires
- ReverseDiff/versions/0.0.3/requires
- ReverseDiff/versions/0.0.4/requires
- ReverseDiff/versions/0.1.0/requires
- ReverseDiff/versions/0.1.1/requires
- ReverseDiff/versions/0.1.2/requires
- StochasticDiffEq/versions/2.0.0/requires
- StochasticDiffEq/versions/2.0.1/requires
- StochasticDiffEq/versions/2.0.2/requires
- StochasticDiffEq/versions/2.0.3/requires
- StochasticDiffEq/versions/2.0.4/requires
- StochasticDiffEq/versions/2.1.0/requires
- StochasticDiffEq/versions/2.2.0/requires
- StochasticDiffEq/versions/2.2.1/requires
I've placed upper bounds on ForwardDiff for the packages [marked by JuliaCIBot](http://juliarun-ci.s3.amazonaws.com/3a284f317fad06108bbef2fd7e5475743ce4a6f0/ForwardDiff_reverse_dependency_tests.html) in #9407.
ref #9416 
cc @ChrisRackauckas
> upper bound ForwardDiff at 0.5.0 for downstream packages

- IterableTables/versions/0.0.1/requires
- IterableTables/versions/0.0.2/requires
- IterableTables/versions/0.1.0/requires
- Query/versions/0.4.0/requires
- Query/versions/0.4.1/requires
- Query/versions/0.5.0/requires
I mark all the versions that don't work with julia 0.6- as such.
I also upper bound NamedTuples so that we can phase in the next breaking change in NamedTuples.
> Add upper bounds on NamedTuples in Query and IterableTables

- Spectra/versions/0.3.3/requires
- Spectra/versions/0.3.3/sha1
A fix in the peakhw (renamed peakmeas) function + related doc update.
Diff vs v0.3.2: https://github.com/charlesll/Spectra.jl/compare/8194b1310093efd47502fed301c5b3e7a9410d7f...8b3ffeb8e123ff8fd367cd4f79cfd060fbdc909f
> Tag Spectra v0.3.3 [https://github.com/charlesll/Spectra.jl]

- Spectra/versions/0.3.4/requires
- Spectra/versions/0.3.4/sha1
- Drop FORTRAN compilation of GCVSPL.f: Import new gcvspline Python module; installation of gcvspline through pip in a build.jl script in deps.
- various tests added;
- various examples added;
- Support now seems OK for Julia 0.6;
Diff vs v0.3.3: https://github.com/charlesll/Spectra.jl/compare/8b3ffeb8e123ff8fd367cd4f79cfd060fbdc909f...d80b712b23fc20c7e8ff0cbf97de5d1b304ce6e1
> Tag Spectra v0.3.4 [https://github.com/charlesll/Spectra.jl]

- DynamicalBilliardsPlotting/versions/0.1.0/requires
(plotting moved back to core package under on-demand availability)
> Deprecate `DynamicalBilliardsPlotting`

- ROOT/url
* Changes the URL of ROOT.jl - ROOT.jl has moved to the JuliaHEP organization. 
* New release, Cxx.jl-based, ROOT-6 and Julia v0.6 compatible.
Both changes are in agreement with the original author, Joosep Pata (who's a co-owner of JuliaHEP).
> New URL and release of ROOT.jl

- CoordinateDescent/versions/0.0.1/requires
In #9707 with the version of ProximalBase 0.0.3 there are breaking changes.
> Upper bound on ProximalBase

- Query/versions/0.5.0/requires
This upper bound is unnecessary and just block things. I added it a while back ago after the original tag, but that was an error.
> Remove upper bound on a Query requirement

- EMIRT/url
this repo was private previously and the url was moved to PackageMirror
> change url for EMIRT.jl

- Atom/versions/0.6.0/requires
- Media/versions/0.3.0/requires
both of these use syntax that wouldn't work in early dev versions
@MikeInnes come on.
> Use 0.6.0-pre as julia lower bound for Atom 0.6.0 and Media 0.3.0

- CSVFiles/versions/0.0.1/requires
- ExcelFiles/versions/0.0.1/requires
- StatFiles/versions/0.0.1/requires
This finishes the registration of these packages. They don't work with an older version of ``FileIO``, but when we originally registered them, FileIO v0.4.0 was not yet tagged.
> Update minimum version of FileIO for CSVFiles, ExcelFiles, StatFiles

- RobotOS/versions/0.4.3/requires
- RobotOS/versions/0.4.3/sha1
Diff vs v0.4.2: https://github.com/jdlangs/RobotOS.jl/compare/3855cc762d8d4146791a3d2b48e74699b7abc045...f601da6a2cc0ebd28ba981d0c487628e2fa7fd86
> Tag RobotOS v0.4.3 [https://github.com/jdlangs/RobotOS.jl]

- GenericSVD/url
The repository was moved to JuliaMath. This needs to be updated to trigger AttoBot.
> Update URL after move GenericSVD

- SimJulia/versions/0.4.0/requires
- SimJulia/versions/0.4.0/sha1
Release SimJulia v0.4.0 for compatibility with Julia v0.6:
- complete rewrite: more Julian less pythonic
- discrete event framework is on par with SimJulia v0.3.14
- continuous event framework is partially implemented
Diff vs v0.3.14: https://github.com/BenLauwens/SimJulia.jl/compare/d0e2abe932d0adfb96fdaddb4ff7cf82301ec02b...ee859c7efb148e1c90c43e3bd6a7f1fe7ab5075a
> Tag SimJulia v0.4.0 [https://github.com/BenLauwens/SimJulia.jl]

- JavaCall/versions/0.5.0/requires
Retroactively change the supported Julia version for JavaCall. 
JavaCall 0.5.0 was tagged stating support for julia 0.4. However, that is incorrect, it should have had julia 0.5 as the minimum supported version.  This PR makes that change in the existing tag. After this, JavaCall 0.4.4 should be the maximum supported version in Julia 0.4
Tony, is this acceptable?
> JavaCall v0.5.0 does not support julia v0.4

- SparseGrids/versions/0.2.0/requires
- SparseGrids/versions/0.2.0/sha1
Diff vs v0.1.1: https://github.com/robertdj/SparseGrids.jl/compare/4d82e68efda00cd5ad681260e9b702083fdd1b18...cdbae3d2f1ed76165deb1a9efb5912355ddcb486
> Tag SparseGrids v0.2.0 [https://github.com/robertdj/SparseGrids.jl]

- ImageProjectiveGeometry/versions/0.1.0/requires
- ImageProjectiveGeometry/versions/0.1.1/requires
- ImageProjectiveGeometry/versions/0.1.2/requires
gaussian2d was deprecated and now removed, cc @peterkovesi 
ref https://github.com/JuliaLang/METADATA.jl/pull/10251#issuecomment-315360576
> Upper bound ImageProjectiveGeometry's Images dependency to 0.11

- ParticleFilters/versions/0.0.1/requires
- ParticleFilters/versions/0.0.2/requires
- ParticleFilters/versions/0.0.3/requires
ParticleFilter now requires a version of POMDPs.jl < 0.6
> ParticleFilters requires POMDPs below 0.6

- HCubature/url
- HCubature/versions/1.0.0/requires
- HCubature/versions/1.0.0/sha1
This package provides a pure-Julia alternative to the Cubature.jl and Cuba.jl packages (both of which rely on C libraries, and e.g. are not type-generic), complementing the pure-Julia QuadGK.jl (1d integrals).
(Closes stevengj/HCubature.jl#1)
cc @ararslan
> new package: HCubature

- ODEInterface/versions/0.4.0/requires
- ODEInterface/versions/0.4.0/sha1
Attempt: 
Splitting ODEInterface in two (later perhaps more) different branches, depending on the julia version:
Here is an explanation of the version number idea/attempt:
https://github.com/luchr/ODEInterface.jl/blob/master/VERSIONS.md
I've read [tkelman's comment for Pull-Request 10415](https://github.com/JuliaLang/METADATA.jl/pull/10415#issuecomment-318437015) several times, and I think all the requirements and suggestions are satisfied [OK, except attobot]:
>  And if you drop support for a specific minor version of Julia, that's considered a form of breaking change even if the package code doesn't actually change significantly, so worth a new package minor version.
OK. This is case for the above scheme (after `v0.1.a` support for julia v0.4 is dropped and the new version (in time) is …
> Tag ODEInterface v0.4.0 [https://github.com/luchr/ODEInterface.jl]

- OrdinaryDiffEq/versions/2.10.0/requires
- OrdinaryDiffEq/versions/2.11.0/requires
- OrdinaryDiffEq/versions/2.11.1/requires
- OrdinaryDiffEq/versions/2.11.2/requires
- OrdinaryDiffEq/versions/2.11.3/requires
- StochasticDiffEq/versions/2.8.0/requires
- StochasticDiffEq/versions/2.9.0/requires
- StochasticDiffEq/versions/2.9.1/requires
`@muladd` will be removed from DiffEqBase.jl into its own package MuladdMacro.jl and so this places version bounds for that transition.
> add version bounds to *diffeq for `@muladd` removal

- Rmath/versions/0.1.0/requires
- Rmath/versions/0.1.1/requires
- Rmath/versions/0.1.2/requires
- Rmath/versions/0.1.3/requires
- Rmath/versions/0.1.4/requires
- Rmath/versions/0.1.5/requires
- Rmath/versions/0.1.6/requires
- Rmath/versions/0.1.7/requires
Older versions will break after JuliaLang/julia#19980 is merged.
Should only be merged after #10601.
> Insert julia version upper bound for Rmath

- OrdinaryDiffEq/versions/2.12.0/requires
- OrdinaryDiffEq/versions/2.13.0/requires
There is an impending change to the symplectic methods definitions which will break tests in OrdinaryDiffEq.jl.
> Add bounds to OrdinaryDiffEq.jl

- BinDeps/versions/0.7.0/requires
so it doesn't get used on versions of Julia susceptible to
https://github.com/JuliaLang/julia/pull/22886
ref https://github.com/JuliaStats/Rmath.jl/issues/38
> tighten lower bound of BinDeps 0.7.0

- BinDeps/versions/0.7.0/requires
the problem #10652 is avoiding is only an issue on linux
(and maybe freebsd)
> Allow BinDeps 0.7.0 on julia 0.5 and 0.6 on non-linux

- LanguageServer/versions/0.1.0/requires
- LanguageServer/versions/0.1.1/requires
- LanguageServer/versions/0.1.2/requires
- LanguageServer/versions/0.1.3/requires
- LanguageServer/versions/0.1.4/requires
- LanguageServer/versions/0.1.5/requires
I also had to add lower bounds, and I just picked the first version of CSTParser.jl that was registered in METADATA.jl. I'm almost certain that those lower bounds are not right, but the main purpose of this PR is to get the upper bounds in place.
> Add bounds to LanguageServer.jl requirements

- CSVFiles/versions/0.0.1/requires
- CSVFiles/versions/0.1.0/requires
- CSVFiles/versions/0.1.1/requires
- CSVFiles/versions/0.2.0/requires
- ExcelFiles/versions/0.0.1/requires
- ExcelFiles/versions/0.1.0/requires
- FeatherFiles/versions/0.0.1/requires
- FeatherFiles/versions/0.0.2/requires
- Query/versions/0.4.1/requires
- Query/versions/0.5.0/requires
- Query/versions/0.6.0/requires
- StatFiles/versions/0.0.1/requires
- StatFiles/versions/0.0.2/requires
IterableTables v0.5.0 will be breaking, so this bounds all existing packages that depend on it. I'll tag IterableTables v0.5.0 once this tag here is merged, and then will also tag new versions of all the packages that depend on IterableTables.
> Add upper bounds on IterableTables dependencies

- BedgraphFiles/versions/0.1.0/requires
Missed this one when I did #10832.
@CiaranOMara Cool package! I'm in the process of moving the trait definition from IterableTables to TableTraits to get rid of some annoying Requires.jl dependency. This here will prevent things from breaking, and I'll open PRs against BedgraphFiles.jl to make this a smooth transition.
> Add bounds to BedgraphsFiles package

- LazyQuery/versions/0.0.1/requires
- LazyQuery/versions/0.1.0/requires
- LazyQuery/versions/0.1.1/requires
Current LazyQuery.jl versions don't work with Query.jl v0.7.0, so this adds the appropriate bounds.
CC @bramtayl
> Add bounds to a LazyQuery dependency

- ControlCore/versions/0.0.1/requires
Deprecated [`ControlCore`](https://github.com/KTH-AC/ControlCore.jl) in favour of [`LTISystems`](https://github.com/JuliaSystems/LTISystems.jl).
Related to #11014 and #11015.
> Deprecate ControlCore

- DataCubes/versions/0.2.0/requires
- DataCubes/versions/0.2.0/sha1
Update to be compatible with Julia 0.6.
Diff vs v0.1.0: https://github.com/c-s/DataCubes.jl/compare/ec27b6dafb700c16e0739c0e547d7b9528134384...5573e2d3bef571e35c51ad9ec95ca67ff1b6d60c
> Tag DataCubes v0.2.0 [https://github.com/c-s/DataCubes.jl]

- DelayDiffEq/versions/0.10.0/requires
- DelayDiffEq/versions/0.9.0/requires
- DelayDiffEq/versions/0.9.1/requires
This PR adds upper bounds to `DelayDiffEq` versions since there was a breaking change in `OrdinaryDiffEq`, see https://github.com/JuliaDiffEq/DelayDiffEq.jl/pull/36 for more information.
> Upper bound DelayDiffEq

- Temporal/versions/0.4.3/requires
- Temporal/versions/0.4.3/sha1
Bugfix when indexing columns with `Vector{Symbol}` in combination with `:` for rows.
Diff vs v0.4.2: https://github.com/dysonance/Temporal.jl/compare/e0cfa3905446f34b601bf6469a944e31338137ee...4e736eae369fe2f2baf1a3832474cad3d06eda9c
> Tag Temporal v0.4.3 [https://github.com/dysonance/Temporal.jl]

- DelayDiffEq/versions/0.10.0/requires
- DelayDiffEq/versions/0.9.0/requires
- DelayDiffEq/versions/0.9.1/requires
This corrects https://github.com/JuliaLang/METADATA.jl/pull/11095. Sorry, I wrongly assumed upper bounds are inclusive.
> Correctly bound DelayDiffEq

- Graphs/versions/0.8.0/requires
- Graphs/versions/0.8.0/sha1
REDO of #11193 , but need minor version update for dropping Julia 0.4 support.
[Graphs.jl](https://github.com/JuliaArchive/Graphs.jl)
v0.7.1 -> [v0.8.0](https://github.com/JuliaArchive/Graphs.jl/releases/tag/v0.8.0)
[![Build Status](https://travis-ci.org/JuliaArchive/Graphs.jl.svg?branch=master)](https://travis-ci.org/JuliaArchive/Graphs.jl)
Diff vs v0.7.1: https://github.com/JuliaArchive/Graphs.jl/compare/0207655f5e3f51dde98e507b4e5f4ccf480390eb...784d12602dd3eefa2f94824ae7daf2b42b8c6b6c
REQUIRE
```
julia 0.5
DataStructures 0.5.0
Compat 0.18
```
> Tag Graphs v0.8.0 [https://github.com/JuliaArchive/Graphs.jl]

- KernelEstimator/versions/0.2.2/requires
- KernelEstimator/versions/0.2.2/sha1
Fix multivariate kde bandwidth issue.
Diff vs v0.2.1: https://github.com/panlanfeng/KernelEstimator.jl/compare/f776585cb8751147048ef14c80976551992502d3...f7821fdda02c6b75407d8cd79caf12ceca861b27
> Tag KernelEstimator v0.2.2 

- IncrementalInference/versions/0.2.10/requires
- IncrementalInference/versions/0.2.10/sha1
[IncrementalInference.jl](https://github.com/dehann/IncrementalInference.jl)
v0.2.9 -> [v0.2.10](https://github.com/dehann/IncrementalInference.jl/releases/tag/v0.2.10)
[![Build Status](https://travis-ci.org/dehann/IncrementalInference.jl.svg?branch=master)](https://travis-ci.org/dehann/IncrementalInference.jl)
Diff vs v0.2.9: https://github.com/dehann/IncrementalInference.jl/compare/476212075512dfff85b371a8254824693d3e8fd0...ac625cd49afd57d82413d3d305f26adddb7a974b
> Tag IncrementalInference v0.2.10

- DynamicalBilliards/url
- DynamicalSystems/url
Due to the creation of the github organization.
> change links to have JuliaDynamics instead of Datseris

- GPUArrays/versions/0.1.0/requires
- Transpiler/versions/0.1.0/requires
- Transpiler/versions/0.2.0/requires
- Transpiler/versions/0.3.0/requires
I think this is how we can assure, that GPUArrays still works after tagging Sugar + Transpiler for the new changes!
> add upper bounds for sugar + transpiler

- Reduce/versions/0.2.0/requires
- Reduce/versions/0.2.0/sha1
Significant update for [Reduce.jl](https://github.com/chakravala/Reduce.jl) that provies many new capabilities
*Symbolic parser generator for Julia language expressions using REDUCE algebra term rewrite system*
Interface for applying symbolic manipulation on Julia expressions using REDUCE's term rewrite system:
* reduce expressions are RExpr objects that can parse into julia Expr objects and vice versa;
* interface link communicates and interprets via various reduce output modes using rcall method;
* high-level reduce-julia syntax parser-generator walks arbitrary expression to rewrite mathematical code;
* import operators from REDUCE using code generation to apply to arbitrary computational expressions.
Diff vs v0.1.0: https://github.com/chakravala/Reduce.jl/compare/cec4d29741f351666b6adcd …
> Tag Reduce v0.2.0

- Codecs/versions/0.4.0/requires
- Codecs/versions/0.4.0/sha1
Diff vs v0.3.0: https://github.com/dcjones/Codecs.jl/compare/3413ecbd244dd34a04b67a95035762088588c137...e6dd7966fd1bc4a9bbffbd725f37da3a9a131a79
> Tag Codecs v0.4.0 [https://github.com/dcjones/Codecs.jl]

- GMT/url
GMT.jl is now hosted under the https://github.com/GenericMappingTools organization
> Change URL following the move to the GenericMappingTools organization

- GLMNet/versions/0.3.0/requires
Tagged with Compat too low. Ref https://github.com/JuliaStats/GLMNet.jl/pull/27
> Bump Compat dependency for GLMNet 0.3.0

- Celeste/versions/0.3.0/requires
cc @jeff-regier. Without this, the tagged version of Celeste doesn't load on 0.6.
> Add upper bounds of Celeste dependencies

- OptimBase/versions/0.1.0/requires
It seems that this was not necessary, and is currently making LsqFit downgrade NLSolversBase, Optim and NLsolve and LsqFit ends up not working as a result.
> Remove upper bound on OptimBase

- LowRankApprox/url
- LowRankApprox/versions/0.1.0/requires
- LowRankApprox/versions/0.1.0/sha1
This moves LowRankApprox to JuliaMatrices, and tags a new release that support v0.7-dev but drops v0.5.
> LowRankApprox v0.1.0

- Feather/versions/0.2.5/requires
This should be approved by someone from the JuliaData organization, ideally @quinnj.
It is a short-term fix for https://github.com/JuliaData/Feather.jl/issues/58, which is a real issue for all the downstream packages because it breaks all the tests.
> Add upper bound on a Feather dependency

- Augmentor/versions/0.0.1/requires
- Augmentor/versions/0.0.2/requires
- Augmentor/versions/0.1.0/requires
- Augmentor/versions/0.2.0/requires
- Augmentor/versions/0.3.0/requires
The tagged versions of Augmentor rely on a function in ImageCore that was removed with ImageCore 0.5
> Augmentor.jl: restrict upper version of ImageCore and StaticArrays

- RCall/versions/0.7.5/requires
- RCall/versions/0.8.0/requires
- RCall/versions/0.8.1/requires
These should have been included in #12039.
Cc: @randy3k
> Add missing upper bounds on CategoricalArrays 0.3.0 to recent RCall releases

- AmplNLWriter/versions/0.3.0/requires
- CPLEX/versions/0.2.8/requires
- Cbc/versions/0.3.2/requires
- Clp/versions/0.3.1/requires
- CoinOptServices/versions/0.2.0/requires
- Convex/versions/0.5.0/requires
- GLPKMathProgInterface/versions/0.3.4/requires
- Gurobi/versions/0.3.3/requires
- Ipopt/versions/0.2.6/requires
- JuMP/versions/0.18.0/requires
- KNITRO/versions/0.3.1/requires
- NLopt/versions/0.3.6/requires
- Pajarito/versions/0.5.0/requires
- SCIP/versions/0.4.0/requires
- SCS/versions/0.3.3/requires
- Xpress/versions/0.5.0/requires
A "major" version bump for MathProgBase 0.7 was required as it dropped support for Julia 0.5, no changes otherwise.
> update MathProgBase upper bounds

- Gallium/versions/0.0.1/requires
- Gallium/versions/0.0.2/requires
- Gallium/versions/0.0.3/requires
- Gallium/versions/0.0.4/requires
In preparation for tagging a new 0.6 Gallium that just re-exports ASTInterpreter2.
> Upper bound julia versions for old Gallium

- LazyQuery/versions/0.1.2/requires
- LazyQuery/versions/0.1.3/requires
Query v0.8.0 will break LazyQuery, so we need an upper bound. @bramtayl.
> Add upper bound to a LazyQuery dep

- Reduce/versions/0.2.2/requires
- Reduce/versions/0.2.2/sha1
Performance improvements, matrices, compatibility, and robustness
Diff vs v0.2.1: https://github.com/chakravala/Reduce.jl/compare/da8db01b9f1ce37b86e8c2d7ca71a70366295f23...b9c379ecc0879b8dfc2ada6a3d8ef979a3754ee3
> Tag Reduce v0.2.2

- Gallium/versions/0.0.1/requires
- Gallium/versions/0.0.2/requires
- Gallium/versions/0.0.3/requires
- Gallium/versions/0.0.4/requires
The user's who have already installed older versions of Gallium and pinned it's version, are now unable to perform `Pkg.add()` operations because of this change, reverting this PR will avoid user's from encountering this issue in future.
> Reverts https://github.com/JuliaLang/METADATA.jl/pull/12106/

- CUBLAS/versions/0.2.0/requires
- CUBLAS/versions/0.2.1/requires
- CUBLAS/versions/0.2.2/requires
- CUDAdrv/versions/0.7.0/requires
- CUDAdrv/versions/0.7.0/sha1
- CUDAnative/versions/0.5.1/requires
- CUDAnative/versions/0.5.2/requires
- CUDAnative/versions/0.5.3/requires
- CUDAnativelib/versions/0.0.1/requires
- CUDArt/versions/0.3.0/requires
- CUDArt/versions/0.3.1/requires
- CUDArt/versions/0.3.2/requires
- CUDArt/versions/0.4.0/requires
- CUDArt/versions/0.4.1/requires
- CUDNN/versions/0.4.0/requires
- CURAND/versions/0.1.0/requires
- CuArrays/versions/0.1.0/requires
- CuArrays/versions/0.1.1/requires
- CuArrays/versions/0.2.0/requires
- CuArrays/versions/0.2.1/requires
- CuArrays/versions/0.3.0/requires
- GPUArrays/versions/0.1.0/requires
Same as #12179, with additional commit for changing bounds on other packages.
Repository: [JuliaGPU/CUDAdrv.jl](https://github.com/JuliaGPU/CUDAdrv.jl)
Release: [v0.7.0](https://github.com/JuliaGPU/CUDAdrv.jl/releases/tag/v0.7.0)
Diff: [vs v0.6.1](https://github.com/JuliaGPU/CUDAdrv.jl/compare/dccdaa0f39477e9570b5c24d0b15ac849e93582f...9dc229600e70223b4ab4cfab7bc23e4b36da7bf0)
`requires` vs v0.6.1: no changes
I plan on using the 0.7.x versions of CUDAdrv to remove CuArray in favor of CuArrays.jl.
This is a breaking change, hard to deprecate (as CuArrays.CuArray isn't meant to be identical to CUDAdrv.CuArray), so I've just added upper bounds to all packages using CUDAdrv.
Not sure whether that's the best approach though.
> Tag CUDAdrv.jl v0.7.0

- OAuth/versions/0.6.1/requires
- OAuth/versions/0.6.1/sha1
Diff vs v0.6.0: https://github.com/randyzwitch/OAuth.jl/compare/142fe5d7a25a7ca5ee09a03932dfc1ad89033c31...bdfe2c9d0bd14b1bb70a7691d2238523cae7de2e
> Tag OAuth v0.6.1 [https://github.com/randyzwitch/OAuth.jl]

- .test/list_3582.jl
Addresses issue introduced in https://github.com/JuliaLang/METADATA.jl/pull/12489
> Add AutoGrad v0.0.10 to the grandfather list

- ReadStat/url
Evan transferred the repo over to me because he is no longer active in the julia ecosystem and I had been maintaining things for the last 1.5 years or so already.
> Update ReadStat.jl URL

- LineSearches/versions/3.0.0/requires
- LineSearches/versions/3.0.1/requires
- LineSearches/versions/3.1.0/requires
- LineSearches/versions/3.2.0/requires
- LineSearches/versions/3.2.1/requires
- LineSearches/versions/3.2.2/requires
- LineSearches/versions/3.2.3/requires
These weren't necessary after all, so no need to have them, as it'll just force us to tag a new LineSearches.jl
> Remove unnecessary upper bounds on NLSolversBase in LineSearches.

- MFCC/versions/0.2.0/requires
- MFCC/versions/0.2.0/sha1
This PR makes MFCC compatible with Julia-0.6 again.   Code has not changed much, but we're dropping support for Julia-0.5 and earlier. 
Diff vs v0.1.1: https://github.com/davidavdav/MFCC.jl/compare/0b7cbdd56a10987f62e6e1f8e2864824f98e9ec8...e1adfaa57a730f9efa5c9245ada3e863ff2f702a
> Tag MFCC v0.2.0 [https://github.com/davidavdav/MFCC.jl]

- ZipFile/versions/0.5.0/requires
- ZipFile/versions/0.5.0/sha1
Diff vs v0.4.0: https://github.com/fhs/ZipFile.jl/compare/46542e4d9b6e859ac8f2c68bc21318bfcbf2e9a9...2811b56c0a8f2e676c7f5ed52fbfefdd1344bef8
update https://github.com/fhs/ZipFile.jl/pull/38
> Tag ZipFile v0.5.0 [https://github.com/fhs/ZipFile.jl]

- Decimals/versions/0.2.1/requires
- Decimals/versions/0.2.1/sha1
Diff vs v0.2.0: https://github.com/tinybike/Decimals.jl/compare/61b23a4176b735cb95ce097ac89e5a3533a688a2...be5eaccbabeb36de76f7ac06547400c74ea82160
> Tag Decimals v0.2.1 [https://github.com/tinybike/Decimals.jl]

- BlackBoxOptimizationBenchmarking/versions/0.0.1/requires
Since no bounds are on here, I guess that it's just supposed to work on current Optim. Needs to be merged for https://github.com/JuliaLang/METADATA.jl/pull/12709 not to fail.
> Bound Optim BlackBoxOptimBenchmaring

- FourierFlows/url
The repository was moved from my personal GitHub account to an organization named "FourierFlows".
> Update FourierFlows url

- RDatasets/versions/0.2.0/requires
With version 0.11.4 of `DataFrames` this version of `RDatasets` works again
> Update to latest changes in DataFrames

- .test/check-pr.jl
This adjusts the logic for checking whether policy 8 (don't change the SHA of an existing tag) is violated. In particular, it explicitly adds JuliaLang/METADATA.jl as a remote, fetches from it, and compares its head commit against the current commit SHA in the PR, as given by Travis. Hopefully this will improve the reliability of this sporadically incorrect check.
> Improve the PR check for changing SHAs

- .test/check-pr.jl
Currently when examining the changes made in a PR, the check groups additions and modifications together, then checks that none of the files in that group is a package's sha1 file. The problem with that is for new tags, the sha1 will _always_ be listed as changed, since additions and modifications are grouped together. Thus this PR separates them, and only the modified files are checked for adherence to policy 8. (This was my bad, sorry folks.)
> Fix incorrect diff filter for changes

- .test/check-pr.jl
- .test/ci.sh
The changes introduced in https://github.com/JuliaLang/METADATA.jl/pull/12891 break support for private METADATA which run tests on other CI systems (GitLab CI for example).
Key take aways for maintaining support for alternative CI testing:
- Avoid requiring Travis CI specific environment variables "TRAVIS_*"
- Avoid interacting with "https://github.com/JuliaLang/METADATA.jl.git" and instead use `origin`
- Use `origin/HEAD` instead of `origin/metadata-v2` as private METADATAs may use a different remote head name
> Support testing on private METADATA again

- .test/check-pr.jl
> "git diff A...B" is equivalent to "git diff $(git-merge-base A B) B"
When running the "check-pr.jl" tests we use `git diff` to verify that no METADATA files were modified which should remain constant. When we use `git diff A B` we can potentially see changes which occurred outside of the scope of the PR.
I believe (I haven't fully validated this) that it's caused from the `origin/HEAD` being updated and being newer than the HEAD.
> Use common ancestor for git diff

- ROCAnalysis/versions/0.2.0/requires
- ROCAnalysis/versions/0.2.0/sha1
This brings this package up to date with julia-0.6, and drops support for 0.5. 
Diff vs v0.1.0: https://github.com/davidavdav/ROCAnalysis.jl/compare/487dd1fd9fcb6959b400f6013edde1adde2b5834...21aef7e498ed9210aa96ebcfdbd481d0cc117df0
> Tag ROCAnalysis v0.2.0 [https://github.com/davidavdav/ROCAnalysis.jl]

- CUDAdrv/versions/0.8.0/requires
Not sure if its OK to retroactively change REQUIRES like that. But there's incompatibilities between CUDAdrv 0.8.0 and CUDAnative for Julia 0.6, so I'd rather bake this in METADATA. It also keeps the breaking API changes to Julia 0.7 users.
> Restrict CUDAdrv 0.8+ to Julia 0.7

- .test/METADATA.jl
- .test/ci.sh
Merging ~~https://github.com/JuliaLang/julia/pull/25662~~ https://github.com/JuliaLang/julia/pull/25472 ~~broke the version testing here~~ printed an error in the log which is confusing when the tests fail for some other reason or because of timeout.
The `Pkg` deprecation warning also added a lot of noise. Finally, I've disabled running the tests in parallel. It completely messes up the log and was the original reason why I missed an error. It will make each build slower but I guess it shouldn't have an effect on the overall throughput since we can just run more builds concurrently. Is that a correct interpretation of Travis?
> Clean up the log

- ODEInterface/versions/0.4.2/requires
- ODEInterface/versions/0.4.2/sha1
* Workaround for Issue https://github.com/JuliaLang/julia/issues/25281 to make ODEInterface-Package usable again in julia v0.7/trunk.
A lot of syntax/deprecation changes for julia v0.7/trunk:
* `STDERR -> stderr`
* use newline instead of `->` in doc syntax 
* `unsafe_warp`: own-arg
* Pkg moved from base to stdlib: Libdl, Markdown, LinearAlgebra, Test, Unicode
* `Void -> Cvoid`
* use "uninitialized" for `Matrix{}`, `Vector{}`: `Array{}(uninitialized, ...)`
* `cfunction` with `Tuple{...}`
At the moment: no errors or warnings in the current nightlies during build and test.
> Tag ODEInterface v0.4.2 [https://github.com/luchr/ODEInterface.jl]

- BlockArrays/versions/0.3.1/requires
- BlockArrays/versions/0.3.1/sha1
Diff vs v0.3.0: https://github.com/JuliaArrays/BlockArrays.jl/compare/948e5c16eaf430407db8e6f546d9fb23f8dc9b3c...c75e9a8f7fbfab9ffc7626d9df04bd4b602d2ae2
> Tag BlockArrays v0.3.1 [https://github.com/JuliaArrays/BlockArrays.jl]

- AprilTags/url
- MotionCaptureJointCalibration/url
- RigidBodyDynamics/url
- RigidBodySim/url
@Affie (and @dehann), I took the liberty of changing the AprilTags.jl URL as well.
> Update package URLs after move to JuliaRobotics organization.

- LCMCore/url
You can see the github redirect already in place: <https://github.com/rdeits/LCMCore.jl>
> Move LCMCore.jl URL from rdeits to JuliaRobotics

- BioAlignments/versions/0.1.0/requires
- BioAlignments/versions/0.2.0/requires
The new release of BioSymbols v2.0, breaks current versions of BioAlignments, so I've altered their require lines to avoid any issues when installing. ref: #13812
> BioAlignments retag

- Optim/versions/0.14.1/requires
The Optim v0.14.1 entry was not in my local metadata when I made th prevoius PR.
> Upper bound LineSearches in Optim v0.14.1

- StatsModels/versions/0.1.0/requires
- StatsModels/versions/0.2.0/requires
- StatsModels/versions/0.2.1/requires
- StatsModels/versions/0.2.2/requires
That version changed the behavior of unique, which breaks older StatsModels releases (https://github.com/JuliaStats/StatsModels.jl/pull/55).
Merge after the new StatsModels version is tagged (https://github.com/JuliaLang/METADATA.jl/pull/14303).
> Add upper bounds on CategoricalArrays 0.3.8 to StatsModels

- SOM/url
Dear Administrators.
The Github repo has a **new url:**
The **first releases** 
were published from my personal github account (andreasdominik) ...
In the **meanwhile** 
more and more projects in my team are migrated to Julia
and as a result we started to develop more Julia packages (and reduce our
activity with R). Different students and researchers are owners of
the projects. Therefore it make sense to have all packages in one
organisation structure at Github and not in different personal accounts.
I did the repo transfer with the splendid Github transfer tool, so that
all links to the original repo keep in place (cloning from the old
repo is still possible and reflects updates). However it make sense to change the repo path of the
package to the new location. 
Thank you very much for …
> Update url of package SOM.jl

- Xtensor/versions/0.0.1/requires
- Xtensor/versions/0.0.10/requires
- Xtensor/versions/0.0.11/requires
- Xtensor/versions/0.0.2/requires
- Xtensor/versions/0.0.3/requires
- Xtensor/versions/0.0.4/requires
- Xtensor/versions/0.0.5/requires
- Xtensor/versions/0.0.6/requires
- Xtensor/versions/0.0.7/requires
- Xtensor/versions/0.0.8/requires
- Xtensor/versions/0.0.9/requires
- Xtensor/versions/0.1.0/requires
Is it ok to add this upper bound now, or do we have to release a new version of xtensor-julia?
> Add upper bound to xtensor CXXWrap version

- Homotopies/versions/0.1.0/requires
This updates all versions of `Homotopies` to use an upper bound for `FixedPolynomials`. This was discussed with @andreasnoack in #14585 to make JuliaCIBot pass for #14585.
> Add in Homotopies upper bound for FixedPolynomials

- StatsBase/versions/0.18.0/requires
- StatsBase/versions/0.19.0/requires
explicitly use Compat to avoid stderr conflict caused by other
packages using Compat
> Add upper bound on Compat for StatsBase versions that don't

- ReferenceFrameRotations/url
The package ReferenceFrameRotations.jl was transfered to the
Organization SatelliteToolbox and this commit updates the URL of
the package.
> Move ReferenceFrameRotations.jl to SatelliteToolbox Org

- ExperimentalAnalysis/versions/0.0.1/requires
- ExperimentalAnalysis/versions/0.0.2/requires
- ExperimentalAnalysis/versions/0.1.0/requires
- ExperimentalAnalysis/versions/0.1.1/requires
uses ~ parsed as macro which stopped working in Julia 0.6
> Add upper bounds on Julia 0.6 for ExperimentalAnalysis since package

- NLsolve/versions/1.1.0/requires
This was a mistake. The upper bounds was only present in METADATA and not the repo as such. It should have been there all along.
> Add upper bound to NLsolve

- .test/list_3582.jl
Requesting an exception for `mPulseAPI v1.0.7` to continue to support julia v0.4.  We have current paying customers using our code with julia 0.4 and have tested extensively that all parts continue to work with julia 0.4.
Ref: https://github.com/JuliaLang/METADATA.jl/pull/14733#issuecomment-390623046
Thanks.
> Requesting exception for mPulseAPI 1.0.7 to support julia 0.4

- MIDI/url
Otherwise attobot cannot tag a release in metadata...
> update URL for new organization

- FillArrays/versions/0.1.0/requires
- FillArrays/versions/0.1.0/sha1
Diff vs v0.0.1: https://github.com/JuliaArrays/FillArrays.jl/compare/b138617bd1fd9394132f3aa75015f9afb6fbc8cc...1e4e4e6d1a688c9eae918a0c881ffbde4d4a0a11
> Tag FillArrays v0.1.0 [https://github.com/JuliaArrays/FillArrays.jl]

- SumOfSquares/versions/0.1.0/requires
- SumOfSquares/versions/0.1.1/requires
The release v0.1.0 of MultivariateMoments is going to break SumOfSquares but upper bounds can prevent this to harm anyone
> Add upper bounds to SumOfSquares for MultivariateMoments

- ACME/versions/0.2.0/requires
- ACME/versions/0.2.1/requires
- ACME/versions/0.2.2/requires
- ACME/versions/0.3.0/requires
These ACME versions fail during `using` on julia 0.7.0-DEV.3220 and later.
> Upper bound julia version for older ACME versions

- ECOS/versions/0.9.0/requires
No changes are needed for ECOS in order to work with MathOptInterface (MOI) v0.4.
See https://github.com/JuliaOpt/ECOS.jl/pull/68
> Bump MOI upper bound to v0.5 for ECOS

- CSDP/versions/0.1.0/requires
No changes are needed for ECOS in order to work with MathOptInterface (MOI) v0.4. The needed changes will be in SemidefiniteOptInterface v0.1.
See https://github.com/JuliaOpt/CSDP.jl/pull/24
> Bump MOI upper bound to v0.5 for CSDP

- FastTransforms/versions/0.0.4/requires
- FastTransforms/versions/0.0.5/requires
- FastTransforms/versions/0.0.6/requires
- FastTransforms/versions/0.0.7/requires
- FastTransforms/versions/0.1.0/requires
- FastTransforms/versions/0.2.0/requires
- FastTransforms/versions/0.2.1/requires
- FastTransforms/versions/0.2.2/requires
- FastTransforms/versions/0.3.0/requires
- FastTransforms/versions/0.3.1/requires
- FastTransforms/versions/0.3.2/requires
Adds upper bounds in FastTransforms.jl for new ToeplitzMatrices.jl.
> upper bound for ToeplitzMatrices 0.4
