JuliaLang/METADATA.jl

Combinatorics/versions/0.1.2/requires, Combinatorics/versions/0.1.2/sha1
Fixes Int/Cint confusion on 64-bit systems
=> Tag Combinatorics v0.1.2

Convex/versions/0.0.2/requires, Convex/versions/0.0.2/sha1
cc @madeleineudell @joehuchette
=> Tag Convex v0.0.2

WAV/versions/0.4.1/requires, WAV/versions/0.4.1/sha1
Fixes:
* WAV.jl Issue #18
* playback of mono files on Julia v0.3
=> Tag WAV v0.4.1

HDF5/versions/0.4.10/requires
ref https://github.com/timholy/HDF5.jl/pull/203#issuecomment-70941245 and https://github.com/JuliaLang/julia/pull/9161#issuecomment-70941563
cc @timholy @simonster is this all that's needed in METADATA to fix this?
=> bump julia requirement for HDF5 0.4.10 to 0.3.4

KNITRO/versions/0.0.5/requires, KNITRO/versions/0.0.5/sha1
=> Tag KNITRO v0.0.5

Twitter/versions/0.2.0/requires, Twitter/versions/0.2.0/sha1
Factor out OAuth code into separate library, OAuth.jl
=> Tag Twitter v0.2.0

NamedArrays/url
As requested and discussed in https://github.com/JuliaLang/METADATA.jl/pull/2057#issuecomment-72294827
=> Added .jl to NamedArrays URL

.test/METADATA.jl, .travis.yml, LightXML/versions/0.1.10/requires, LightXML/versions/0.1.10/sha1
adds `free` and `unlink` for `XMLElement` and `XMLNode`
=> Tag LightXML v0.1.10

ZMQ/versions/0.1.16/requires, ZMQ/versions/0.1.16/sha1
This changes to a WinRPM binary, ref https://groups.google.com/forum/#!topic/julia-users/8TeUa5uJKs4
=> Tag ZMQ v0.1.16

StreamStats/url, StreamStats/versions/0.0.1/requires, StreamStats/versions/0.0.1/sha1
This adds a standardized package for computing statistics on streaming data.
=> Add StreamStats package

Color/versions/0.4.0/requires, Color/versions/0.4.0/sha1
Update REQUIRE to use Graphics package (https://github.com/JuliaLang/julia/pull/10150)
=> Tag Color v0.4.0

GitHub/versions/0.0.6/requires, GitHub/versions/0.0.6/sha1
Feel bad tagging two versions in one day, but it should be fine
=> Tag GitHub v0.0.6

PGFPlots/versions/1.2.1/requires, PGFPlots/versions/1.2.1/sha1
Bug fixes and added additional colormaps.
=> Tag PGFPlots v1.2.1

Patchwork/versions/0.1.3/requires, Patchwork/versions/0.1.3/sha1
Fixes JuliaLang/Interact.jl#46
And some improvements to tests
=> Tag Patchwork v0.1.3

Timestamps/url, Timestamps/versions/0.0.1/requires, Timestamps/versions/0.0.1/sha1
This package provides a time-aware data structure that does not have the constraints found in the `TimeSeries.TimeArray` data structure.
Each single `Timestamp` object is immutable and consists of a `timestamp` element and a `value` element. These objects can be aggregated into array structures. There is no checking that the `value` elements in such an array of of the same type, so a pseudo-hetergenous array structure is possible. 
Also allowed are duplicate dates. 
Documentation can be found [here](http://timestampsjl.readthedocs.org/en/latest/).
=> Register Timestamps

Wavelets/versions/0.3.0/requires, Wavelets/versions/0.3.0/sha1
=> Tag Wavelets v0.3.0

SCS/versions/0.0.3/requires, SCS/versions/0.0.3/sha1
Fixes SCS on 0.4
@madeleineudell @karanveerm
=> Tag SCS v0.0.3

LightXML/versions/0.1.11/requires, LightXML/versions/0.1.11/sha1
=> Tag LightXML v0.1.11

Ipopt/versions/0.1.13/requires, Ipopt/versions/0.1.13/sha1
Changes the Windows binary to use WinRPM
=> Tag Ipopt v0.1.13

BinDeps/versions/0.3.11/requires, BinDeps/versions/0.3.11/sha1
fixes for tuple changes in 0.4
=> Tag BinDeps v0.3.11

Calculus/versions/0.1.7/requires, Calculus/versions/0.1.7/sha1
Tuple fixes for 0.4
@johnmyleswhite
=> Tag Calculus v0.1.7

Iterators/versions/0.1.8/requires, Iterators/versions/0.1.8/sha1
Closes https://github.com/JuliaLang/Iterators.jl/issues/48.
=> Tag Iterators v0.1.8

GaussianMixtures/versions/0.0.7/requires, GaussianMixtures/versions/0.0.7/sha1
Fixing several issues in GaussianMixtures, I believe https://github.com/davidavdav/GaussianMixtures.jl/issues/8, https://github.com/davidavdav/GaussianMixtures.jl/issues/9 and https://github.com/davidavdav/GaussianMixtures.jl/issues/10.
=> Tag GaussianMixtures v0.0.7

SparseVectors/url
=> url correction: SparseExtensions to SparseVectors

TimeSeries/versions/0.5.8/requires, TimeSeries/versions/0.5.8/sha1
Need to import Base.values for existing method.
(for the record, I defined it first :smile: )
=> Tag TimeSeries v0.5.8

Winston/versions/0.11.10/requires
ref https://github.com/nolta/Winston.jl/pull/222, this tag does not work correctly on 0.3, so prevent it from being installed there
cc @nolta
=> Change julia requires of Winston 0.11.10 to 0.4-

LightGraphs/versions/0.1.14/requires, LightGraphs/versions/0.1.14/sha1
Improved Dijkstra and betweenness centrality; edge distances can be different types.
=> Tag LightGraphs v0.1.14

EvolvingGraphs/versions/0.0.4/requires, EvolvingGraphs/versions/0.0.4/sha1
v0.0.4
---------
* new metrics:
- `shortest_path(g, v1, v2)`
- `shortest_distance(g, v1, v2)`
- `shortest_temporal_path(g, (v1, t1), (v2, t2))`
- `shortest_temporal_distance(g, (v1, t1), (v2, t2))`
* new functions:
- `has_node(g, v, t)`
- `out_neighbors(g, v, t)`
- slicing: `slice(g, t_min, t_max)` and `slice!(g, t_min, t_max)`
- sorting: `issorted(g)`, `sorttime(g)` and `sorttime!(g)`
* tutorial for analyzing evolving graphs
=> Tag EvolvingGraphs v0.0.4

Meshes/versions/0.1.0/requires, Meshes/versions/0.1.0/sha1
Fix of https://github.com/JuliaLang/METADATA.jl/pull/2724
=> Tag Meshes v0.1.0

ConfParser/url, HexEdit/url, NMEA/url, Pcap/url
Created a new github account and changed ownership of the packages from my old account to my new acct.  I am updating the url's for METADATA
=> changed urls for my packages to my new acct

JuliaFEM/url
Registeration of JuliaFEM, FEM project that develops open-source software for reliable, scalable, distributed Finite Element Method.
=> Register JuliaFEM

Levenshtein/url
Small package for measuring the Levenshtein distance between two Strings.
=> Register Levenshtein

KrylovMethods/url
KrylovMethods is a collection of some iterative methods for solving linear systems of equations. It is tuned for large sparse linear systems (where the performance is slightly better than the similar IterativeSolvers package), but works also on function handles and LinearOperators.
=> Register KrylovMethods

EvolvingGraphs/versions/0.0.6/requires, EvolvingGraphs/versions/0.0.6/sha1
v0.0.6
---------
* new data type
- `AggregatedGraph`
- `AttributeNode`
* redefine `out_neighbors` to fix the shortest temporal path
mistake. This change will affect the results of
`shortest_temporal_path` and `weak_connected_components`.
* redefine type hierarchy, introduce abstraction `AbstractStaticGraph`. 
* define function `eltype` on node types. 
* new functions:
- `undirected` and `undirected!` turns a directed evolving graph to an undirected
evolving graph.
=> Tag EvolvingGraphs v0.0.6

Augur/url, Augur/versions/0.0.1/requires, Augur/versions/0.0.1/sha1
I think I did the rebase correctly, but please let me know if this broke anything.
=> Register and tag Augur v0.0.1

JavaCall/versions/0.2.3/requires, JavaCall/versions/0.2.3/sha1
=> Tag JavaCall v0.2.3

BinDeps/versions/0.3.14/requires, BinDeps/versions/0.3.14/sha1
Now with hopefully less package breakage!
=> Tag BinDeps v0.3.14

KNITRO/versions/0.0.6/requires, KNITRO/versions/0.0.6/sha1
Closes https://github.com/JuliaOpt/KNITRO.jl/issues/32
@davidanthoff
=> Tag KNITRO v0.0.6

JDBC/url, JDBC/versions/0.0.1/requires, JDBC/versions/0.0.1/sha1
A julia package to use Java JDBC drivers to access databases
=> Register JDBC: v0.0.1

Calculus/versions/0.1.9/requires, Calculus/versions/0.1.9/sha1
Fixes some deprecation warnings on 0.4
CC @johnmyleswhite
=> Tag Calculus v0.1.9

StatsFuns/url, StatsFuns/versions/0.0.1/requires, StatsFuns/versions/0.0.1/sha1
This is package collects all numerical special functions from `StatsBase` and `Distributions`. 
Purposes:
- This package serves the similar role as `Rmath`. `Distributions` will depend on this package instead of on `Rmath` directly. The efforts of replacing `Rmath` computational routines will happen here.
- By moving the numerical functions to this package, the development on downstream packages can focus on higher-level functionalities, while implementing/testing/optimizing the computational routines would happen in this package. 
- There are packages that may need some special stats-functions, but don't need the distributions.
=> Register StatsFuns

Lexicon/versions/0.1.15/requires, Lexicon/versions/0.1.15/sha1
=> Tag Lexicon v0.1.15

SimJulia/versions/0.3.2/requires, SimJulia/versions/0.3.2/sha1
=> Tag SimJulia v0.3.2: Fix regression

Revealables/url, Revealables/versions/0.0.1/requires, Revealables/versions/0.0.1/sha1
Register a package for hiding/revealing content in Julia notebooks
=> Register Revealables

RNGTest/versions/0.0.5/requires, RNGTest/versions/0.0.5/sha1
=> Tag RNGTest v0.0.5

Faker/url, Faker/versions/0.0.1/requires, Faker/versions/0.0.1/sha1
This package is a generator of fake information, for julia 0.4.0
=> Register Faker

UnicodePlots/url
Hi!
This is basically a reboot of the idea behind TextPlots.jl library, which seems abandoned.
=> Register UnicodePlots

ConfParser/url, HexEdit/url, NMEA/url, Pcap/url
=> changed urls

JSON/versions/0.4.5/requires, JSON/versions/0.4.5/sha1
Deprecation fixes and a Unicode bug
=> Tag JSON v0.4.5

RouletteWheels/versions/0.0.3/requires, RouletteWheels/versions/0.0.3/sha1
- **MAJOR bugfix** in the `StochasticAcceptance` `setindex!` method. 
- Add `WheelFromDict` wrapper.
- Add `select_fastest` function.
=> Tag RouletteWheels v0.0.3

ColorTypes/url, ColorTypes/versions/0.1.0/requires, ColorTypes/versions/0.1.0/sha1
=> Tag ColorTypes v0.1.0

FixedEffectModels/versions/0.1.0/sha1
=> correct sha

Taro/versions/0.2.0/requires, Taro/versions/0.2.0/sha1
Ability to generate PDF files via FOP
=> Tag Taro v0.2.0

InterestRates/url, InterestRates/versions/0.0.1/requires, InterestRates/versions/0.0.1/sha1
Tools for Term Structure of Interest Rates calculation, aimed at the valuation of financial contracts, specially Fixed Income instruments.
=> New package registration: InterestRates.jl

CoinOptServices/versions/0.0.6/requires, CoinOptServices/versions/0.0.6/sha1
closes https://github.com/JuliaOpt/CoinOptServices.jl/issues/7
=> Tag CoinOptServices v0.0.6

JuMP/versions/0.10.0/requires, JuMP/versions/0.10.0/sha1
=> Tag JuMP v0.10.0

Conda/versions/0.1.1/requires, Conda/versions/0.1.1/sha1
Fix a function call in installation. I'll take care that Travis is green before tagging next time!
=> Tag Conda v0.1.1

GitHub/versions/1.0.0/requires, GitHub/versions/1.0.0/sha1
Calling this 1.0 might be a bit of a stretch, but it's out there and usable so I'm going with it.
=> Tag GitHub v1.0.0

ForwardDiff/versions/0.1.0/requires, ForwardDiff/versions/0.1.0/sha1
My JSoC project finally bears fruit!
=> Tag ForwardDiff v0.1.0

JuMP/versions/0.10.1/requires, JuMP/versions/0.10.1/sha1
=> Tag JuMP v0.10.1

CUSPARSE/url
I moved CUSPARSE.jl from my ownership to JuliaGPU's.
=> Updated CUSPARSE's URL to reflect ownership transfer

FastGaussQuadrature/url
FastGaussQuadrature is a package to calculate Gauss Legendre, Jacobi, Hermite, Radau and Lobatto  quadrature rules in O(n) operations.
=> Register FastGaussQuadrature

RouletteWheels/versions/0.0.4/requires, RouletteWheels/versions/0.0.4/sha1
=> Tag RouletteWheels v0.0.4

Immerse/versions/0.0.3/requires, Immerse/versions/0.0.3/sha1
=> Tag Immerse v0.0.3

FMIndexes/url, FMIndexes/versions/0.0.1/requires, FMIndexes/versions/0.0.1/sha1
https://github.com/BioJulia/FMIndices.jl
=> Register FMIndexes: v0.0.1

DocOpt/versions/0.1.1/requires, DocOpt/versions/0.1.1/sha1
Suppressed warnings on v0.4.0-rc2.
=> Tag DocOpt v0.1.1

WAV/versions/0.6.1/requires, WAV/versions/0.6.1/sha1
=> Tag WAV v0.6.1

ConfParser/url, HexEdit/url, NMEA/url, Pcap/url
=> changed urls for my packages

StatsBase/versions/0.7.3/requires, StatsBase/versions/0.7.3/sha1
=> Tag StatsBase 0.7.3

Parameters/versions/0.1.1/requires, Parameters/versions/0.1.1/sha1
=> Tag Parameters v0.1.1

AWS/versions/0.1.8/requires
Fixes https://github.com/amitmurthy/AWS.jl/issues/42#issuecomment-142424473
=> Update REQUIRE for AWS version 0.1.8

IterativeSolvers/versions/0.2.0/requires, IterativeSolvers/versions/0.2.0/sha1
Provides `svdl`, a high performance iterative SVD
=> Tag IterativeSolvers v0.2.0

OAuth/versions/0.3.0/requires, OAuth/versions/0.3.0/sha1
=> Tag OAuth v0.3.0

Interpolations/versions/0.3.1/requires, Interpolations/versions/0.3.1/sha1
This release includes a complete rewrite of the extrapolation functionality
with extended support for various schemes as well as support for combining
schemes in any concievable way.
=> Tag Interpolations.jl v0.3.1

Contour/versions/0.0.8/requires, Contour/versions/0.0.8/sha1
Ensure compatibility with Julia 0.4 without warnings.
=> Tag Contour v0.0.8

Compat/versions/0.7.5/requires
fixes https://github.com/JuliaLang/Compat.jl/issues/147
=> fix a compat tag that's broken on 0.3

Mustache/versions/0.0.14/requires, Mustache/versions/0.0.14/sha1
=> Tag Mustache v0.0.14

BDF/versions/0.1.0/requires, BDF/versions/0.1.0/sha1
=> Tag BDF v0.1.0

SerialPorts/versions/0.0.3/requires, SerialPorts/versions/0.0.3/sha1
This adds support for using a Conda install.
=> Tag SerialPorts v0.0.3

JuMPChance/versions/0.2.2/requires, JuMPChance/versions/0.2.2/sha1
=> Tag JuMPChance v0.2.2

AmplNLWriter/url
=> Update AmplNLWriter URL

OpenCL/versions/0.3.5/requires, OpenCL/versions/0.3.5/sha1
=> Tag OpenCL v0.3.5

.test/METADATA.jl
With the switch to libgit2, all new registered packages will be https:// by default on v0.5 dev.
=> Allow https:// pkg urls and some cleanup

Mux/versions/0.1.1/requires, Mux/versions/0.1.1/sha1
=> Tag Mux v0.1.1

AffineTransforms/versions/0.1.1/requires, AffineTransforms/versions/0.1.1/sha1
Updates for new Interpolations API, allow CartesianIndex, more comprehensive array transformations.
=> Tag AffineTransforms v0.1.1

LightGraphs/versions/0.3.4/requires, LightGraphs/versions/0.3.4/sha1
This will be the final version with explicit support for Julia v0.3.
=> Tag LightGraphs v0.3.4

JavaCall/versions/0.3.3/requires, JavaCall/versions/0.3.3/sha1
=> Tag JavaCall v0.3.3

IJuliaPortrayals/versions/0.0.4/requires, IJuliaPortrayals/versions/0.0.4/sha1
- Clear `String`-related deprecation warnings.
=> Tag IJuliaPortrayals v0.0.4

Immerse/versions/0.0.1/requires, Immerse/versions/0.0.2/requires, Immerse/versions/0.0.3/requires, Immerse/versions/0.0.4/requires, Immerse/versions/0.0.5/requires, Immerse/versions/0.0.6/requires, Immerse/versions/0.0.7/requires, Immerse/versions/0.0.8/requires
See https://github.com/JuliaGraphics/Immerse.jl/issues/16.
=> Pin Gadfly to version that works for Immerse

Color/versions/0.3.1/requires, Color/versions/0.3.10/requires, Color/versions/0.3.11/requires, Color/versions/0.3.12/requires, Color/versions/0.3.13/requires, Color/versions/0.3.14/requires, Color/versions/0.3.15/requires, Color/versions/0.3.3/requires, Color/versions/0.3.4/requires, Color/versions/0.3.5/requires, Color/versions/0.3.6/requires, Color/versions/0.3.7/requires, Color/versions/0.3.8/requires, Color/versions/0.3.9/requires, Color/versions/0.4.0/requires, Color/versions/0.4.1/requires, Color/versions/0.4.2/requires, Color/versions/0.4.3/requires, Color/versions/0.4.4/requires, Color/versions/0.4.5/requires, Color/versions/0.4.6/requires, Color/versions/0.4.7/requires, Color/versions/0.4.8/requires
Fixes https://github.com/JuliaLang/Color.jl/issues/107
=> Add upper limit to FixedPointNumbers for Color

LightGraphs/versions/0.3.6/requires, LightGraphs/versions/0.3.6/sha1
=> Tag LightGraphs v0.3.6

QuartzImageIO/versions/0.1.0/requires, QuartzImageIO/versions/0.1.0/sha1
Bump minor version because we're closing support for Julia 0.3
=> Tag QuartzImageIO v0.1.0

CPLEX/versions/0.0.18/requires, CPLEX/versions/0.0.18/sha1
Deprecation fixes. Closes https://github.com/JuliaOpt/CPLEX.jl/issues/56
CC @joehuchette
=> Tag CPLEX v0.0.18

Meddle/url, Morsel/url, SMTPClient/url, Soundex/url, Trie/url
* Meddle
* Morsel
* SMTPClient
* Soundex
* Trie
=> Send some packages to the archive

GitHub/url, GitHub/versions/1.0.3/requires, GitHub/versions/1.0.3/sha1
As discussed [here](https://github.com/JuliaWeb/GitHub.jl/pull/39#discussion_r44152036)
=> Tag GitHub v1.0.3 and update repo location

OptimPack/versions/0.2.0/requires, OptimPack/versions/0.2.0/sha1
This version has been updated to work with Julia 0.4
=> OptimPack v0.2.0

CovarianceMatrices/versions/0.0.4/requires, CovarianceMatrices/versions/0.0.4/sha1
Bug fixes, improved coverage and update CI testing.
=> CovarianceMatrices v0.0.4

NearestNeighbors/versions/0.0.2/requires, NearestNeighbors/versions/0.0.2/sha1
- Add ability to store data and tree separately, https://github.com/KristofferC/NearestNeighbors.jl/pull/6
- Minor fixes
=> Tag NearestNeighbors v0.0.2

JuMP/versions/0.11.1/requires, JuMP/versions/0.11.1/sha1
=> Tag JuMP v0.11.1

Mosek/versions/0.1.2/requires
Closes https://github.com/JuliaOpt/Mosek.jl/issues/66
CC @ulfworsoe
=> fix Mosek requires

JavaCall/versions/0.3.4/requires, JavaCall/versions/0.3.4/sha1
Make tests less brittle
Add field access
=> Tag JavaCall v0.3.4

EvolvingGraphs/versions/0.0.9/requires, EvolvingGraphs/versions/0.0.9/sha1
v0.0.9
---------
Fix test failing on Julia v0.3.
=> Tag EvolvingGraphs v0.0.9

FredData/url, FredData/versions/0.1.0/requires, FredData/versions/0.1.0/sha1
FredData is a package to pull economic data from Federal Reserve Economic Data (FRED).
=> Register FredData: v0.1.0

AmplNLWriter/versions/0.1.0/requires, AmplNLWriter/versions/0.1.0/sha1
=> Tag AmplNLWriter v0.1.0

MixedModels/versions/0.4.4/requires, MixedModels/versions/0.4.4/sha1
Added extractors for the random effects and ordering of the random-effects terms.
=> Tag MixedModels v0.4.4

ECOS/versions/0.6.1/requires, ECOS/versions/0.6.1/sha1
Minor update to help with development of https://github.com/mlubin/cmpb
=> Tag ECOS v0.6.1

ArcadeLearningEnvironment/url
Disregard previous pull request (a few weeks ago).
=> Register ArcadeLearningEnvironment

DualNumbers/versions/0.2.0/requires, DualNumbers/versions/0.2.0/sha1
CC @MikaelSlevinsky @dlfivefifty @jrevels
=> Tag DualNumbers v0.2.0

OpenStreetMap/versions/0.8.2/requires, OpenStreetMap/versions/0.8.2/sha1
Long overdue compatibility fixes for Julia 0.4
=> Tag OpenStreetMap v0.8.2

ReverseDiffSparse/versions/0.4.0/requires, ReverseDiffSparse/versions/0.4.0/sha1
Complete, 100% breaking rewrite from https://github.com/mlubin/ReverseDiffSparse2.jl. Thanks to @yuyichao for help merging the two repos. Ref https://github.com/JuliaOpt/JuMP.jl/pull/638
CC @IainNZ @joehuchette
=> Tag ReverseDiffSparse v0.4.0

IniFile/versions/0.2.5/requires, IniFile/versions/0.2.5/sha1
Fix v0.4 deprecation warnings.
=> Tag IniFile v0.2.5

JuliaParser/versions/0.6.4/requires, WoodburyMatrices/versions/0.1.3/requires
please don't tag broken versions
=> adjust requirements on most recent juliaparser tag

Mosek/versions/0.3.0/requires, Mosek/versions/0.3.0/sha1
Compatibility with breaking changes in MathProgBase 0.4.0.
=> Tag Mosek v0.3.0

ClassicalCiphers/versions/0.2.0/requires, ClassicalCiphers/versions/0.2.0/sha1
Collection of new ciphers implemented.
=> Tag ClassicalCiphers v0.2.0

NKLandscapes/versions/0.2.0/requires, NKLandscapes/versions/0.2.0/sha1
Some updates to the package, adds several new features, cleans up some existing code, expands test coverage, and addresses several bugs.
=> Tag NKLandscapes v0.2.0

ValueOrientedRiskManagementInsurance/versions/0.0.2/requires, ValueOrientedRiskManagementInsurance/versions/0.0.2/sha1
Added branch for the 2nd edition of the German version of the book
=> Tag ValueOrientedRiskManagementInsurance v0.0.2

Roots/versions/0.1.25/requires, Roots/versions/0.1.25/sha1
=> Tag Roots v0.1.25

WoodburyMatrices/versions/0.1.5/requires, WoodburyMatrices/versions/0.1.5/sha1
This is needed to merge tlycken/Interpolations.jl#104
=> Tag WoodburyMatrices v0.1.5

Actors/url, Actors/versions/0.0.1/requires, Actors/versions/0.0.1/sha1
New package [Actors.jl](https://github.com/daqcore/Actors.jl).
A Julia implementation of the Actor Model, based on Julia Tasks. Currently, only very basic functionality is implemented. This is likely to end up as something of a hybrid between Erlang- and Scala/Akka-style actors.
=> Register Actors

SymPy/versions/0.2.37/requires, SymPy/versions/0.2.37/sha1
add `ivpsolve` for solving ODEs with initial condition(s).
=> Tag SymPy v0.2.37

Ipopt/versions/0.2.1/requires, Ipopt/versions/0.2.1/sha1
=> Tag Ipopt v0.2.1

FusionDirect/versions/0.1.2/requires, FusionDirect/versions/0.1.2/sha1
This new minor revision of FusionDirect provides more accurate fusion detection
=> Tag FusionDirect v0.1.2

PlanOut/url, PlanOut/versions/0.1.0/requires, PlanOut/versions/0.1.0/sha1
=> add planout package

MelGeneralizedCepstrums/versions/0.0.2/requires, MelGeneralizedCepstrums/versions/0.0.2/sha1, SynthesisFilters/versions/0.0.2/requires, SynthesisFilters/versions/0.0.2/sha1, WORLD/versions/0.2.1/requires, WORLD/versions/0.2.1/sha1
Patch releases: fix deprecations on the Julia master
=> Tag WORLD v0.2.1, SynthesisFilters v0.0.2, MelGeneralizedCepstrums v0.0.2

Mocha/versions/0.1.1/requires, Mocha/versions/0.1.1/sha1
* Infrastructure
* Fix compatability with Julia v0.5 nightly
* Fix blasfunc compatibility (@elehcim)
* Improved computation performance for neurons on CPU backend (@uschmidt83)
=> Tag Mocha v0.1.1

Spectra/url, Spectra/versions/0.0.1/requires, Spectra/versions/0.0.1/sha1, SpectraJu/url
Registration of Spectra.jl
Created a new branch to avoid any trouble with the old pull request.
=> Pull request/1fb03976

SignalView/url, SignalView/versions/0.0.1/requires, SignalView/versions/0.0.1/sha1
Neat tool for visualising and interacting with Reactives signal graph.
It's based on GLVisualize, so no tests/coverage yet :(
=> register SignalView

EllipticFEM/url, EllipticFEM/versions/0.0.1/requires, EllipticFEM/versions/0.0.1/sha1
This package provides a finite element method to solve elliptic partial differential equations.
One important fact is that the assembly of the stiffness matrix is faster than the similar code in MATLAB.
For further information please see the README.
=> Register EllipticFEM.jl

ECOS/versions/0.6.2/requires, ECOS/versions/0.6.2/sha1, SCS/versions/0.2.1/requires, SCS/versions/0.2.1/sha1
Fix windows download links, cc @mlubin
=> Tag ECOS and SCS

NormalizeQuantiles/versions/0.0.9/requires, NormalizeQuantiles/versions/0.0.9/sha1
exported helper function sampleRanks
=> Tag NormalizeQuantiles v0.0.9

GLPKMathProgInterface/versions/0.2.1/requires, GLPKMathProgInterface/versions/0.2.1/sha1
Various fixes for callback behavior.
CC @emreyamangil
=> Tag GLPKMathProgInterface v0.2.1

Swifter/url, Swifter/versions/0.0.1/requires, Swifter/versions/0.0.1/sha1
This is a prototype to interact with iOS application that using Swift.
Although, Swift has a REPL system, but that's not useful than Julia REPL.
This is not to call Swift functions directly (like PyCall),
This is for Server side using Swift and Client side using Julia script/REPL.
https://github.com/wookay/Swifter.jl
=> Register Swifter 

ScikitLearn/versions/0.0.2/requires, ScikitLearn/versions/0.0.2/sha1
Travis uncovered a missing dependency
=> Tag ScikitLearn v0.0.2

ReverseDiffSource/versions/0.2.2/requires, ReverseDiffSource/versions/0.2.2/sha1
Adds a option to exclude some variables from derivation.
=> Tag ReverseDiffSource v0.2.2

Rsvg/url, Rsvg/versions/0.0.1/requires, Rsvg/versions/0.0.1/sha1
should now contain the necessary actions in single commit.
=> Register Rsvg and Tag

Pajarito/url, Pajarito/versions/0.1.0/requires, Pajarito/versions/0.1.0/sha1
A solver for mixed-integer convex programming. Documented at http://arxiv.org/abs/1511.06710
CC @IainNZ @joehuchette @chriscoey @emreyamangil @madeleineudell @juan-pablo-vielma @SteveDiamond @ajfriend @mcg1969 @tiagoakle @poulson @bodono @adomahidi @tkelman
=> Register Pajarito

SimJulia/versions/0.3.11/requires, SimJulia/versions/0.3.11/sha1
Make all examples work on Julia v0.5
=> Tag SimJulia v0.3.11 [git://github.com/BenLauwens/SimJulia.jl.git]

JuliaParser/versions/0.7.1/requires, JuliaParser/versions/0.7.1/sha1
=> Tag JuliaParser v0.7.1 [https://github.com/JuliaLang/JuliaParser.jl]

TaylorSeries/url, TaylorSeries/versions/0.1.2/requires, TaylorSeries/versions/0.1.2/sha1
This will be the last version compatible with Julia 0.3.
=> Tag TaylorSeries v0.1.2

ConfParser/url, HexEdit/url, NMEA/url, Pcap/url
Changed my github user so I changed the url's to match.  Thanks!
=> changed package urls to match path for new github username

ElasticFDA/versions/0.3.2/requires, ElasticFDA/versions/0.3.2/sha1
Bug fixes to ElasticFDA, release v0.3.2
=> Tag ElasticFDA v0.3.2

LightGraphs/versions/0.5.3/requires, LightGraphs/versions/0.5.3/sha1
Lots of new functionality added, and some dependencies removed (thanks, @carlolucibello)
=> Tag LightGraphs v0.5.3

Blosc/versions/0.1.5/requires, Blosc/versions/0.1.5/sha1
=> Tag Blosc v0.1.5 [git://github.com/stevengj/Blosc.jl.git]

RCall/versions/0.4.1/requires, RCall/versions/0.4.1/sha1
=> Tag RCall v0.4.1

NamedArrays/versions/0.4.8/requires, NamedArrays/versions/0.4.8/sha1
Add keywords for `sort()` and other small changes.
=> Tag NamedArrays v0.4.8

PATHSolver/versions/0.0.4/requires, PATHSolver/versions/0.0.4/sha1
=> Tag PATHSolver v0.0.4

Swifter/versions/0.0.5/requires, Swifter/versions/0.0.5/sha1
I'm getting ready to release
* query among devices
* added jupyter notebooks
- [UIControls.ipynb](https://github.com/wookay/AppConsole/blob/master/notebooks/UIControls.ipynb)
- [MultipleDevices.ipynb](https://github.com/wookay/AppConsole/blob/master/notebooks/MultipleDevices.ipynb)
Thanks.
=> Tag Swifter v0.0.5

ODBC/versions/0.4.0/requires, ODBC/versions/0.4.0/sha1
Please hold on merging until later. I want to craft an ANN post for julia-users as this is a major breaking change release.
=> New version bump for ODBC

Rotations/url, Rotations/versions/0.0.1/requires, Rotations/versions/0.0.1/sha1, Rotations/versions/0.1.0/requires, Rotations/versions/0.1.0/sha1
Pull request to add a rotations package for handling 3D rotation parametrizations and conversions between them.
Parametrizations included are:
rotation matrices
quaternions
angle axis representations
stereographic quaternion projections (a 3 parameter representation of a unit quaternion)
Euler angles (Tait-Bryan ordering e.g. XYZ)
proper Euler angles (proper euler ordering e.g. XYX)
=> Register Rotations: v0.0.1, v0.1.0

StatsFuns/versions/0.2.2/requires, StatsFuns/versions/0.2.2/sha1
Fixes possible error with too old Compat.
Cc: @andreasnoack
=> Tag StatsFuns v0.2.2

Mads/versions/0.1.12/requires, Mads/versions/0.1.12/sha1
tests improved; packages removed.
=> Tag Mads v0.1.12

Spectra/versions/0.0.2/requires, Spectra/versions/0.0.2/sha1
Updated Spectra.jl package, with planning new functions using new requirements. Docs have been added compared to 0.0.1.
=> Tag Spectra v0.0.2

ValidatedNumerics/versions/0.4.3/requires, ValidatedNumerics/versions/0.4.3/sha1
=> Tag ValidatedNumerics v0.4.3

KernelDensity/versions/0.1.2/requires, LsqFit/versions/0.0.2/requires, Mads/versions/0.1.12/requires
ref https://github.com/JuliaOpt/Optim.jl/issues/217
The limit wasn't necessary on the newest version, but I'll leave it for the older versions, as I'm not sure.
=> Limit was not necessary.

Mads/versions/0.1.12/requires
ref: https://github.com/JuliaLang/METADATA.jl/pull/5341 and https://github.com/madsjulia/Mads.jl/pull/2
=> Reinstate Optim req in Mads

OpenGene/versions/0.1.9/requires, OpenGene/versions/0.1.9/sha1
This new minor revision of OpenGene provides some fixes for Julia v0.5, and some new functions for OpenGene operations.
=> Tag OpenGene v0.1.9

Conda/versions/0.2.1/requires, Conda/versions/0.2.1/sha1
See https://github.com/Luthaf/Conda.jl/issues/34 for the solved issue.
I had to submit this by hand, because `PkgDev.publish()` segfaulted for me.
=> Tag Conda v0.2.1 [git://github.com/Luthaf/Conda.jl.git]

Currencies/url
Currencies.jl has moved to https://github.com/JuliaFinance/Currencies.jl.
=> Move Currencies.jl to JuliaFinance

AstroLib/url
The project has been moved to JuliaAstro.
=> Update url of AstroLib

MLBase/versions/0.5.3/requires, MLBase/versions/0.5.3/sha1
@tkelman and @jiahao,  here is MLBase v0.5.3. Let me know if I need to change anything.
=> release MLBase v0.5.3

LibArchive/versions/0.0.2/requires, LibArchive/versions/0.0.2/sha1
[LibArchive.jl](https://github.com/yuyichao/LibArchive.jl)
* Fix depwarns.
* Unify `Reader` and `Writer` constructors.
* `do` syntax support.
* Better read/write support on 0.5
=> Tag LibArchive v0.0.2

IntervalLinearEquations/url, IntervalLinearEquations/versions/0.2.0/requires, IntervalLinearEquations/versions/0.2.0/sha1
Julia package to solve system of linear equations:
Changes from the previous PR:
- travis is configured;
- the readme is extended;
- the package is renamed (old name was ILESolver).
=> Register IntervalLinearEquations: v0.1.0, v0.1.1, v0.1.2, v0.1.3, v0.2.0

TimeZones/versions/0.1.2/requires, TimeZones/versions/0.2.0/requires
Fixing https://github.com/JuliaLang/METADATA.jl/pull/5509#issuecomment-230092889
=> Setting upper bounds on Mocking dependency

Swifter/versions/0.0.8/requires, Swifter/versions/0.0.8/sha1
code was updated during JuliaCon 2016
- displaying array of UIViews on jupyter notebook
- added Compat in requires
thanks.
=> Tag Swifter v0.0.8

ToeplitzMatrices/url
=> Update ToeplitzMatrices url

Mads/versions/0.1.16/requires, Mads/versions/0.1.16/sha1
Various fixes and improvements.
=> Tag Mads v0.1.16

HyperDualNumbers/versions/0.1.8/requires, HyperDualNumbers/versions/0.1.8/sha1, HyperDualNumbers/versions/1.0.0/requires, HyperDualNumbers/versions/1.0.0/sha1
Include Edwin’s fixes for asin, acos and atan.
=> Bump HyperDualNumbers to v1.0.0

DataFramesMeta/versions/0.1.2/requires, DataFramesMeta/versions/0.1.2/sha1
~~This has my Primes tag in here too but I'll try to do some Git magic to remove that since I also have #5604. (The operative word here being "try.")~~ fixed
=> Tag DataFramesMeta v0.1.2

InspectDR/versions/0.0.6/requires, InspectDR/versions/0.0.6/sha1
Improved tick labels.  Finally migrated formatting code to use NumericIO.
=> Tag InspectDR v0.0.6

LightGraphs/versions/0.6.1/requires, LightGraphs/versions/0.6.1/sha1
Fixes pkg testing by adding Clp to test/REQUIRE.
=> Tag LightGraphs v0.6.1

Hiccup/versions/0.0.3/requires, Hiccup/versions/0.0.3/sha1
Fixes https://github.com/JunoLab/Hiccup.jl/issues/17
=> Tag Hiccup v0.0.3

Measures/versions/0.0.3/requires
please be more careful with these things @shashi and @ranjanan
=> add missing Compat requirement to Measures 0.0.3

DataFramesMeta/versions/0.1.3/requires, DataFramesMeta/versions/0.1.3/sha1
Now with 0.5 suppport 🎆 0️⃣5️⃣
=> Tag DataFramesMeta v0.1.3

MeCab/versions/0.1.7/requires, MeCab/versions/0.1.7/sha1
I'd like to release MeCab.jl v0.1.7
=> Tag MeCab v0.1.7

CompEcon/url, CompEcon/versions/0.1.0/requires, CompEcon/versions/0.1.0/sha1
Ref: https://github.com/spencerlyon2/CompEcon.jl/issues/26
=> Pull request/cc84bca0

GenericSVD/versions/0.0.2/requires, GenericSVD/versions/0.0.2/sha1
=> Tag GenericSVD v0.0.2

WinReg/versions/0.1.1/requires, WinReg/versions/0.1.1/sha1
=> Tag WinReg v0.1.1

CoinOptServices/versions/0.1.2/requires, CoinOptServices/versions/0.1.2/sha1
Works on 0.5.
CC @tkelman @JackDunnNZ
=> Tag CoinOptServices v0.1.2 

LogParser/versions/0.3.0/requires, LogParser/versions/0.3.0/sha1
I intentionally made this `julia 0.5` instead of `julia 0.5-`, as I don't want to have to do another PR just to switch it in a few weeks.
=> Tag LogParser v0.3.0

ExcelReaders/versions/0.6.0/requires, ExcelReaders/versions/0.6.0/sha1
=> Pull request/43cc9db2

SimJulia/versions/0.3.14/requires, SimJulia/versions/0.3.14/sha1
Maintenance release
Use dirname(@__FILE__) instead of Pkg.dir as proposed by @tkelman
=> Tag SimJulia v0.3.14

NormalizeQuantiles/versions/0.1.2/requires, NormalizeQuantiles/versions/0.1.2/sha1
Documentation reformated and added.
Some minor code cleanups.
=> Tag NormalizeQuantiles v0.1.2

HttpServer/versions/0.1.6/requires, HttpServer/versions/0.1.6/sha1
Closes https://github.com/JuliaWeb/HttpServer.jl/issues/100
=> Tag HttpServer v0.1.6 [https://github.com/JuliaWeb/HttpServer.jl]

Geodesy/versions/0.1.0/requires, Geodesy/versions/0.2.0/requires, Geodesy/versions/0.2.0/sha1
Includes an additional tweak to the 0.1.0 REQUIRE to fix some interdependency problems with CoordinateTransformations, see #5953 
@andyferris @awbsmith
=> Tag geodesy 0.2.0

MathProgBase/versions/0.5.3/requires, MathProgBase/versions/0.5.3/sha1
=> Tag MathProgBase v0.5.3

DSGE/versions/0.1.2/requires, DSGE/versions/0.1.3/requires
xref to fix in DSGE.jl: https://github.com/FRBNY-DSGE/DSGE.jl/pull/6
xref to discussion #5957
=> Put upper limit on Optim

Spectra/versions/0.1.5/requires, Spectra/versions/0.1.5/sha1
Removing gcvpsl.o and adding the documentation on the RamEau function
=> Tag Spectra v0.1.5

CxxWrap/versions/0.1.6/requires, CxxWrap/versions/0.1.6/sha1
Bugfixes and new features following reports by @jstrube
=> Tag CxxWrap v0.1.6

RouletteWheels/versions/0.0.6/requires, RouletteWheels/versions/0.0.6/sha1
A [compat update](https://github.com/jbn/RouletteWheels.jl/pull/2) from @tkelman.
=> Tag RouletteWheels v0.0.6

JDBC/versions/0.1.0/requires, JDBC/versions/0.1.0/sha1
=> Tag JDBC v0.1.0

FileIO/versions/0.1.1/requires, FileIO/versions/0.1.1/sha1
Fixes `del_format` when magic bytes are generated by a function (@JohnHBrock)
CC @ssfrr.
=> Tag FileIO v0.1.1 [https://github.com/JuliaIO/FileIO.jl]

LearnBase/url, LearnBase/versions/0.0.1/requires, LearnBase/versions/0.0.1/sha1
https://github.com/JuliaML/LearnBase.jl/
We over at [JuliaML](https://github.com/JuliaML) have been throwing our heads together for some time now and feel like this package is now ready be proposed to METADATA. The package itself is quite small, but provides the abstractions that we build on in various other packages we are developing.
To not come here with empty promises that we will need these abstraction "one day", we first wanted to implement at least one full package that builds on these abstractions, and also represents a community effort to create something that works for all of us involved in its creation (Which I dare say I am very excited about!).
- check it out if you want!: [JuliaML/Losses.jl](https://github.com/JuliaML/Losses.jl) (it depends on LearnBase, which is why the CI …
=> Register and Tag LearnBase.jl

BinDeps/versions/0.4.3/requires, BinDeps/versions/0.4.3/sha1
closes https://github.com/JuliaLang/BinDeps.jl/issues/242, deprecation warning fix
=> Tag BinDeps v0.4.3

Yeppp/versions/0.1.0/requires, Yeppp/versions/0.1.0/sha1
=> Tag Yeppp v0.1.0

AppleAccelerate/url, ODE/url, Roots/url, Sundials/url, WinRPM/url
to other organizations
(There's a script at `.test/update-redirects.jl` that does this which I run periodically.)
=> Update URL's for packages that were just moved

RData/versions/0.0.4/requires, RData/versions/0.0.4/sha1
=> Tag RData v0.0.4 [https://github.com/JuliaStats/RData.jl]

AWS/url, Combinatorics/url, Graphs/url, IterativeSolvers/url, MATLAB/url, VML/url, Yeppp/url
(populated by `.test/update-redirects.jl`)
=> More moved package url updates

GraphCentrality/versions/0.0.1/requires, GraphCentrality/versions/0.1.0/requires
Per https://github.com/JuliaGraphs/GraphCentrality.jl/issues/2
=> deprecate GraphCentrality

SymEngine/url, SymEngine/versions/0.1.0/requires, SymEngine/versions/0.1.0/sha1
[SymEngine.jl](https://github.com/symengine/SymEngine.jl) provides wrappers for [SymEngine](https://github.com/symengine/symengine), a symbolic manipulation library.
=> SymEngine.jl

Languages/versions/0.1.0/requires, Languages/versions/0.1.0/sha1
cc: @johnmyleswhite 
I'll tag TextAnalysis once this is done.
=> Tag Languages v0.1.0

BufferedStreams/versions/0.2.0/requires, BufferedStreams/versions/0.2.0/sha1
* Renaming a function (thanks to @simonster).
* A minor bug fix.
=> Tag BufferedStreams v0.2.0

MIToS/versions/1.2.0/requires, MIToS/versions/1.2.0/sha1
This solves https://github.com/diegozea/MIToS.jl/issues/32 and the `swap!` problem with `FixedSizeArrays`
Thanks!
=> Tag MIToS v1.2.0

ExtremelyRandomizedTrees/versions/0.0.10/requires, ExtremelyRandomizedTrees/versions/0.0.11/requires, ExtremelyRandomizedTrees/versions/0.0.3/requires, ExtremelyRandomizedTrees/versions/0.0.4/requires, ExtremelyRandomizedTrees/versions/0.0.5/requires, ExtremelyRandomizedTrees/versions/0.0.6/requires, ExtremelyRandomizedTrees/versions/0.0.7/requires, ExtremelyRandomizedTrees/versions/0.0.8/requires, ExtremelyRandomizedTrees/versions/0.0.9/requires, ExtremelyRandomizedTrees/versions/0.1.0/requires, InformedDifferentialEvolution/versions/0.0.2/requires, InformedDifferentialEvolution/versions/0.0.3/requires, InformedDifferentialEvolution/versions/0.0.4/requires, InformedDifferentialEvolution/versions/0.1.0/requires, KShiftsClustering/versions/0.0.1/requires, KShiftsClustering/versions/0.0.2/requires, KShiftsClustering/versions/0.0.3/requires, KShiftsClustering/versions/0.1.0/requires
By adding appropriate upper bounds, cc @rened and ref https://github.com/JuliaLang/METADATA.jl/pull/6108#issuecomment-242756426
=> Fix breakage in 3 packages due to FunctionalData 0.1.2

TikzPictures/versions/0.3.5/requires, TikzPictures/versions/0.3.5/sha1
Fixed issue with error messages for texlive 2016 and address issue with testing when lualatex is not present.
=> Tag TikzPictures v0.3.5

MixedModels/versions/0.5.7/requires, MixedModels/versions/0.5.7/sha1
Last tagged version of the package to support julia-0.4.x
=> Tag MixedModels v0.5.7

WordNet/versions/0.1.0/requires, WordNet/versions/0.1.0/sha1
Adds sensekey support (contribution by @oxinabox)
=> Tag WordNet v0.0.2

FastTransforms/versions/0.0.6/requires, FastTransforms/versions/0.0.6/sha1
=> Tag FastTransforms v0.0.6

ApproxFun/versions/0.3.2/requires, ApproxFun/versions/0.3.2/sha1
=> Tag ApproxFun v0.3.2

.test/check-pr.jl
This should fix the failure in #6510.
cc @tkelman and @fcard
=> Only check changes to version files

.test/check-pr.jl
Addresses the issue noted in #6515.
=> Select the appropriate SHA from git ls-remote

.test/METADATA.jl
cc @ararslan this needs a lot more testing on your fork
=> disable the tag check for now

Plotly/versions/0.1.1/requires, Plotly/versions/0.1.1/sha1
Makes `Requests.post(::PlotlyJS.SyncPlot)` match API for `Requests.post(::PlotlyJS.Plot)`
=> Tag Plotly v0.1.1 [https://github.com/plotly/Plotly.jl]

.test/METADATA.jl, .test/check-pr.jl
Maybe one of these times won't be a complete failure.
=> Reenable and refix tag checking

RandomMatrices/versions/0.2.1/requires, RandomMatrices/versions/0.2.1/sha1
=> Tag RandomMatrices v0.2.1 [https://github.com/jiahao/RandomMatrices.jl]

NRRD/versions/0.1.0/requires, NRRD/versions/0.1.0/sha1
All work by @tlnagy:
- Fix 0.5 issues
- Update README/REQUIRE for new julia version
- Transition from ZLib->LibZ
=> Tag NRRD v0.1.0

FileIO/versions/0.1.3/requires, FileIO/versions/0.1.3/sha1
Changes:
- add missing BigTIFF magic bytes (@romainFr)
- prevent StackOverflow if `load`/`save` is not defined by a module (@timholy)
=> Tag FileIO v0.1.3 [https://github.com/JuliaIO/FileIO.jl]

Gadfly/versions/0.5.1/requires, Gadfly/versions/0.5.1/sha1
=> Tag Gadfly v0.5.1 [https://github.com/dcjones/Gadfly.jl]

CDDLib/versions/0.0.1/requires, CDDLib/versions/0.1.0/requires
@tkelman Thanks for the heads up :)
=> Update requirements for CDDLib

GeneralizedSchurAlgorithm/versions/0.0.2/requires, GeneralizedSchurAlgorithm/versions/0.0.2/sha1
[https://github.com/KTH-AC/GeneralizedSchurAlgorithm.jl]
=> Tag GeneralizedSchurAlgorithm v0.0.2

ROCAnalysis/versions/0.1.0/requires, ROCAnalysis/versions/0.1.0/sha1
Dropping support for julia-0.3
=> Tag ROCAnalysis v0.1.0 [https://github.com/davidavdav/ROCAnalysis.jl]

Fontconfig/versions/0.1.1/requires, Fontconfig/versions/0.1.1/sha1
- Fixes build on Windows, thanks to @jmcastro2109 for helping me figure this out
=> Tag Fontconfig v0.1.1

PlotThemes/url, PlotThemes/versions/0.0.1/requires, PlotThemes/versions/0.0.1/sha1
https://github.com/JuliaPlots/PlotThemes.jl: v0.0.1
cc: @pkofod
=> Register PlotThemes

mPulseAPI/versions/1.0.1/requires, mPulseAPI/versions/1.0.1/sha1
1.0.1 Fixes a bug with handling international characters in the API response.
=> Tag mPulseAPI v1.0.1

LombScargle/versions/0.1.2/requires, LombScargle/versions/0.1.2/sha1
From `NEWS.md` file:
> ### New Features ###
> 
> * New function for performing bootstrap resampling: `LombScargle.bootstrap`.
>   The `fap` and `fapinv` functions have now new methods to estimate false-alarm
>   probability and its inverse from a bootstrap sample.
> * New utilities: `period`, `periodpower`, `findmaxperiod`.
> 
> ### Bug Fixes ###
> 
> * Fix power in the standard (i.e., `fast = false` variant) generalised
>   Lomb–Scargle algorithm with `fit_mean = true`.  You will find different
>   results than before, but for the better, previous results were slightly wrong.
=> Tag LombScargle v0.1.2

Rmath/versions/0.1.4/requires, Rmath/versions/0.1.4/sha1
As requested by @tkelman in https://github.com/JuliaStats/Rmath.jl/pull/22#issuecomment-254690861
=> Tag Rmath v0.1.4 [https://github.com/JuliaStats/Rmath.jl]

PGFPlots/versions/1.4.2/requires, PGFPlots/versions/1.4.2/sha1
Added Patch2D plot type - updated docs.
=> Tag PGFPlots v1.4.2

MixedModels/versions/0.6.1/requires, MixedModels/versions/0.6.1/sha1
Expand signatures on some methods, resulting in substantial speed increase on some models.
=> Tag MixedModels v0.6.1 [https://github.com/dmbates/MixedModels.jl]

Suppressor/versions/0.0.4/requires, Suppressor/versions/0.0.4/sha1
Test in v0.4.7 also.                                                                                                                         
* now compatible with Julia v0.4                                                                                                                      
* Add v0.4.7 to AppVeyor test matrix.                                                                                                                 
* Add v0.4.7 to Travis CI test matrix.
=> Tag Suppressor v0.0.4 [https://github.com/Ismael-VC/Suppressor.jl]

mPulseAPI/versions/1.0.3/requires, mPulseAPI/versions/1.0.3/sha1
Make SOASTA Endpoint configurable
=> Tag mPulseAPI v1.0.3

DifferentialEquations/versions/0.5.0/requires, DifferentialEquations/versions/0.5.0/sha1
This is the pre-modularization tag for [DifferentialEquations.jl](https://github.com/JuliaDiffEq/DifferentialEquations.jl). However, it is a minor tag because there are many feature which were added, including (but likely not limited to):
- A benchmarking suite (which shows [order of magnitude speedups for the ODE algorithms over ODE.jl](https://github.com/JuliaDiffEq/DifferentialEquations.jl/tree/master/benchmarks))
- [High order interpolations for every optimized Runge-Kutta method (ranging from 3 to 9 on 10? algorithms, with a default of 3 on all other 100+ ODE algorithms, including the ODE.jl wrapped algorithms)](http://juliadiffeq.github.io/DifferentialEquations.jl/stable/solvers/ode_solve.html)
- Overloaded calls so the [solution object acts both like an array and the interpolation …
=> Tag DifferentialEquations v0.5.0

ZipFile/versions/0.3.0/requires, ZipFile/versions/0.3.0/sha1
update https://github.com/fhs/ZipFile.jl/issues/29
=> Tag ZipFile v0.3.0 [https://github.com/fhs/ZipFile.jl]

VoronoiDelaunay/versions/0.1.0/requires, VoronoiDelaunay/versions/0.1.0/sha1
Cf. <https://github.com/JuliaLang/METADATA.jl/pull/6828>
=> Tag VoronoiDelaunay v0.1.0

Mosek/versions/0.5.1/requires, Mosek/versions/0.5.1/sha1
@ulfworsoe, no explosions needed
CC @chriscoey
=> Tag Mosek v0.5.1 [https://github.com/JuliaOpt/Mosek.jl]

DiffEqParamEstim/url, DiffEqParamEstim/versions/0.0.1/requires, DiffEqParamEstim/versions/0.0.1/sha1
=> Register DiffEqParamEstim

Weave/versions/0.2.1/requires, Weave/versions/0.2.1/sha1
I hope this is finally correct. Thanks for help @tkelman!
=> Tag Weave v0.2.1 [https://github.com/mpastell/Weave.jl]

PowerModels/versions/0.2.2/requires
Per @tkelman's request in #7000
=> Updating PowerModels v0.2.2 requires

SimpleTraits/versions/0.2.0/requires, SimpleTraits/versions/0.2.0/sha1
- dropped Julia 0.4
- new features, see https://github.com/mauro3/SimpleTraits.jl/blob/master/NEWS.md
=> Tag SimpleTraits v0.2.0 [https://github.com/mauro3/SimpleTraits.jl]

PGFPlots/versions/1.4.3/requires, PGFPlots/versions/1.4.3/sha1
Added some Reel compatibility and allows use of contour with provided data.
=> Tag PGFPlots v1.4.3

UnicodePlots/versions/0.2.2/requires, UnicodePlots/versions/0.2.2/sha1
- small fix for deprecation warning
=> Tag UnicodePlots v0.2.2 [https://github.com/Evizero/UnicodePlots.jl]

Mosek/versions/0.6.0/requires, Mosek/versions/0.6.0/sha1
Disable support for MOSEK 7.1 and earlier. Improve re-build functionality.
=> update MOSEK version

DiffEqProblemLibrary/versions/0.3.1/requires, DiffEqProblemLibrary/versions/0.3.1/sha1
This is a small tag that fixes a bug for tests to pass in other areas of the ecosystem.
=> Tag DiffEqProblemLibrary v0.3.1 [https://github.com/JuliaDiffEq/DiffEqProblemLibrary.jl]

ForecastEval/url, ForecastEval/versions/0.0.1/requires, ForecastEval/versions/0.0.1/sha1
Register new package FoecastEval
=> Register ForecastEval package

PlotlyJS/versions/0.5.2/requires, PlotlyJS/versions/0.5.2/sha1
More robust interactions with blink and saving figures from any frontend.
=> Tag PlotlyJS v0.5.2 [https://github.com/spencerlyon2/PlotlyJS.jl]

TikzGraphs/versions/0.3.0/requires, TikzGraphs/versions/0.3.0/sha1
- Cleaner implementations
- Can now specify node styles
- Can specify the styles of specific nodes
=> Tag TikzGraphs v0.3.0

PyAMG/versions/0.0.8/requires, PyAMG/versions/0.0.8/sha1
minor update to make `\` more useful.
=> Tag PyAMG v0.0.8 [https://github.com/cortner/PyAMG.jl]

AlgebraicDiffEq/url, ApproxFun/url, CDDLib/url, DASSL/url, Fontconfig/url, Hexagons/url, Interact/url, JPLEphemeris/url, LRSLib/url, Loess/url, Measures/url, Options/url, Polyhedra/url, Reactive/url, SingularIntegralEquations/url, ZMQ/url
from running .test/update-redirects.jl
cc @ChrisRackauckas 
@dlfivefifty 
@blegat 
@pwl 
@shashi 
@helgee 
Don't forget to re-enable CI services after moving a repo.
=> url redirects for various moved packages

Recommendation/url, Recommendation/versions/0.0.1/requires, Recommendation/versions/0.0.1/sha1
Repository: [takuti/Recommendation.jl](https://github.com/takuti/Recommendation.jl)
Release: [v0.0.1](https://github.com/takuti/Recommendation.jl/releases/tag/v0.0.1)
Travis: [![Build Status](https://travis-ci.org/takuti/Recommendation.jl.svg?branch=master)](https://travis-ci.org/takuti/Recommendation.jl)
cc: @JeffreySarnoff
=> Register new package Recommendation.jl v0.0.1

Polynomials/versions/0.1.1/requires, Polynomials/versions/0.1.2/requires, Polynomials/versions/0.1.2/sha1
I think I did this right, but ended up doing several manual steps to fix a mistake. Sorry for any extra hassles.
=> Tag Polynomials v0.1.2 [https://github.com/Keno/Polynomials.jl]

JuliaWebAPI/versions/0.2.1/requires, JuliaWebAPI/versions/0.2.1/sha1
- support multipart/form-data
- allow a pre-processor for HTTP endpoints
- remove deprecation warnings
=> Tag JuliaWebAPI v0.2.1 [https://github.com/JuliaWeb/JuliaWebAPI.jl]

NLsolve/versions/0.9.1/requires, NLsolve/versions/0.9.1/sha1
cc @tkelman https://travis-ci.org/EconForge/NLsolve.jl/builds/189813498
=> Tag NLsolve v0.9.1 [https://github.com/EconForge/NLsolve.jl]

GLFW/versions/1.2.1/requires, GLFW/versions/1.2.1/sha1
Fix Homebrew installation on OS X.
=> Tag GLFW v1.2.1 [https://github.com/JuliaGL/GLFW.jl]

RationalFunctions/versions/0.0.2/requires, RationalFunctions/versions/0.0.2/sha1
Tagging [`RationalFunctions 0.0.2`](https://github.com/aytekinar/RationalFunctions.jl/releases).
Added
Sample plots for common platforms (as artifacts from unit tests) are also provided.
**Note.** Requires `Polynomials 0.1.2` (latest version as of now) due to the bugfix Keno/Polynomials.jl@b8a6bf4e.
=> Tag RationalFunctions

ACME/versions/0.1.0/requires, ACME/versions/0.1.1/requires
ACME 0.1.0 and 0.1.1 were broken by JuliaLang/julia#19595
=> Upper bound Julia version for past ACME versions

PowerModels/versions/0.1.0/requires, PowerModels/versions/0.2.0/requires, PowerModels/versions/0.2.1/requires, PowerModels/versions/0.2.2/requires, PowerModels/versions/0.2.3/requires, PowerModels/versions/0.2.3/sha1
- Added an upper bound on JuMP version as a quick fix for Julia 0.5 builds
- Added a few new features for Matpower file parsing (see CHANGELOG.md)
=> Tag PowerModels v0.2.3 [https://github.com/lanl-ansi/PowerModels.jl]

Gadfly/versions/0.5.3/requires, Gadfly/versions/0.5.3/sha1
* Support for size aesthetic for `Geom.point`
* Various doc improvements
* Improved Juno support
=> Tag Gadfly v0.5.3 [https://github.com/GiovineItalia/Gadfly.jl]

BlossomV/versions/0.2.1/requires, BlossomV/versions/0.2.1/sha1
=> Tag BlossomV v0.2.1 [https://github.com/mlewe/BlossomV.jl]

QML/versions/0.1.0/requires, QML/versions/0.2.0/requires, QML/versions/0.3.0/requires, QML/versions/0.3.0/sha1
=> Tag QML.jl v0.3.0 [https://github.com/barche/QML.jl/releases/tag/v0.3.0]

Temporal/versions/0.2.1/requires, Temporal/versions/0.2.1/sha1
Minor update with a change to the `show` method to allow `TS` objects to be shown with rows shown dynamically changed by the size of the window (as with most Julia base classes).
=> Tag Temporal v0.2.1 [https://github.com/dysonance/Temporal.jl]

ProtoBuf/versions/0.3.2/requires, ProtoBuf/versions/0.3.2/sha1
=> Tag ProtoBuf v0.3.2 [https://github.com/tanmaykm/ProtoBuf.jl/releases/tag/v0.3.2]

Weber/versions/0.3.2/requires, Weber/versions/0.3.2/sha1
Repository: [haberdashPI/Weber.jl](https://github.com/haberdashPI/Weber.jl)
Release: [v0.3.2](https://github.com/haberdashPI/Weber.jl/tree/v0.3.2)
TravisCI: [![Build Status](https://travis-ci.org/haberdashPI/Weber.jl.svg?branch=v0.3.2)](https://travis-ci.org/haberdashPI/Weber.jl)
AppVeyor: [![Build status](https://ci.appveyor.com/api/projects/status/uvxq5mqlq0p2ap02/branch/master?svg=true)](https://ci.appveyor.com/project/haberdashPI/weber-jl/branch/master)
=> Tag Weber v0.3.2 [https://github.com/haberdashPI/Weber.jl]

GslibIO/url, GslibIO/versions/0.0.1/requires, GslibIO/versions/0.0.1/sha1
@tkelman added the tag, thanks.
=> Register GslibIO [https://github.com/juliohm/GslibIO.jl.git]: v0.0.1

LossFunctions/versions/0.0.1/requires, LossFunctions/versions/0.0.2/requires
=> LossFunctions: upperbound LearnBase for old versions

MacroTools/versions/0.3.5/requires
closes https://github.com/JuliaLang/julia/issues/20581
ref #7903
replaces #7921
=> make MacroTools 0.3.5 julia-0.4-only

EllipticFEM/versions/0.0.2/requires, EllipticFEM/versions/0.0.2/sha1
I corrected a problem with the folder structure. Now the version should work fine.
=> Update EllipticFEM to version v0.0.2.

Temporal/versions/0.2.3/requires, Temporal/versions/0.2.3/sha1
Small bugfixes:
- There was an error in the `show` method when trying to print only one row
- There were problems when trying to do a merge/outerjoin/hcat when the second argument's index members superseded the first argument's index members
=> Tag Temporal v0.2.3 [https://github.com/dysonance/Temporal.jl]

Query/versions/0.0.1/requires, Query/versions/0.0.2/requires, Query/versions/0.0.3/requires, Query/versions/0.0.4/requires, Query/versions/0.1.0/requires, Query/versions/0.2.0/requires, Query/versions/0.2.1/requires, Query/versions/0.3.0/requires, Query/versions/0.3.1/requires
Same goal as #8156, but now for the right package.
=> Update Query REQUIRES files

MP3/versions/0.0.1/requires
ref http://pkg.julialang.org/detail/MP3.html, http://pkg.julialang.org/detail/SampledSignals.html
cc @ssfrr @jongwook
=> MP3.jl 0.0.1 does not work with SampledSignals 0.3

StochDynamicProgramming/versions/0.1.0/requires, StochDynamicProgramming/versions/0.1.1/requires, StochDynamicProgramming/versions/0.1.2/requires, StochDynamicProgramming/versions/0.1.3/requires, StochDynamicProgramming/versions/0.2.0/requires, StochDynamicProgramming/versions/0.2.1/requires, StochDynamicProgramming/versions/0.2.2/requires
failing due to use of setvalue on fixed variables
http://pkg.julialang.org/detail/StochDynamicProgramming.html
=> Add JuMP 0.16 upper bound to StochDynamicProgramming

mPulseAPI/versions/1.0.5/requires, mPulseAPI/versions/1.0.5/sha1
=> Tag mPulseAPI v1.0.5

Interpolations/url
ref: https://github.com/JuliaMath/Interpolations.jl/issues/140#issuecomment-286672127
cc: @timholy
=> Move Interpolations.jl repository to JuliaMath

Julz/versions/0.0.2/requires, Julz/versions/0.0.2/sha1
Repository: djsegal/Julz.jl
Release: v0.0.2
Travis: [![Build Status](https://travis-ci.org/djsegal/Julz.jl.svg?branch=master)](https://travis-ci.org/djsegal/Julz.jl)
cc: @djsegal
-----
diff: https://github.com/djsegal/Julz.jl/compare/v0.0.1...v0.0.2
=> Tag Julz v0.0.2 [https://github.com/djsegal/Julz.jl]

NamedTuples/versions/3.0.0/requires, NamedTuples/versions/3.0.1/requires
As discussed in blackrock/NamedTuples.jl#20.
=> Update NamedTuples requirements

TikzGraphs/versions/0.4.0/requires, TikzGraphs/versions/0.4.0/sha1
Allowing for directional edges.
=> Tag TikzGraphs v0.4.0 [https://github.com/sisl/TikzGraphs.jl]

Winston/url
CI services have been reenabled and all that.
=> Update Winston URL for move to JuliaGraphics

DICOM/url, MsgPack/url, Pajarito/url
cc @ihnorton, @kmsquire, @mlubin - double-check that CI services are still running
=> Update URLs for moved packages

.test/update-redirects.jl
gives roughly 35x speedup
The empty `println()` lines were only there to make the output interrupt ProgressMeter in a better-looking way. This version runs quickly enough that ProgressMeter isn't as useful any more. Some day it would be neat if ProgressMeter could support asyncmap/pmap/map etc, but will leave that alone for now.
=> Use asyncmap in .test/update-redirects.jl

LineSearches/versions/1.0.0/requires
ref #8710 cc: @tkelman 
I hope this is sufficient
=> Put upper limit on NLSolversBase in LineSearches

DiffEqMonteCarlo/versions/0.0.1/requires, DiffEqMonteCarlo/versions/0.1.0/requires, DiffEqParamEstim/versions/0.0.1/requires, DiffEqParamEstim/versions/0.0.2/requires, DiffEqParamEstim/versions/0.0.3/requires, DiffEqParamEstim/versions/0.0.4/requires, DiffEqParamEstim/versions/0.1.0/requires, ParameterizedFunctions/versions/0.6.0/requires, ParameterizedFunctions/versions/1.0.0/requires, ParameterizedFunctions/versions/1.1.0/requires, ParameterizedFunctions/versions/1.1.1/requires, ParameterizedFunctions/versions/1.2.0/requires
These will be required for a big Base change.
=> max versions on diffeq

.test/METADATA.jl, .test/check-pr.jl, .test/ci.sh, .test/travis.sh, .travis.yml
I adjusted the testing code so that the code works with other CIs.
=> Refactor METADATA tests to work outside of Travis CI

DiffEqMonteCarlo/versions/0.2.0/requires, StochasticDiffEq/versions/1.4.0/requires
These are the only two needed.
=> max version bounds for diffeqbase 1.0.0

DiffEqDevTools/versions/0.7.0/requires, DiffEqSensitivity/versions/0.1.0/requires
This needs a max bound due to a typing change.
=> max bound devtools

CompEcon/versions/0.2.0/requires, CompEcon/versions/0.2.1/requires
=> Change upper bound on BasisMatrices dependency inside CompEcon

JSON/versions/0.10.0/requires
ref https://github.com/JuliaLang/METADATA.jl/pull/9093#issuecomment-298819420
=> Make JSON 0.10 require Julia 0.5

GroveAlg/url, GroveAlg/versions/0.0.1/requires, GroveAlg/versions/0.0.1/sha1
https://github.com/chakravala/GroveAlg.jl
=> Register GroveAlg [https://github.com/chakravala/GroveAlg.jl.git]: v0.0.1

PGFPlots/versions/1.6.0/requires, PGFPlots/versions/1.6.0/sha1
Removed precompilation due to package dependencies that are not precompiled.
=> Pull request/ae42f704

DiffEqMonteCarlo/versions/0.3.0/requires, DiffEqMonteCarlo/versions/0.4.0/requires
Upper bounds due to number of fields change in the MonteCarloProblem type,
=> upper bounds for incoming change

Fatou/versions/0.0.3/requires, Fatou/versions/0.0.3/sha1
Improved performance of `orbitplot` function, it was just too slow! much quicker now
Diff vs v0.0.2: https://github.com/chakravala/Fatou.jl/compare/7be430d7d6f39f02c2effc499578754dcf84973a...6e894a436a935e295bb5bcd3fe54aae1e04fdbe4
Also, another major update is planned to completely generalize the Fatou sets to other types and move the images and explanations to the wiki, to make the README shorter, but it's not ready yet.
=> Tag Fatou v0.0.3

Gadfly/versions/0.6.2/requires, Gadfly/versions/0.6.2/sha1
Diff vs v0.6.1: https://github.com/GiovineItalia/Gadfly.jl/compare/16018ad198d50d5a951faa46ad5e444a80df5a49...05f4df1d6ac01eacdab415ea20e874be3623f6a4
=> Tag Gadfly v0.6.2 [https://github.com/GiovineItalia/Gadfly.jl]

DiffEqMonteCarlo/versions/0.5.0/requires
=> add upper bound for type changes

.test/ci.sh
@staticfloat should we be doing this here, on the website, PkgDev.generate etc too?
=> Use cached urls for travis julia downloads

FilePaths/versions/0.1.0/requires, FilePaths/versions/0.1.0/sha1
Diff vs v0.0.1: https://github.com/rofinn/FilePaths.jl/compare/fe6ef4dd6072b4647b1f6e32608b8d4112988728...b5c8d72a084195af8140452b0d816b3184c2e50b
=> Tag FilePaths v0.1.0 [https://github.com/rofinn/FilePaths.jl]

CUSOLVER/url
Reflect migration to JuliaGPU org
=> Update CUSOLVER URL

Temporal/versions/0.3.0/requires, Temporal/versions/0.3.0/sha1
Tag Temporal v0.3.0 [https://github.com/dysonance/Temporal.jl]
Diff vs v0.2.5: https://github.com/dysonance/Temporal.jl/compare/e455d3e1492bea01cd15a63cfd358277b013a6d7...b6be8608f68c05f5692e1bebc1bf2acbf26b1f05
=> Temporal: Yahoo Finance API Fix!

StructJuMP/url, StructJuMP/versions/0.0.1/requires, StructJuMP/versions/0.0.1/sha1
Repository: [StructJuMP/StructJuMP.jl](https://github.com/StructJuMP/StructJuMP.jl)
Release: [v0.0.1](https://github.com/StructJuMP/StructJuMP.jl/releases/tag/v0.0.1)
Travis: [![Build Status](https://travis-ci.org/StructJuMP/StructJuMP.jl.svg?branch=master)](https://travis-ci.org/StructJuMP/StructJuMP.jl)
cc: @joehuchette @blegat @ktarplee @kibaekkim @cnpetra @michel2323 @fqiang @emreyamangil
=> Register new package StructJuMP.jl v0.0.1

Ito/versions/0.0.0/requires, Ito/versions/0.0.1/requires, Ito/versions/0.0.2/requires
=> Deprecate Ito

PowerModels/versions/0.3.2/requires, PowerModels/versions/0.3.2/sha1
Diff vs v0.3.1: https://github.com/lanl-ansi/PowerModels.jl/compare/4488d66ae45c2ad523c1514a384ae4cb15242e2b...16e2abc843b0cddd7e4326bed7de0cad7e92b6fb
=> Tag PowerModels v0.3.2 [https://github.com/lanl-ansi/PowerModels.jl]

NOAAData/url, NOAAData/versions/0.0.1/requires, NOAAData/versions/0.0.1/sha1
Adding NOAAData v0.0.1 with proper julia version
=> Pull request/4164bdc7

InspectDR/versions/0.2.1/requires, InspectDR/versions/0.2.1/sha1
Improve how layouts are controlled +ready for user-defined stylesheets.
Diff vs v0.2.0: https://github.com/ma-laforge/InspectDR.jl/compare/e59b5812519eca157f6432cb4f3f7166b9dee81a...31bc0b1389a3e3cccf98fc6d4031e1ff6ad31acd
=> Tag InspectDR v0.2.1 [https://github.com/ma-laforge/InspectDR.jl]

BioSequences/versions/0.6.2/requires, BioSequences/versions/0.6.2/sha1
Diff vs v0.6.1: https://github.com/BioJulia/BioSequences.jl/compare/3904c46d6f513dae3cb13c533c46251e09adff5a...3c02bfe7cf8999ce191adcc93f4a7aaf6beb88ce
=> Tag BioSequences v0.6.2 [https://github.com/BioJulia/BioSequences.jl]

XSim/versions/0.1.0/requires
caused issues on pkgeval https://github.com/JuliaCI/pkg.julialang.org/blob/345bf6547d534e4238f05e3aeacda45bb5db5379/logs/XSim_0.4.log
cc @reworkhow
=> revert lower bound change from #10053

TakingBroadcastSeriously/versions/0.1.0/requires
=> this package doesn't support 0.5

Pyramids/versions/0.0.1/requires
=> Place upper bound on Images dependency of Pyramids

FaceDatasets/versions/0.1.0/requires, FaceDatasets/versions/0.1.1/requires, FaceDatasets/versions/0.1.2/requires, FaceDatasets/versions/0.1.3/requires, FaceDatasets/versions/0.1.4/requires, FaceDatasets/versions/0.2.0/requires
the Image type no longer exists, ref https://github.com/JuliaLang/METADATA.jl/pull/10251 cc @dfdx
=> Upper bound FaceDatasets' Images dependency to 0.11

Mads/versions/0.4.18/requires, Mads/versions/0.4.18/sha1
HDF5 crashes on Travis; but all the tests work otherwise.
Diff vs v0.4.17: https://github.com/madsjulia/Mads.jl/compare/2b348784049e976d7bfae22a3a370efcc14c2553...8fe02bd9b4e51b6edafeccfcaee730be08bb97f8
=> Tag Mads v0.4.18 [https://github.com/madsjulia/Mads.jl]

Diana/versions/0.0.2/requires, Diana/versions/0.0.2/sha1
Diff vs v0.0.1: https://github.com/codeneomatrix/Diana.jl/compare/59c9f516ef249ed266b1a9f020fef07287f7cd9b...3568ccba29a1ab406db50eab42a43c2d3c2fdfc0
* Client rewrite
=> Tag Diana v0.0.2 [https://github.com/codeneomatrix/Diana.jl]

GeneticVariation/versions/0.1.0/requires
@tkelman Will this prevent BioSequences 0.7 issues in the brief interim whilst I work on GeneticVariation? #10452
=> BioSequences 0.7 upper bound for GeneticVariation.jl

OhMyREPL/versions/0.1.0/requires
Fixes https://github.com/KristofferC/OhMyREPL.jl/issues/93
Is this correct @tkelman?
=> upper bound Tokenize for OhMyREPL 0.5

Tokenize/versions/0.2.0/requires, Tokenize/versions/0.2.0/sha1
Did this manually so hopefully it is right
=> tag Tokenize 0.2.0

CUDAnative/versions/0.1.0/requires, CUDAnative/versions/0.1.1/requires, CUDAnative/versions/0.1.2/requires, CUDAnative/versions/0.1.3/requires, CUDAnative/versions/0.2.0/requires, CUDAnative/versions/0.3.0/requires, CUDAnative/versions/0.3.1/requires
=> Update bounds on CUDAnative

JuliaFEM/versions/0.3.2/requires, JuliaFEM/versions/0.3.2/sha1
Diff vs v0.3.1: https://github.com/JuliaFEM/JuliaFEM.jl/compare/6fcba926d0fb1d2d86007a9388e1dea67809be3e...dc75cfda0363acfafbd2d3b000ff5158c8661f86
=> Tag JuliaFEM v0.3.2 [https://github.com/JuliaFEM/JuliaFEM.jl]

Curvelet/url, Curvelet/versions/0.0.1/requires, Curvelet/versions/0.0.1/sha1
Curvelet.jl is a package which implements the Uniform Discrete Curvelet Transform (UDCT) used in image processing.
=> Register Curvelet.jl Package

AWSCore/url
Migrate AWSCore.jl from samoconnor account to JuliaCloud account
=> Migrate AWSCore.jl to JuliaCloud github account

CUDAnative/versions/0.1.2/requires, CUDAnative/versions/0.1.3/requires, CUDAnative/versions/0.2.0/requires, CUDAnative/versions/0.3.0/requires, CUDAnative/versions/0.3.1/requires, CUDAnative/versions/0.4.0/requires, CUDAnative/versions/0.4.1/requires, CUDAnative/versions/0.4.2/requires, CUDAnative/versions/0.5.0/requires
Ref JuliaGPU/CUDAnative.jl#110
=> Add upper bounds to CUDAnative for LLVM.

ImageSegmentation/versions/0.0.1/requires
Noted here: https://github.com/JuliaImages/ImageSegmentation.jl/issues/16
=> ImageSegmentation: set required version on Clustering

DataCubes/versions/0.2.0/requires, DataCubes/versions/0.2.0/sha1
Diff vs v0.1.0: https://github.com/c-s/DataCubes.jl/compare/ec27b6dafb700c16e0739c0e547d7b9528134384...5573e2d3bef571e35c51ad9ec95ca67ff1b6d60c
=> Tag DataCubes v0.2.0 [https://github.com/c-s/DataCubes.jl]

DataFrames/url
=> Change DataFrames URL from JuliaStats to JuliaData

CUDAnative/versions/0.4.0/requires, CUDAnative/versions/0.4.1/requires, CUDAnative/versions/0.4.2/requires, CUDAnative/versions/0.5.0/requires
CUDAdrv 0.5.3 doesn't define debug etc.
cc @SimonDanisch
=> Fix upper bounds for CUDAnative.

RigidBodyDynamics/versions/0.3.0/requires
Fixes https://github.com/tkoolen/RigidBodyDynamics.jl/issues/332.
=> Upper bound TypeSortedCollections for RigidBodyDynamics.

CSVFiles/versions/0.0.1/requires, CSVFiles/versions/0.1.0/requires, CSVFiles/versions/0.1.1/requires, CSVFiles/versions/0.2.0/requires, CSVFiles/versions/0.3.0/requires, CSVFiles/versions/0.3.1/requires, CSVFiles/versions/0.4.0/requires
As recommended by @davidanthoff in #11307
=> remove TextParse upperbound for CSVFiles

Mads/versions/0.4.27/requires, Mads/versions/0.4.27/sha1
Diff vs v0.4.26: https://github.com/madsjulia/Mads.jl/compare/ba31d323335994b5c9fd5b9c87624c5669428805...1ffe5a11fe62dd6e9a1c0bfb906d4f35efdef7cb
=> Tag Mads v0.4.27 [https://github.com/madsjulia/Mads.jl]

GAFramework/url, GAFramework/versions/0.0.1/requires, GAFramework/versions/0.0.1/sha1
Hi, I would like to register GAFramework.jl. It's a package containing a genetic algorithm framework in Julia.
=> Pull request/b540ae13 Registering package GAFramework.jl, a genetic algorithm framework

DelayDiffEq/versions/1.3.0/requires
bound for dtacc change in OrdinaryDiffEq which will break DelayDiffEq
=> Bound DelayDiffEq

FEHM/url, FEHM/versions/0.1.0/requires, FEHM/versions/0.1.0/sha1
=> Register FEHM [https://github.com/zemjulia/FEHM.jl.git]: v0.1.0

LRUCache/url
=> Update LRUCache URL for move to JuliaCollections

OSQP/url, OSQP/versions/0.1.0/requires, OSQP/versions/0.1.0/sha1
Added OSQP.jl package and tagged version `0.1.0`.
=> Added OSQP.jl package

CSDP/versions/0.0.3/requires
Same as https://github.com/JuliaLang/METADATA.jl/pull/12026 for the CSDP solver.
=> update MathProgBase upper bound

MixedModels/versions/0.13.0/requires
cf: https://github.com/JuliaLang/METADATA.jl/pull/12059#issuecomment-347305690
=> Add DataFrames upper bound to MixModels 0.13.0

RData/url
=> Update RData url as it's moved to JuliaData

Graphs/versions/0.9.0/requires, Graphs/versions/0.9.0/sha1
[![Build Status](https://travis-ci.org/JuliaArchive/Graphs.jl.svg?branch=master)](https://travis-ci.org/JuliaArchive/Graphs.jl)
[Graphs.jl](https://github.com/JuliaArchive/Graphs.jl)
[v0.9.0](https://github.com/JuliaArchive/Graphs.jl/releases/tag/v0.9.0)
Diff vs v0.8.0: https://github.com/JuliaArchive/Graphs.jl/compare/784d12602dd3eefa2f94824ae7daf2b42b8c6b6c...4d6cfe1e44e2be0c13dcfa4ec2a6707a3177b995
=> Tag Graphs v0.9.0 [https://github.com/JuliaArchive/Graphs.jl]

BlackBoxOptimizationBenchmarking/url, BlackBoxOptimizationBenchmarking/versions/0.0.1/requires, BlackBoxOptimizationBenchmarking/versions/0.0.1/sha1
https://github.com/jonathanBieler/BlackBoxOptimizationBenchmarking.jl.git : v0.0.1
=> Register BlackBoxOptimizationBenchmarking 

LineSearches/versions/3.0.0/requires, LineSearches/versions/3.0.1/requires, LineSearches/versions/3.1.0/requires, LineSearches/versions/3.2.0/requires, LineSearches/versions/3.2.1/requires, LineSearches/versions/3.2.2/requires, LineSearches/versions/3.2.3/requires, NLsolve/versions/0.12.0/requires, NLsolve/versions/0.12.1/requires, NLsolve/versions/0.13.0/requires, Optim/versions/0.10.0/requires, Optim/versions/0.10.1/requires, Optim/versions/0.11.0/requires, OptimBase/versions/0.1.0/requires
should be merged before https://github.com/JuliaLang/METADATA.jl/pull/12538
=> Upper bounds on NLSolversBase.

JuMP/versions/0.18.0/requires
https://github.com/JuliaOpt/JuMP.jl/pull/1150
No new tag needed.
=> Update JuMP's ForwardDiff upper bound

DSGE/versions/0.1.4/requires, DSGE/versions/0.1.5/requires, DSGE/versions/0.2.0/requires, DSGE/versions/0.3.0/requires, DSGE/versions/0.3.1/requires, DSGE/versions/0.4.0/requires
ref https://github.com/JuliaLang/METADATA.jl/pull/12709
=> Put upper bound on Optim in DSGE.

FourierFlows/url, FourierFlows/versions/0.0.1/requires, FourierFlows/versions/0.0.1/sha1
This software provides solvers for partial differential equations on doubly-periodic domains using Fourier-based pseudospectral methods. A central intent of the software's design is also to provide a framework for writing new, fast solvers for new physical problems.
=> First commit for FourierFlows.jl

ChaosTools/versions/0.1.0/requires, ChaosTools/versions/0.2.0/requires, ChaosTools/versions/0.2.1/requires, ChaosTools/versions/0.3.0/requires
Fixes JuliaCI tests failing on the Pull Requsts for DynamicalSystemsBase 0.3
=> Add upper bounds to ChaosTools.jl

Microeconometrics/versions/0.1.0/requires, Microeconometrics/versions/0.1.1/requires, Microeconometrics/versions/0.1.2/requires, Microeconometrics/versions/0.2.0/requires
ref https://github.com/JuliaLang/METADATA.jl/pull/12709
=> Put upper bounds on Optim in Microeconometrics.

LanguageServer/versions/0.2.0/requires, LanguageServer/versions/0.2.1/requires, LanguageServer/versions/0.2.2/requires, LanguageServer/versions/0.3.0/requires
This should fix the Juliabot errors in #12861.
CC @ZacLN.
=> Add upper bound to LanguageServer

.test/ci.sh
cherry pick one commit from #12891
=> Only run tests on the current release version

StatFiles/versions/0.2.0/requires
Prep for an upcoming breaking ReadStat tag.
=> Add some bounds to StatFiles

Microbiome/url
Microbiome.jl is now part of BioJulia
=> update url for Microbiome.jl

DandelionWebSockets/url, DandelionWebSockets/versions/0.1.0/requires, DandelionWebSockets/versions/0.1.0/sha1
Registering a WebSocket client package.
=> Pull request/e11e19b3

ConformalMaps/url, ConformalMaps/versions/0.0.1/requires, ConformalMaps/versions/0.0.1/sha1
This package defines `ConformalMap` and `InverseConformalMap` types which approximate the conformal map from given polygonal region to the unit disk.
=> Publish ConformalMaps.jl

.test/ci.sh
Reverts https://github.com/JuliaLang/METADATA.jl/pull/12945
=> Perform tests on multiple versions of Julia again

AprilTags/url, AprilTags/versions/0.0.1/requires, AprilTags/versions/0.0.1/sha1
This package is a ccall wrapper for the [AprilTags](https://april.eecs.umich.edu/software/apriltag.html) library tailored for Julia.
[![Build Status](https://travis-ci.org/Affie/AprilTags.jl.svg?branch=master)](https://travis-ci.org/Affie/AprilTags.jl)
[![docs](https://img.shields.io/badge/docs-latest-blue.svg)](https://Affie.github.io/AprilTags.jl/latest/)
@dehann
=> Register AprilTags [https://github.com/Affie/AprilTags.jl.git]: v0.0.1

ExcelFiles/versions/0.0.1/requires, ExcelFiles/versions/0.1.0/requires, ExcelFiles/versions/0.2.0/requires
This is in preparation for the next ExcelReaders release.
=> Put bounds on ExcelReaders dep in ExcelFiles

.test/METADATA.jl, .test/check-pr.jl, .test/ci.sh, .test/update-redirects.jl
cc: @aviks 
As far as I can tell, no METADATA travis checks are passing while we continue to try and check w/ 0.5, so this PR drops it.
=> A few compat issues and drop 0.5 since it doesn't work anymore

NLsolve/versions/0.10.0/requires, NLsolve/versions/0.10.1/requires, NLsolve/versions/0.11.0/requires, NLsolve/versions/0.12.0/requires, NLsolve/versions/0.12.1/requires, NLsolve/versions/0.13.0/requires, NLsolve/versions/0.14.0/requires, NLsolve/versions/0.14.1/requires, NLsolve/versions/1.0.0/requires, NLsolve/versions/1.0.1/requires
ref https://github.com/JuliaLang/METADATA.jl/pull/14054
=> Upperbound LineSearches in NLsolve and Optim.

.travis.yml
This is just a test of the functionality. It will just update a private channel. If it is useful, we could consider adding a monitoring/alerts channel to the official Slack.
=> Add Slack integration

Ipopt/versions/0.3.0/requires
https://github.com/JuliaOpt/Ipopt.jl/issues/110
https://github.com/JuliaOpt/Ipopt.jl/pull/111
=> Set lower bound on Ipopt's BinaryProvider dep

EAGO/versions/0.1.0/requires
=> Upper bound IntervalArithmetic in EAGO to prevent test failure

NLPModels/versions/0.0.1/requires, NLPModels/versions/0.1.0/requires, NLPModels/versions/0.2.0/requires, NLPModels/versions/0.3.0/requires
=> Add upper bounds in NLPModels

ExcelDataStreams/url, ExcelDataStreams/versions/0.0.1/requires, ExcelDataStreams/versions/0.0.1/sha1
I'm registering a simple module to make an Excel file into a DataStream.
=> Pull request/d1ae0e8c

InternedStrings/url
I transferred the Repo to the Org,
so now I need to update this URL before I can publish anymore releases
=> Move InternedStrings.jl to JuliaString Org

JSON/versions/0.17.2/requires
See https://github.com/JuliaIO/JSON.jl/commit/f05dd3d26976ae8310cfb512cf0106505e95b51b#commitcomment-28964093
=> Fix Compat requirement in JSON 0.17.2

CSV/versions/0.2.3/requires, CSV/versions/0.2.4/requires
See https://github.com/JuliaData/CSV.jl/pull/206
=> Update Compat lower bounds for CSV version 0.2.3 and 0.2.4

DSGE/versions/0.2.0/requires, DSGE/versions/0.3.0/requires, DSGE/versions/0.3.1/requires, DSGE/versions/0.4.0/requires, DSGE/versions/0.4.1/requires
Addresses https://github.com/JuliaLang/METADATA.jl/pull/14695#issuecomment-391338204. We plan to upgrade DSGE to work with the new StateSpaceRoutines release and tag a new (DSGE) release soon.
=> Add upper bound on StateSpaceRoutines in DSGE

Turing/url
=> Update Turing.jl URL

PtFEM/versions/0.1.1/requires
Fixes https://github.com/JuliaLang/julia/issues/27469
=> Remove stdlib packages from PtFEM require file

Hecke/versions/0.4.5/requires
I will update AbstractAlgebra, which has the potential of breaking Hecke.
=> An upper bound for Hecke

SuiteSparse/url
=> Update SuiteSparse path

BoundaryValueDiffEq/versions/0.0.1/requires, BoundaryValueDiffEq/versions/0.1.0/requires, BoundaryValueDiffEq/versions/0.2.0/requires, BoundaryValueDiffEq/versions/0.3.0/requires, BoundaryValueDiffEq/versions/1.0.0/requires
See https://github.com/JuliaLang/METADATA.jl/pull/15205#issuecomment-397965707
and
https://github.com/JuliaDiffEq/BoundaryValueDiffEq.jl/pull/35
=> Upper bound for BandedMatrices in BoudaryValueDiffEq
